### ISSUE TITLE
Build fails on CI environment(appcenter) with react-native-agora

### ISSUE THREAD

**Issue by sharathchandramg** [AgoraIO-Community/react-native-agora#174]
Hi,
I am using react-native-agora in our application and have managed to integrate to both android and iOS. 

I am facing problems mainly on building the application on our CI server(Microsoft Appcenter)

The issue is :

1. The local repo builds without any errors and works. Builds works even on cleaning the node_modules and Pods reinstalled. (The local build logs are available @ https://www.dropbox.com/s/on4ge5z9ihicqsd/Build%20Integration_2020-04-27T12-24-50.txt?dl=0)

2. The same local build fails on Appcenter with multiple errors. The same issue is happening on other CI platforms like bitrise. (The appcenter build logs are available @ https://www.dropbox.com/s/rg2sju0x1tnw2x5/appcenter_logs_with_agora.zip?dl=0)

I have created a public repo for further debugging. 
Repo: [https://dev.azure.com/viewease/ia-build/_git/ia-mobile?version=GBagora-ios](url)
Branch Name: agora-ios
 
We have removed agora and then the builds work fine both on local and appcenter
Repo: https://dev.azure.com/viewease/ia-build/_git/ia-mobile?version=GBremoving-agora
Branch Name: removing-agora
The appcenter logs are available @ https://www.dropbox.com/s/2oz4v0quhuxfu4k/appcenter_logs_without_agora.zip?dl=0

I have tried changing the header search paths for all of them as "non-recursive", but the issue on appcenter persists.

The issue occurring during archiving stage, it shows the AgoraRtcEngineKit.framework missisng issues. 

Some one please help on this.

Thanks

**Comment by LichKing-2234** [comment]
sorry for the late reply, is this problem still exits?

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
