### ISSUE TITLE
Error while updating property 'showLocalView'

### ISSUE THREAD

**Issue by KaviduAloka** [AgoraIO-Community/react-native-agora#2]
I have created a video calling app using react-native and react-native-agora. This works ok most of the times. But sometimes an error occurs in local video preview.

Error in :

`<AgoraView style={styles.localVideoStyle} zOrderMediaOverlay showLocalVideo mode={1} />`

Error:

> Error while updating property 'showLocalVideo' of a view managed by: RTCAgoraVideoView
> 
> null
> 
> No implementation found for int io.agora.rtc.internal.RtcEngineImpl.nativeLog(int, java.lang.String) (tried Java_io_agora_rtc_internalRtcEngineImpl_nativeLog and Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog_ILjava_lang_String_2)

I am still trying to figure out the issue...

**Comment by KaviduAloka** [comment]
This only happened because the local video was not ready. And it is solved

**Comment by kvlknctk** [comment]
@KaviduAloka 
Can you say where error?

**Comment by KaviduAloka** [comment]
> @KaviduAloka
> Can you say where error?

Set the video preview height and width
