### ISSUE TITLE
ios  Native module cannot be null.

### ISSUE THREAD

**Issue by KarenQiao** [AgoraIO-Community/react-native-agora#203]

**Comment by LichKing-2234** [comment]
what version of your RN, have you link the module?

**Comment by KarenQiao** [comment]
react-native-cli: 2.0.1
react-native: 0.59.9

yes, i am sure that i have already linked. use react-native link react-native-agora.

**Comment by LichKing-2234** [comment]
please double-check, better link it by yourself

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
