### ISSUE TITLE
While video calling in react-native ios app, local video view is not showing on join video channel for both party.

### ISSUE THREAD

**Issue by ChandreshRana** [AgoraIO-Community/react-native-agora#207]
while video calling in react-native IOS app, there are two types of video rendering local and remote. But local video view is not showing on join video channel from both party. both the party can only see each other on the screen but they are not able to see their own local video view on screen as a small view on right side top corner. But if we toggle video button couple of time then its start appear.

```
 toggleVideo() {
    let mute = this.state.vidMute
    console.log('Video toggle', mute)
    this.setState({
      vidMute: !mute,
    })
    RtcEngine.muteLocalVideoStream(!this.state.vidMute)
  }
```

- other peoples are also facing this issue:
i)  https://github.com/syanbo/react-native-agora/issues/108
ii) https://github.com/syanbo/react-native-agora/issues/51

I had try some of the solutions but not get the desired result.

I had same issue in android but i resolved it by adding "zOrderMediaOverlay" as true on agora view and it works for android. but same it's not work for IOS.

Here is sample agoraview code:

```
 <AgoraView
            style={styles.localVideoStyle}
            zOrderMediaOverlay={true}
            showLocalVideo={true}
            mode={1}
          />
```

Please guide us to resolve this issue.

**Comment by tinyCoder32** [comment]
Same here.

**Comment by bamaarintoko** [comment]
same here

**Comment by rebirthtobi** [comment]
@ChandreshRana I got localvideo to show by listening to `joinSuccess`

```
RtcEngine.on("joinChannelSuccess", this._onJoinedSuccess);
--------
@autobind
    private _onJoinedSuccess() {
        void RtcEngine.startPreview();
        void RtcEngine.enableAudio();
        void RtcEngine.enableVideo();
        this.setState({ joined: true });
    }
-----------------
{joined
                    ? (
                        <>
                            {!muteVideo
                                ?   <AgoraView
                                    style={isPearPresent ? styles.localVideoStyle : styles.wrapper}
                                    mode={1}
                                    showLocalVideo={true}
                                    remoteUid={peerIds[0]}
                                    zOrderMediaOverlay={true}
                                />
                                : null
                            }
                            {isPearPresent
                                ? <AgoraView
                                    style={styles.wrapper}
                                    mode={1}
                                    remoteUid={peerIds[0]}
                                    showLocalVideo={false}
                                    zOrderMediaOverlay={false}
                                />
                                : null
                            }
                        </>
                    )
                    : null
                }
```


Pardon my code, I am using typescript, which means i have to set `showLocalVideo` to false on the other.

Basically, what i did is use a state to manage when local video has joined channel, when local video join the channel then render local video.

but my remote video is still not showing

**Comment by LichKing-2234** [comment]
please try the latest version

**Comment by kennguyen1506** [comment]
> @ChandreshRana I got localvideo to show by listening to `joinChannelSuccess `
> 
> ```
> RtcEngine.on("joinChannelSuccess", this._onJoinedSuccess);
> --------
> @autobind
>     private _onJoinedSuccess() {
>         void RtcEngine.startPreview();
>         void RtcEngine.enableAudio();
>         void RtcEngine.enableVideo();
>         this.setState({ joined: true });
>     }
> -----------------
> {joined
>                     ? (
>                         <>
>                             {!muteVideo
>                                 ?   <AgoraView
>                                     style={isPearPresent ? styles.localVideoStyle : styles.wrapper}
>                                     mode={1}
>                                     showLocalVideo={true}
>                                     remoteUid={peerIds[0]}
>                                     zOrderMediaOverlay={true}
>                                 />
>                                 : null
>                             }
>                             {isPearPresent
>                                 ? <AgoraView
>                                     style={styles.wrapper}
>                                     mode={1}
>                                     remoteUid={peerIds[0]}
>                                     showLocalVideo={false}
>                                     zOrderMediaOverlay={false}
>                                 />
>                                 : null
>                             }
>                         </>
>                     )
>                     : null
>                 }
> ```
> 
> Pardon my code, I am using typescript, which means i have to set `showLocalVideo` to false on the other.
> 
> Basically, what i did is use a state to manage when local video has joined channel, when local video join the channel then render local video.
> 
> but my remote video is still not showing

have you encountered an issue when localview does not work on a releaseAPK for android. my code is exactly like yours and it works on debug mode, but does not work on a release build.

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
