### ISSUE TITLE
Export declared types in RtcEvents too

### ISSUE THREAD

**Issue by marqroldan** [AgoraIO-Community/react-native-agora#215]
Can someone please enlighten me why these aren't also exported? I wanted to make sure that the function I'm creating is of 'x' type so I'm aware of the proper parameters passed without having to check the typed object if I'm doing it correctly (passed functions without parameters as long as it has the correct return value are allowed)

Thanks!

**Comment by LichKing-2234** [comment]
you use the TS to develop? maybe it is my mistake.

**Comment by marqroldan** [comment]
Yes I do, but I'm also new to it so I'm not sure if it's the right way to do

For example

```
warningCallback = () => {
//void
}


const TestObject: RtcEngineEvents = {
 Warning: this.warningCallback
} as RtcEngineEvents;
```

There's no type error because it is correct that `this.warningCallback` is void
But, I wanted to know the parameters that it passes to the function so I needed to use the type `WarningCallback` 

something like this instead



```
warningCallback: WarningCallback = ( /** with intellisense i now know the parameters it could have **/) => {
//void
}


const TestObject: RtcEngineEvents = {
 Warning: this.warningCallback
} as RtcEngineEvents;
```

It's a very minor issue

**Comment by LichKing-2234** [comment]
you mean the events object contains all of the events?

**Comment by marqroldan** [comment]
I'm no expert in how Typescript types/interfaces should be exported, but since it's something minor I just exported everything I needed.

**Comment by LichKing-2234** [comment]
these have been exported.
