### ISSUE TITLE
Error while updating property 'showLocalVideo' of a view managed by: RCTAgoraVideoView

### ISSUE THREAD

**Issue by kvlknctk** [AgoraIO-Community/react-native-agora#224]
Hi,

I only encounter this problem in the project I created. While everything is going well, it gives this error after the program is closed and opened. It works smoothly for the first time but closes on the second. 
I guess I can't close the agora properly with modal. My close method;

```js 
  endCall = () => {
        RtcEngine.leaveChannel().then(r => {
            this.setState({
                peerIds    : [],
                joinSucceed: false,
            });
            this.props.CallStore.closeModal();
        });

    }
```

the second time I try to open the program I get this error.
![alt text](https://i.imgur.com/8nb8BIR.png "ss")

this is where I get the error
![alt text](https://i.imgur.com/j11R5f6.png "ss")

can this parameter have a special use? or am I using it in the wrong place?

Best regards.

**Comment by LichKing-2234** [comment]
Maybe you can try the beta version

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
