### ISSUE TITLE
Poor video call quality

### ISSUE THREAD

**Issue by sebazh** [AgoraIO-Community/react-native-agora#231]
Hi guys. Thank you for this awesome package.

We are using agora for audio/video calls between mobile-to-mobile and mobile-to-web calls.
We faced with poor video calls quality from time to time (especially in calls between mobile and web clients). 

Could someone give a recommendations or suggestions how to improve it please? 

Here is one example of a call with poor video quality:
<img width="1149" alt="Screenshot 2020-07-07 at 15 14 15" src="https://user-images.githubusercontent.com/51706160/86780788-cc4c3e00-c065-11ea-9bdf-854295b7fde3.png">

As you see there is a lot of "Blurry video", "Very choppy video", "No video" logs in the chart of the call. But both users had good internet connection. I use default audio/video profiles. 

Let me know if you need more information

Please someone point me what might be wrong. 
Thanks in advance

**Comment by LichKing-2234** [comment]
sorry for the late reply, could you pls provide our SDK log file?

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.

**Comment by Dinox869** [comment]
Hey, I'm developing an app using Agora , my sound quality is amazing but the video quality is poor. I've used 
VideoEncoderConfiguration config = VideoEncoderConfiguration();
    config.dimensions = Size(640, 480);
    config.frameRate  = 15;
    config.bitrate = AgoraVideoBitrateStandard;
    await AgoraRtcEngine.setVideoEncoderConfiguration(
     config
    ); 
and also tried : 
 await AgoraRtcEngine.setParameters( '''{\"che.video.lowBitRateStreamParameter\{\"width\":1280,\"height\":720,\"frameRate\":30,\"bitRate\":2260}}''' );
The video is still shaky even under good netwrok connection

**Comment by LichKing-2234** [comment]
@Dinox869 Have you try `config.dimensions = Size(1280, 720);`?
