### ISSUE TITLE
modular_header error while installing react-native-agora@3.0.0-beta.4

### ISSUE THREAD

**Issue by sayeed545** [AgoraIO-Community/react-native-agora#233]
I tried to installing react-native-agora@3.0.0-beta.4. After installing library, on iOS while installing pod files I got the following error. Attaching screenshot.

I tried adding modular_header but it is effecting my existing libraries in package.json. (RNFS, react-native-image-crop-picker).

My current package.json file and a few library versions:

"react": "16.8.3",  
"react-native": "0.59.10",
"react-native-agora": "^2.9.1-alpha.3",
"agora-react-native-rtm": "^1.0.1-alpha.1",
"react-native-fs": "^2.16.2",
"react-native-image-crop-picker": "^0.24.0",

Thanks.
![RNAgoraError](https://user-images.githubusercontent.com/59599614/87011700-e57bf880-c1e5-11ea-9e7e-415d50d93447.png)

**Comment by LichKing-2234** [comment]
you should unlink and uninstall the alpha version before you use the beta version.

**Comment by LichKing-2234** [comment]
and many API is different from the alpha version.

**Comment by sayeed545** [comment]
I tried unlink and uninstall the alpha version and install the beta version I am getting the same error

**Comment by LichKing-2234** [comment]
you can refer to the install doc.
https://github.com/syanbo/react-native-agora/blob/master/docs/v3/installation.ios.md

**Comment by LichKing-2234** [comment]
by the way, what version of your cocoapods

**Comment by shubh08** [comment]
I am also facing the same issue while trying to do pod install after running  
`react-native link react-native-agora`

My RN version -  0.59.10

**Comment by LichKing-2234** [comment]
@shubh08 you can refer to our podfile.

https://github.com/AgoraIO-Community/react-native-agora/blob/master/docs/v3/installation.ios.md#using-with-cocoapods-recommended

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.

**Comment by reinhardholl** [comment]
I am also experiencing this issue adding `3.0.0` to an existing project running React Native `0.59.10`. Error is:

```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `react-native-agora` depends upon `React`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

As @sayeed545 pointed out, setting `modular_header => true` breaks existing packages.
