### ISSUE TITLE
could not find compatible versions for pod "AgoraRtcEngine_iOS_Crypto" In Podfile

### ISSUE THREAD

**Issue by sayeed545** [AgoraIO-Community/react-native-agora#236]
While installing latest release version with react-native-agora": "3.0.1-rc.1", I am getting the following below error in my pod files. 

Please let me know how to fix it.

_[!] CocoaPods could not find compatible versions for pod "AgoraRtcEngine_iOS_Crypto":
  In Podfile:
    react-native-agora (from `../node_modules/react-native-agora`) was resolved to 3.0.1-rc.1, which depends on
      AgoraRtcEngine_iOS_Crypto (= 3.0.1.1)

None of your spec sources contain a spec satisfying the dependency: `AgoraRtcEngine_iOS_Crypto (= 3.0.1.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile._

My current react native version is: 0.59.10. I am unlinked and uninstalled the previous version properly and have tried installing the latest.

Thanks.

![Screen Shot 2020-07-15 at 4 00 12 PM](https://user-images.githubusercontent.com/59599614/87535229-c7fed100-c6b4-11ea-89bc-ca03468a0a6c.png)

**Comment by LichKing-2234** [comment]
out-of-date source repos which you can update with pod repo update or with pod install --repo-update.

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.

**Comment by maerlynflagg** [comment]
> out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.

`pod repo update` not help to solve the issue and `pod install --repo-update` gave me the error _could not find compatible..._

the only help for me was: 

1. remove Podfile.lock
2. pod install --repo-update in the directory, where is the Podfile  
3. build ios app again
