### ISSUE TITLE
Swift errors during compilation

### ISSUE THREAD

**Issue by ian** [AgoraIO-Community/react-native-agora#237]
Running new Xcode Version 12.0 beta 2.  Gettting Swift compilation errors:

<img width="871" alt="CleanShot 2020-07-18 at 16 28 17@2x" src="https://user-images.githubusercontent.com/19853/87862300-0fcf6380-c914-11ea-92ca-61ba344e03a3.png">

**Comment by LichKing-2234** [comment]
is it works with Xcode 11?

**Comment by ian** [comment]
I actually think this is a result of upgrading from 2.9.1 alpha7 -> 3.0.1 rc1.  After upgrading, Swift compilation fails in both Xcode 11 and beta 12.  

Searches online seem to indicate that swift files need to be suffixed with .mm and .hh instead of .m and .h.  I looked for a solution to always treat .m and .h files as swift but I don't seem to be able to solve this.

If you have any suggestions let me know.  Otherwise, is it too big of an ask to request that your codebase follow Swift file naming standards?  I don't know if others are dealing with this but for now I'm going to downgrade back to 2.9.1.

**Comment by ian** [comment]
Can confirm rolling back to 2.9.1 fixes compile errors.

**Comment by LichKing-2234** [comment]
what your RN version?

**Comment by LichKing-2234** [comment]
have you done this?
https://github.com/syanbo/react-native-agora/blob/master/docs/v3/installation.ios.md#step-1-migrating-to-swift

**Comment by LichKing-2234** [comment]
if you are using auto-linking, pls ignore the Step2

**Comment by ian** [comment]
I am using cocopods and have done the npx pod-init, yes.  And yes, I have a swift file.

The RN 0.63 Podfile is quite different so I am not copying and pasting like you are suggesting.  If you need one line from that file (which I'm unaware of) then you might want to update the instructions to specify which that is.  Overwriting the Podfile is bad form.

This still doesn't explain why 3.x doesn't compile but 2.9 compiles?

**Comment by LichKing-2234** [comment]
pls share your `react-native info`

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
