### ISSUE TITLE
raw video data support

### ISSUE THREAD

**Issue by 0xori** [AgoraIO-Community/react-native-agora#238]
Is there any plans to add `registerVideoFrameObserver` support for react native agora?
https://docs.agora.io/en/Video/raw_data_video_android?platform=Android

**Comment by LichKing-2234** [comment]
you can add it by fork our sdk

**Comment by LichKing-2234** [comment]
RN does not support byte array, so it can only be implemented at the native layer.

you can reopen this issue if the problem still exists.

**Comment by LichKing-2234** [comment]
https://github.com/AgoraIO-Community/react-native-agora/wiki/Raw-data-Plugin-is-beta

**Comment by LichKing-2234** [comment]
same as https://github.com/AgoraIO-Community/react-native-agora/issues/81 https://github.com/AgoraIO-Community/react-native-agora/issues/113
