### ISSUE TITLE
Need help !!

### ISSUE THREAD

**Issue by mcanikhilprajapati** [AgoraIO-Community/react-native-agora#240]
Video stream working Perfet when i start with  RtcEngine.joinChannel() in React Native app
now i want to merge 2 live streaming channel with 1 

how can i archive this goal?

please help

Thanks

**Comment by LichKing-2234** [comment]
you can refer to this doc
https://docs.agora.io/en/Audio%20Broadcast/media_relay_android?platform=Android

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
