### ISSUE TITLE
RtcEngine.create crash

### ISSUE THREAD

**Issue by xiaoyongchen** [AgoraIO-Community/react-native-agora#241]
"react": "16.13.1",
 "react-native": "0.63.1",
 "react-native-agora": "^3.0.1-rc.2",

error: ibc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xfffffff9 in tid 32010 (mqt_native_modu)
ios: no problem

**Comment by LichKing-2234** [comment]
have you set correct AppId?

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.

**Comment by tuanvaisofh** [comment]
i have same issue in react native v061.3 @xiaoyongchen , Can you tell me how to fix it?.
