### ISSUE TITLE
[error][tid:com.facebook.react.JavaScript] TypeError: null is not an object (evaluating 'Agora.FPS30')

### ISSUE THREAD

**Issue by jiyunkeji** [AgoraIO-Community/react-native-agora#243]
[error][tid:com.facebook.react.JavaScript] TypeError: null is not an object (evaluating 'Agora.FPS30')

**Comment by LichKing-2234** [comment]
pls use the `3.0.1-rc.2`

**Comment by jiyunkeji** [comment]
> pls use the `3.0.1-rc.2`

I use the 3.0.1-rc.3 also have this problem. Something wrong?

**Comment by LichKing-2234** [comment]
your code is for 2.x version, you can refer to our samples

**Comment by jiyunkeji** [comment]
> your code is for 2.x version, you can refer to our samples

Even if I have created a new page ,which is according to the newest samples,  but I have this problem. why???

**Comment by LichKing-2234** [comment]
have you check out our quick start?

**Comment by LichKing-2234** [comment]
check out the quick start.
https://github.com/AgoraIO-Community/react-native-agora/blob/master/samples/README.md
