### ISSUE TITLE
null is not an object (evaluating 'AgoraRtcChannelModule.prefix')

### ISSUE THREAD

**Issue by tashanemclean** [AgoraIO-Community/react-native-agora#244]
getting this error running react native 0.60.6. Followed all the steps in the read.me

**Comment by LichKing-2234** [comment]
you may upgrade from 2.x to 3.x?

**Comment by tashanemclean** [comment]
That is the version that I am using. I was able to get up and running following the Agora RN quickstart.

**Comment by LichKing-2234** [comment]
is quickstart works fine?

**Comment by tashanemclean** [comment]
It compiles without any errors in development on ios simulator. I have not tested on a device yet.

**Comment by tashanemclean** [comment]
Using RN works fine but It seems that there is conflict when using this with expo.

**Comment by tashanemclean** [comment]
I am trying to use expo-cli 3.22.3

**Comment by LichKing-2234** [comment]
sorry, we don't support expo

**Comment by LichKing-2234** [comment]
first, run [`expo eject`](https://docs.expo.io/bare/exploring-bare-workflow/#existing-expo-managed-workflow-apps) to switch to the bare workflow.
second, run [`npx react-native run-ios` `npx react-native run-android`](https://docs.expo.io/bare/hello-world/) to run application.

**Comment by tonystark-mdx** [comment]
@LichKing-2234 I'm facing the same issue on react-native-agora v3.1.6 with react-native v0.63.4. Any fix for this?

**Comment by ShayanShokat** [comment]
@LichKing-2234 I'm facing the same issue on react-native-agora v3.1.6 with react-native v0.63.4. Any fix for this?

**Comment by LichKing-2234** [comment]
@ShayanShokat maybe you don't rerun your application after run `npm install react-native-agora`?
