### ISSUE TITLE
Getting error: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_react_native_agora

### ISSUE THREAD

**Issue by aidansalvi** [AgoraIO-Community/react-native-agora#245]
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftCompatibility50", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_react_native_agora in libreact-native-agora.a(MediaObserver.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_react_native_agora in libreact-native-agora.a(PromiseCallback.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_react_native_agora in libreact-native-agora.a(RCTAgoraRtcChannelModule.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_react_native_agora in libreact-native-agora.a(RCTAgoraRtcSurfaceViewManager.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_react_native_agora in libreact-native-agora.a(RtcChannelEvent.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_react_native_agora in libreact-native-agora.a(RtcSurfaceView.o)
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_react_native_agora in libreact-native-agora.a(RCTAgoraRtcEngineModule.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility50_$_react_native_agora)
  "__swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_react_native_agora in libreact-native-agora.a(MediaObserver.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_react_native_agora in libreact-native-agora.a(PromiseCallback.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_react_native_agora in libreact-native-agora.a(RCTAgoraRtcChannelModule.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_react_native_agora in libreact-native-agora.a(RCTAgoraRtcSurfaceViewManager.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_react_native_agora in libreact-native-agora.a(RtcChannelEvent.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_react_native_agora in libreact-native-agora.a(RtcSurfaceView.o)
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_react_native_agora in libreact-native-agora.a(RCTAgoraRtcEngineModule.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_react_native_agora)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by LichKing-2234** [comment]
which version of RN you have used?
https://github.com/syanbo/react-native-agora/blob/master/docs/v3/installation.ios.md#step-1-migrating-to-swift

**Comment by aidansalvi** [comment]
I am using: 0.61.5

**Comment by LichKing-2234** [comment]
refer to doc, add an empty swift file
