### ISSUE TITLE
Do not I need leaveChannel(RTM) if I leaveChannel(RTC)

### ISSUE THREAD

**Issue by keisan1231** [AgoraIO-Community/react-native-agora#247]
I use `react-native-agora` and `agora-react-native-rtm`

## my code

```js
RtcEngine.instance().leaveChannel();
this.client = new RtmEngine();
this.client.leaveChannel(channel_id);
```

## error

<img width=400  src='https://user-images.githubusercontent.com/46130313/88840530-9be86180-d217-11ea-9749-7b7efd4e550d.png'>

## question

I need only `leaveChannel()` of RtcEngine???

```js
RtcEngine.instance().leaveChannel();
```

**Comment by LichKing-2234** [comment]
have you tried the new version? `agora-react-native-rtm@1.2.2-alpha.1`

**Comment by keisan1231** [comment]
@LichKing-2234 

Yes. I use the lastest version.

```
"agora-react-native-rtm": "^1.2.2-alpha.1",
"react-native-agora": "^3.0.1-rc.1",
```

**Comment by LichKing-2234** [comment]
have you called joinChannel?

**Comment by keisan1231** [comment]
@LichKing-2234 

yes.

**Comment by LichKing-2234** [comment]
have you tried our demo about RTM?
https://github.com/AgoraIO/agora-react-native-rtm/tree/master/examples/chatsapp
