### ISSUE TITLE
RtcLocalView.SurfaceView freezes when joining a call 

### ISSUE THREAD

**Issue by Ali-hd** [AgoraIO-Community/react-native-agora#251]
Hi
I'm trying the latest demo and everything seems to work. I made a release apk and installed it on my phone. When testing every time the call starts between 2 users the local video just freezes on the last frame but the RtcRemoteView.SurfaceView works. 
I can't find a solution yet. I'm trying this on android. I used this [demo](https://github.com/AgoraIO-Community/Agora-RN-Quickstart/tree/sdk-v3)

**Comment by LichKing-2234** [comment]
Thanks for your issue, I have found the bug, I will fix it next version.

**Comment by LichKing-2234** [comment]
fixed in 3.0.1-rc.4
