### ISSUE TITLE
addListeners for UserJoined and UserOffline not working

### ISSUE THREAD

**Issue by hhemmati81** [AgoraIO-Community/react-native-agora#254]
I am using version 3.0.1-rc.4 and these 2 listeners aren't working. The only listener that I am able to use is JoinedChannelSuccess. I tested it with the sample code and it was the same issue. 

This doesn't cause an issue with the call but it complicates issues with cloud recording. I was trying to start cloud recording on the first peer added. Since the event listener never returns anything the cloud recording wouldn't start. The same goes for stopping the cloud recording. I was trying to stop manually started cloud recording on the last peer leaving.

**Comment by LichKing-2234** [comment]
maybe your client role is the audience?

**Comment by hhemmati81** [comment]
It turned out I had a stuck cache from when I was testing an older alpha SDK. After clearing everything out it's working properly.
