### ISSUE TITLE
Live Interactive Audio Streaming supported?

### ISSUE THREAD

**Issue by fritzfr** [AgoraIO-Community/react-native-agora#258]
My question is whether this SDK supports the Agora Product "Live Interactive Audio Streaming", or just the regular "Voice Call" product.

If so, how do I use this SDK to use the interactive product?

**Comment by syanbo** [comment]
https://github.com/AgoraIO/agora-react-native-rtm

**Comment by LichKing-2234** [comment]
@fritzfr the SDK contains all of the products about video and audio.
