### ISSUE TITLE
Video is not showing since I updated to the latest version

### ISSUE THREAD

**Issue by monkin77** [AgoraIO-Community/react-native-agora#259]
Hello. So I've been working on a project and had already video calls working with this module. However, since I updated it to the latest version, the video is not shown, although the users connect to the channel and the audio works. Hope someone can help me because I've been going through this for quite some time. Thank you
Code: 
import React, { Component } from 'react'
import { Platform, ScrollView, Text, TouchableOpacity, View, Alert, ActivityIndicator, Button, Dimensions, Image } from 'react-native'
import RtcEngine, { VideoRenderMode, RtcLocalView, RtcRemoteView, /*Types*/ } from 'react-native-agora'
import requestCameraAndAudioPermission from './Permissions'
import styles from './Style'

import Fire from '../../Fire'
import * as firebase from "@react-native-firebase/app"
import firestore from "@react-native-firebase/firestore"

import Icon from 'react-native-vector-icons/MaterialIcons';
import AltIcon from 'react-native-vector-icons/Ionicons';

import * as RootNavigation from '../../RootNavigation';                     //navigation without passing as arg

import { StackNavigationProp } from '@react-navigation/stack';                      //navigation as arg
import { RouteProp } from '@react-navigation/native';

import LottieView from 'lottie-react-native';
import { HexagonView } from 'react-native-shape-image-view';
import { COLORS } from '../../src/colors';
import Svg, { Circle, Line } from 'react-native-svg';

import RenderFindMatchScreen from './transitionScreens/RenderFindMatchScreen';
import RenderEndMatchScreen from './transitionScreens/renderEndMatchScreen';
import RenderContinueMatchScreen from './transitionScreens/renderContinueMatchScreen';
import { countReset } from 'console'

//const { VideoRenderMode } = Types
const FieldValue = firestore.FieldValue;

type RootStackParamList = {
    HomeScreen: undefined;
    videoVideo: { country: string };
    videoGroupVideo: { country: string, channelName: string, channelSize: number };
    videoGroupLobby: { country: string };
};

interface Props {
    navigation: StackNavigationProp<RootStackParamList, 'videoVideo'>;
    route: RouteProp<RootStackParamList, 'videoVideo'>;
}

/**
 * @property peerIds Array for storing connected peers
 * @property appId
 * @property channelName Channel Name for the current session
 * @property joinSucceed State variable for storing success
 */
interface State {
    appId: string,
    channelName: string,
    joinSucceed: boolean,
    peerIds: number[],
    leaving: boolean,
    no_users: number,
    vidMute: boolean,
    audMute: boolean,
    showGuest: boolean,
    guestAvatar: string,
    guestName: string,
    guestCountryCode: string,
    guestUid: string,
    showReview: boolean,
    showContinue: boolean,
    time: number,
    timeColor: string,
}

export default class App extends Component<Props, State> {
    _engine?: RtcEngine

    constructor(props) {
        super(props)
        this.state = {
            appId: "",              
            channelName: 'channel-x',
            joinSucceed: false,
            leaving: false,
            peerIds: [],
            no_users: 0,
            vidMute: false,
            audMute: false,
            showGuest: false,
            guestAvatar: '',
            guestName: '',
            guestCountryCode: '',
            guestUid: '',
            showReview: false,
            showContinue: false,
            time: 60,
            timeColor: 'white',
        }
        if (Platform.OS === 'android') {
            // Request required permissions from Android
            requestCameraAndAudioPermission().then(() => {
                console.log('requested!')
            })
        }
    }
    updateInterval;
    updateTime;
    componentDidMount() {
        this.init()
        this.updateInterval = setInterval(async () => {
            console.log("updated interval");
            this.checkLobby();
        }, 2000);

    }

    componentWillUnmount() {
        clearInterval(this.updateInterval);
        clearInterval(this.updateTime);
    }

    /**
     * @name init
     * @description Function to initialize the Rtc Engine, attach event listeners and actions
     */
    init = async () => {
        //console.log("here")
        const { appId } = this.state
        this._engine = await RtcEngine.create(appId)
        await this._engine.enableVideo();
        await this._engine.enableAudio();            // NEW@@@@@@@@@@@@@@@@@@@@@@@@@@
        
        this._engine.addListener('UserJoined', (uid, elapsed) => {
            console.log('UserJoined', uid, elapsed)
            // Get current peer IDs
            const { peerIds } = this.state
            // If new user
            if (peerIds.indexOf(uid) === -1) {
                this.setState({
                    // Add peer ID to state array
                    peerIds: [...peerIds, uid]
                })
            }
        })

        this._engine.addListener('UserOffline', (uid, reason) => {
            console.log('UserOffline', uid, reason)

            this.endCall();

            const { peerIds } = this.state
            this.setState({
                // Remove peer ID from state array
                peerIds: peerIds.filter(id => id !== uid)
            })
        })

        // If Local user joins RTC channel
        this._engine.addListener('JoinChannelSuccess', async (channel, uid, elapsed) => {
            console.log('JoinChannelSuccess', channel, uid, elapsed)
           
            const { peerIds } = this.state
            // Set state variable to true
            this.setState({
                joinSucceed: true
            })

            if (peerIds.indexOf(uid) === -1) {
                console.log("Add the local user", uid, elapsed)
                this.setState({
                    // Add peer ID to state array
                    peerIds: [...peerIds, uid]
                })
            }
            console.log("peerIds:", this.state.peerIds)
            setTimeout(() => {
                var continueRef = firestore().collection('VideoRooms').doc('Country').collection(this.props.route.params.country).doc(this.state.channelName);
                continueRef.get().then(async (acceptDoc) => {
                    if (acceptDoc.exists) {
                        if (acceptDoc.data().continue !== 0) {        //end call      NEED TO DELETE VIDEOROOMS 
                            await this.endCall();
                        }
                        else {                                         //CALL ACCEPTED
                            this.setState({
                                showGuest: false,
                            })
                        }

                    }
                })

            }, 7000);
        })
    }

    sortUids = (uid, guestUid) => {
        if (uid > guestUid) {
            return (uid + guestUid);
        }
        else {
            return (guestUid + uid);
        }
    }

    checkLobby = async () => {
        if (!this.state.joinSucceed) {                  //when user joins the channel no need to do this
            var docRef = firestore().collection('VideoRoomsCreation').doc('Country').collection(this.props.route.params.country).doc('Room 1');
            docRef.get().then(async (doc) => {
                if (doc.exists) {

                    //console.log("Document Data:", doc.data());                          //if a user is already looking for a room

                    if (doc.data().uid === Fire.uid) {
                        this.setState({                                                                 // NEED TO FIND A WAY TO UDPATE THIS COMPONENT FROM TIME TO TIME TO CHECK IF NEW USER JOINED
                            no_users: 1,
                        })
                        console.log("Waiting for user2")
                    }
                    else {
                        if (doc.data().members === 1) {
                            docRef.update({
                                members: 2,
                                uid: Fire.uid,
                            })                                         // 2nd user to join

                            var guestRef = firestore().collection('USERS').doc(doc.data().uid);
                            guestRef.get().then(async (guest) => {
                                if (guest.exists) {
                                    this.setState({
                                        leaving: true,
                                        guestAvatar: guest.data().avatar,
                                        guestCountryCode: guest.data().countryCode,
                                        guestName: guest.data().name,
                                        guestUid: guest.data().uid,
                                        showGuest: true,
                                    })
                                    var roomName = this.sortUids(Fire.uid, guest.data().uid);
                                    this.setState({
                                        channelName: roomName,
                                    })
                                }
                                else {
                                    console.log("Guest doesn't exist");
                                }
                            })
                            clearInterval(this.updateInterval);
                            await this._engine?.joinChannel(null, doc.data().channelName, null, 0);
                            this.setState({                                             //TIME OFFSET BECAUSE USERS DONT JOIN AT THE SAME TIME
                                time: 61,

                            })
                        }
                        else {                                                                          //1st user after creating the channel and the 2nd user joined
                            var guestRef = firestore().collection('USERS').doc(doc.data().uid);
                            guestRef.get().then(async (guest) => {
                                if (guest.exists) {
                                    this.setState({
                                        leaving: true,
                                        guestAvatar: guest.data().avatar,
                                        guestCountryCode: guest.data().countryCode,
                                        guestName: guest.data().name,
                                        guestUid: guest.data().uid,
                                        showGuest: true,
                                    })
                                    var roomName = this.sortUids(Fire.uid, guest.data().uid);
                                    var videoRoom = firestore().collection('VideoRooms').doc('Country').collection(this.props.route.params.country).doc(roomName);
                                    videoRoom.set({
                                        continue: 0,    // 0 -> CONTINUE  IF > 0 THAN END CALL
                                        deleter: Fire.uid,
                                    })

                                    this.setState({
                                        channelName: roomName,
                                    })
                                }
                                else {
                                    console.log("Guest doesn't exist");
                                }
                            })
                            clearInterval(this.updateInterval);
                            await this._engine?.joinChannel(null, doc.data().channelName, null, 0);
                            await docRef.update({
                                members: FieldValue.delete(),
                                uid: FieldValue.delete(),
                                channelName: FieldValue.delete(),
                            })
                            await docRef.delete();

                        }

                    }

                }
                else {
                    if (!this.state.leaving) {
                        console.log("No such document!");                // if there's not a corresponding user yet
                        var randomChannelName = (Math.floor(Math.random() * (1000000000))).toString();

                        docRef.set({
                            members: 1,
                            uid: Fire.uid,
                            channelName: randomChannelName,
                        })

                        this.setState({
                            no_users: 1,
                        })
                    }
                }
            })/*.catch(function (error) {
                //console.log("Error getting document:", error);
            })*/

        }
    }

    /**
     * @name startCall
     * @description Function to start the call
     */
    startCall = async () => {
        // Join Channel using null token and channel name   
        await this._engine?.joinChannel(null, this.state.channelName, null, 0)
    }

    /**
     * @name endCall
     * @description Function to end the call
     */
    endCall = async () => {
        await this._engine?.destroy();
        //this.setState({ joinSucceed: false , peerIds: [] });                

        //RootNavigation.goBack();
        //this.props.navigation.navigate('transitionVideo');                   
        clearInterval(this.updateTime);

        var endRef = firestore().collection('VideoRooms').doc('Country').collection(this.props.route.params.country).doc(this.state.channelName);   // NEED TO END CALL AFTER A USER LEAVES (LISTENER)
        console.log("deleting...")
        endRef.get().then((endDoc) => {
            if (endDoc.exists) {
                if (endDoc.data().deleter === Fire.uid) {
                    if (endDoc.exists) {
                        endRef.update({
                            continue: FieldValue.delete(),
                            deleter: FieldValue.delete(),
                        });
                        endRef.delete();
                    }
                    else {
                        console.log("Doc does not exist 2")
                    }
                }
            }
        })                                                                       

        this.setState({
            showReview: true,
        })
        setTimeout(async () => {
            await this.setState({
                showReview: false,
            });

            this.props.navigation.goBack();
            this.props.navigation.navigate('videoVideo', { country: this.props.route.params.country });

            /*var endRef = firestore().collection('VideoRooms').doc('Country').collection(this.props.route.params.country).doc(this.state.channelName);   // NEED TO END CALL AFTER A USER LEAVES (LISTENER)
            endRef.get().then((endDoc) => {
                if (endDoc.exists) {
                    if (endDoc.data().continue === 2) {              // STOP LOOKING FOR PEOPLE
                        this.props.navigation.goBack();
                        this.props.navigation.navigate('videoVideo', { country: this.props.route.params.country });
                    }
                    else {
                        this.props.navigation.goBack();
                    }

                    setTimeout(async () => {
                        console.log("deleting...")
                        if (endDoc.data().deleter === Fire.uid) {
                            if (endDoc.exists) {
                                endRef.update({
                                    continue: FieldValue.delete(),
                                    deleter: FieldValue.delete(),
                                });
                                endRef.delete();
                            }
                            else {
                                console.log("Doc does not exist 2")
                            }
                        }
                    }, 5000);
                }
                else {
                    console.log("Doc does not exist on Video.tsx")
                }
            }) */
        }, 5000);
    }

    toggleAudio = async () => {
        let mute = this.state.audMute;
        console.log('Audio Toggle', mute);
        await this._engine?.muteLocalAudioStream(!mute);
        this.setState({
            audMute: !mute,
        });
    }

    toggleVideo = async () => {
        this._engine.switchCamera();
        console.log('Video Toggle');
        /*
        let mute = this.state.vidMute;
        
        this.setState({
            vidMute: !mute,
        });
        this._engine.muteLocalVideoStream(!this.state.vidMute);
        this.setState({
            vidMute: !mute,
        });
        */
    }

    render() {
        return (
            <View style={styles.max}>
                <View style={{ flex: 1 }}>
                    {this._renderVideos()}
                </View>
            </View>
        )
    }

    _renderVideos = () => {
        const { joinSucceed, peerIds, showGuest, showReview, showContinue } = this.state
        var d_width = Dimensions.get('window').width;
        var d_height = Dimensions.get('window').height;
        return showGuest ? (
            <RenderFindMatchScreen guestName={this.state.guestName} guestAvatar={this.state.guestAvatar} guestCountryCode={this.state.guestCountryCode} channelName={this.state.channelName} />
        ) : showReview ? (
            <RenderEndMatchScreen guestName={this.state.guestName} guestAvatar={this.state.guestAvatar} guestCountryCode={this.state.guestCountryCode} guestUid={this.state.guestUid} />
        ) :
                (joinSucceed ? (showContinue ? (
                    <RenderContinueMatchScreen channelName={this.state.channelName} countryCode={this.props.route.params.country} />
                ) : (
                        <View style={styles.max}>
                            <View style={{ zIndex: 5, position: 'absolute', right: 5, top: 5 }}>
                                <Svg height='80' width='80'  >
                                    <Circle cx='40' cy='40' r='36' stroke={COLORS.primary} strokeWidth='4' fill={COLORS.secondary} />
                                    <View style={{ width: 80, height: 80, justifyContent: 'center', alignItems: 'center' }}>
                                        {(this.state.time < 100) && <Text style={{ fontSize: 30, color: this.state.timeColor }}> {this.state.time} </Text>}
                                        {(this.state.time >= 100) && <AltIcon name='infinite' size={30} color='white' />}
                                    </View>
                                </Svg>
                            </View>
                            {
                                this.state.peerIds.length === 4
                                    ?
                                    <View style={{ flex: 1 }}>
                                        <View style={{ flex: 1 / 2, flexDirection: 'row' }}>
                                            {/*<RtcRemoteView.SurfaceView style={{ flex: 1 / 2 }} uid={this.state.peerIds[0]} channelId={this.state.channelName} renderMode={VideoRenderMode.Hidden} zOrderMediaOverlay={true}/> */}
                                            <RtcLocalView.SurfaceView style={{ flex: 1 }} channelId={this.state.channelName} renderMode={VideoRenderMode.Hidden} />
                                            <RtcRemoteView.SurfaceView style={{ flex: 1 / 2 }} uid={this.state.peerIds[1]} channelId={this.state.channelName} renderMode={VideoRenderMode.Hidden} zOrderMediaOverlay={true} />
                                        </View>
                                        <View style={{ flex: 1 / 2, flexDirection: 'row' }}>
                                            <RtcRemoteView.SurfaceView style={{ flex: 1 / 2 }} uid={this.state.peerIds[2]} channelId={this.state.channelName} renderMode={VideoRenderMode.Hidden} zOrderMediaOverlay={true} />
                                            <RtcRemoteView.SurfaceView style={{ flex: 1 / 2 }} uid={this.state.peerIds[3]} channelId={this.state.channelName} renderMode={VideoRenderMode.Hidden} zOrderMediaOverlay={true} />
                                        </View>
                                    </View>
                                    : this.state.peerIds.length === 3
                                        ?
                                        <View style={{ flex: 1 }}>
                                            <View style={{ flex: 1 / 2, flexDirection: 'row' }}>
                                                {/*<RtcRemoteView.SurfaceView style={{ flex: 1 }} uid={this.state.peerIds[0]} channelId={this.state.channelName} renderMode={VideoRenderMode.Hidden} zOrderMediaOverlay={true} />*/}
                                                <RtcLocalView.SurfaceView style={{ flex: 1 }} channelId={this.state.channelName} renderMode={VideoRenderMode.Hidden} />
                                            </View>
                                            <View style={{ flex: 1 / 2, flexDirection: 'row' }}>
                                                <RtcRemoteView.SurfaceView style={{ flex: 1 / 2 }} uid={this.state.peerIds[1]} channelId={this.state.channelName} renderMode={VideoRenderMode.Hidden} zOrderMediaOverlay={true} />
                                                <RtcRemoteView.SurfaceView style={{ flex: 1 / 2 }} uid={this.state.peerIds[2]} channelId={this.state.channelName} renderMode={VideoRenderMode.Hidden} zOrderMediaOverlay={true} />
                                            </View>
                                        </View>
                                        : this.state.peerIds.length === 2
                                            ?
                                            <View style={{ flex: 1 }}>
                                                {/*<RtcRemoteView.SurfaceView style={{ flex: 1 }} uid={this.state.peerIds[0]} channelId={this.state.channelName} renderMode={VideoRenderMode.Hidden} zOrderMediaOverlay={true} />*/}
                                                <RtcLocalView.SurfaceView style={{ flex: 1 }} channelId={this.state.channelName} renderMode={VideoRenderMode.Adaptive}  />
                                                <RtcRemoteView.SurfaceView style={{ flex: 1 }} uid={this.state.peerIds[1]} channelId={this.state.channelName} renderMode={VideoRenderMode.Adaptive} zOrderMediaOverlay={true} />
                                            </View>
                                            : this.state.peerIds.length === 1
                                                ?

                                                <RtcLocalView.SurfaceView style={{ flex: 1 }} channelId={this.state.channelName} renderMode={VideoRenderMode.Hidden} />
                                                //<RtcRemoteView.SurfaceView style={{ flex: 1 }} uid={this.state.peerIds[0]} channelId={this.state.channelName} renderMode={VideoRenderMode.Hidden} zOrderMediaOverlay={true} />
                                                : <View />
                            }
                            <View style={styles.buttonContainer}>
                                <TouchableOpacity style={styles.iconStyle} onPress={() => this.toggleAudio()}>
                                    <Icon  /*backgroundColor="#0093E9"*/ name={this.state.audMute ? 'mic-off' : 'mic'} />
                                </TouchableOpacity>
                                <TouchableOpacity style={styles.iconStyle} onPress={() => this.endCall()} >
                                    <Icon name='call-end' /* size = {20} color='black' */ />
                                </TouchableOpacity>
                                <TouchableOpacity style={styles.iconStyle} onPress={() => this.toggleVideo()}>
                                    <Icon name='camera-alt' />
                                </TouchableOpacity>
                            </View>
                        </View>
                    )
                ) : /*null*/                                                                                    //WHILE LOOKING FOR ANOTHER USER
                    (
                        <View style={styles.container}>
                            <View style={{ flex: 3, justifyContent: 'flex-end', alignItems: 'center' }}>
                                {/*<Text style={{marginBottom: 50, fontSize: 30}}> Searching for users... </Text>*/}
                                <LottieView source={require('../../src/animations/loading_hourglass2.json')} autoPlay loop style={{ height: 400, width: 400 }} />
                            </View>
                            {/*<Text style={{ fontSize: 22 }}>Searching for users... </Text> 
                    <ActivityIndicator size='large'></ActivityIndicator> */}
                            <View style={{ flex: 1, justifyContent: 'flex-end', marginBottom: 50 }}>
                                <TouchableOpacity onPress={async () => {
                                    this.setState({
                                        leaving: true,
                                    })
                                    var leaveRef = firestore().collection('VideoRoomsCreation').doc('Country').collection(this.props.route.params.country).doc('Room 1');
                                    leaveRef.get().then(async (doc) => {
                                        if (doc.exists) {
                                            await leaveRef.update({
                                                members: FieldValue.delete(),
                                                uid: FieldValue.delete(),
                                                channelName: FieldValue.delete(),
                                            })
                                            await leaveRef.delete();
                                            console.log('Deleted Room');
                                        }
                                    })

                                    //RootNavigation.goBack();
                                    this.props.navigation.goBack();
                                }}>

                                    <Icon size={60} color='red' name='highlight-off' />

                                </TouchableOpacity>
                            </View>
                        </View>
                    )
                )
    }
    /*
    _renderRemoteVideos = () => {
        const { peerIds } = this.state
        return (
            <ScrollView
                style={styles.remoteContainer}
                contentContainerStyle={{ paddingHorizontal: 2.5 }}
                horizontal={true}>
                {peerIds.map((value, index, array) => {
                    return (
                        <RtcRemoteView.SurfaceView
                            style={styles.remote}
                            uid={value}
                            channelId={this.state.channelName}
                            renderMode={VideoRenderMode.Hidden}
                            zOrderMediaOverlay={true} />
                    )
                })}
            </ScrollView>
        )
    }
    */
}

**Comment by monkin77** [comment]
After I have checked it is indeed connecting the users, I can hear the audio, the image just doesn't appear

**Comment by LichKing-2234** [comment]
which version have you used before?

**Comment by LichKing-2234** [comment]
by the way, which version you used now, and could you pls provide our SDK log? you can refer to the `setLogFile` method.

**Comment by monkin77** [comment]
I was using v 3.0.1 -  rc.2. I went back to that version and it is working now. The version which was not working for me was the 3.0.1 -  rc.5

**Comment by LichKing-2234** [comment]
have you rerun the application(not reload js) after you upgrade to `3.0.1-rc.5`?

**Comment by monkin77** [comment]
Yes I'm pretty sure I did. The only thing different that I did was change the import since on the newer version you can't import Types to get the VideoRenderMode. So I imported VideoRenderMode directly as seen on my code above. should I have done anything else?

**Comment by LichKing-2234** [comment]
Have you tried our demo?

**Comment by monkin77** [comment]
I haven't, since I got it to work by going back to the previous version.

**Comment by LichKing-2234** [comment]
could you pls provide our SDK log? you can refer to the setLogFile method.

**Comment by LichKing-2234** [comment]
tested in the latest version, works fine.
