### ISSUE TITLE
iOS Compile error

### ISSUE THREAD

**Issue by bear1030** [AgoraIO-Community/react-native-agora#261]
Hello, thanks for your great package.

Android works fine for me.

But I experience some issues with ios.

1. Pod install error
When I did `pod install` it gave me this error. - `[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: react-native-agora`
So I added `use_frameworks!` to Podfile and it resolved pod install error.

2. Compile error
After pod install was successful I tried to build it and it gave me following errors.
`Swift Compiler Error
/myproject/node_modules/react-native-agora/ios/RCTAgora/React/PromiseCallback.swift:14:26: Use of undeclared type 'RCTPromiseResolveBlock'
/myproject/node_modules/react-native-agora/ios/RCTAgora/React/PromiseCallback.swift:15:25: Use of undeclared type 'RCTPromiseRejectBlock'
...
...
/myproject/node_modules/react-native-agora/ios/RCTAgora/React/RCTAgoraRtcChannelModule.swift:25:25: Method does not override any method from its superclass
...
...
/myproject/node_modules/react-native-agora/ios/RCTAgora/React/RCTAgoraRtcChannelModule.swift:13:33: Use of undeclared type 'RCTEventEmitter'
...
...
/myproject/node_modules/react-native-agora/ios/RCTAgora/React/RCTAgoraRtcChannelModule.swift:12:2: Only classes that inherit from NSObject can be declared @objc
...
...
/myproject/node_modules/react-native-agora/ios/RCTAgora/React/RCTAgoraRtcSurfaceViewManager.swift:14:19: Method does not override any method from its superclass
...
...
/myproject/node_modules/react-native-agora/ios/RCTAgora/React/RCTAgoraRtcSurfaceViewManager.swift:13:38: Use of undeclared type 'RCTViewManager'
/myproject/node_modules/react-native-agora/ios/RCTAgora/React/RCTAgoraRtcSurfaceViewManager.swift:30:17: Use of unresolved identifier 'bridge'
/myproject/node_modules/react-native-agora/ios/RCTAgora/React/RCTAgoraRtcSurfaceViewManager.swift:34:17: Use of unresolved identifier 'bridge'
/myproject/node_modules/react-native-agora/ios/RCTAgora/React/RCTAgoraRtcEngineModule.swift:63:13: Use of unresolved identifier 'sendEvent'
/myproject/node_modules/react-native-agora/ios/RCTAgora/React/RCTAgoraRtcEngineModule.swift:12:2: Only classes that inherit from NSObject can be declared @objc`
![Screenshot_162](https://user-images.githubusercontent.com/15319821/92081670-02076c00-edf6-11ea-9af9-ba4980557428.png)

Any solution for this swift compiler error?

Thank you!

**Comment by LichKing-2234** [comment]
could you share your `react-native info`?

**Comment by bear1030** [comment]
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 4.10 GB / 12.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by LichKing-2234** [comment]
you should add an empty swift file to let the project support swift.

**Comment by bear1030** [comment]
Yes, I already added that and also the bridging header file.

**Comment by LichKing-2234** [comment]
RN 0.60+  should not run `react-native link`, seem like you run it.

**Comment by bear1030** [comment]
No, I don't. I don't run `react-native link`

**Comment by LichKing-2234** [comment]
could you share your podfile?

**Comment by bear1030** [comment]
`platform :ios, '9.0'
use_frameworks!
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

pre_install do |installer|
Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

target 'myproject' do
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'

  target 'myprojectTests' do
    inherit! :search_paths
  end

  use_native_modules!
end

target 'myproject-tvOS' do

  target 'myproject-tvOSTests' do
    inherit! :search_paths
  end

end
`

**Comment by bear1030** [comment]
@LichKing-2234 - Any idea?

**Comment by bear1030** [comment]
@LichKing-2234 

I reviewed the embeded react-native-agora project in the xcode. And Objective-C Bridging Header was blank. Is that correct?
![Screenshot_163](https://user-images.githubusercontent.com/15319821/92130964-f341a900-ee37-11ea-88ff-b2244236a3da.png)

**Comment by bear1030** [comment]
Adding `${SRCROOT}/../../node_modules/react-native-agora/ios/RCTAgora/React/RCTAgora-Bridging-Header.h` to Objective-C Bridging Header solved my issue.

I hope you fix this issue in the next release.

Thank you!

**Comment by LichKing-2234** [comment]
which version of cocoapods do you use? I think `use_frameworks!` should not be added.

**Comment by LichKing-2234** [comment]
> Adding `${SRCROOT}/../../node_modules/react-native-agora/ios/RCTAgora/React/RCTAgora-Bridging-Header.h` to Objective-C Bridging Header solved my issue.
> 
> I hope you fix this issue in the next release.
> 
> Thank you!

the target generate by cocoapods, it should not be modified.

**Comment by bear1030** [comment]
> When I did pod install it gave me this error. - [!] Pods written in Swift can only be integrated as frameworks; add use_frameworks! to your Podfile or target to opt into using it. The Swift Pod being used is: react-native-agora
So I added use_frameworks! to Podfile and it resolved pod install error.

I had to add use_frameworks! to fix the issue while doing `pod install`

**Comment by LichKing-2234** [comment]
in the old version of cocoapods, install a swift module, must add `use_frameworks!`, it has been fixed in the new version. so I want to know which version you have used.

**Comment by bear1030** [comment]
My cocoapods version is 1.4.0

**Comment by LichKing-2234** [comment]
it is too old, you can upgrade it and try again.

**Comment by bear1030** [comment]
@LichKing-2234 Yes, upgrading cocoapods version worked for me. Thank you!
