### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNativeAgora.default.on')

### ISSUE THREAD

**Issue by timi-codes** [AgoraIO-Community/react-native-agora#263]
TypeError: undefined is not an object (evaluating '_reactNativeAgora.default.on')
It has really been a frustrating experience while trying to use this library. I've been moving from one error to another throughout this week. Now I'm trying to even use a legacy version and yet I'm still getting this error.

**Comment by LichKing-2234** [comment]
duplicate as https://github.com/AgoraIO-Community/Agora-RN-Quickstart/issues/57

**Comment by ssiju** [comment]
I got same issue
