### ISSUE TITLE
Issue accessing log file

### ISSUE THREAD

**Issue by alicema15** [AgoraIO-Community/react-native-agora#265]
Hi team, I'm using `setLogFile()` to output an agora sdk log file on an iOS device simulator. However, when I try to access the default file path `Sandbox/Library/Caches/agorasdk.log` I'm unable to find anything written.

I'm accessing the file through the following path:
`~/Library/Developer/CoreSimulator/Devices/[DeviceID]/data/Containers/Data/Application/[AppID]/`

Please advise, thank you!

**Comment by LichKing-2234** [comment]
on iOS device simulator, the `Sandbox` direct to `~/Library/Developer/CoreSimulator/Devices/[DeviceID]/data/Containers/Data/Application/[AppID]/`.

**Comment by LichKing-2234** [comment]
if you want to use the default log file, you should not call the `setLogFile` method.

**Comment by alicema15** [comment]
Thank you - found it. Could you please also point me to how to access the log files for an app deployed on device? For context, we have some users using our iOS app through Testflight that are reporting audio cutting out issues and we'd like to fetch the log files to review.

**Comment by LichKing-2234** [comment]
you can use `react-native-fs` to access the log file.
