### ISSUE TITLE
Support for Agora Native v3.2.1

### ISSUE THREAD

**Issue by alicema15** [AgoraIO-Community/react-native-agora#268]
Hi team, in the latest iOS 14 users receive a permissions popup requesting access to local network devices, and I'd like to turn this off. I believe this is supported in the latest Agora Native SDK update to v3.2.1 by temporarily disabling the local network device request. Documentation is here: https://docs.agora.io/en/faq/local_network_privacy

When will v3.2.1 be supported in the react-native-agora package?

Thanks
Alice

**Comment by LichKing-2234** [comment]
yes, I will support 3.1.2 next version.

**Comment by alicema15** [comment]
Thank you!

**Comment by LichKing-2234** [comment]
3.1.2 published
