### ISSUE TITLE
Defocus/focus in video call

### ISSUE THREAD

**Issue by Sach-SPF** [AgoraIO-Community/react-native-agora#269]
Hey there, 

I'm facing an autofocus (defocus/focus) issue with the rear camera in a video call, scenarios is when I move and stop then the camera tries to focus/defocus irrespective of the distance between the object and camera, can someone help me to disable this

Thanks
Sachin

**Comment by LichKing-2234** [comment]
is system camera work?

**Comment by LichKing-2234** [comment]
you can try this function. but the default param is false.
https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/react_native/classes/rtcengine.html#setcameraautofocusfacemodeenabled

**Comment by Sach-SPF** [comment]
Yes, the Device camera works, I have a focus/defocus problem with Agora video calling with rear camera, I'll check out that link

Thanks

**Comment by Sach-SPF** [comment]
Update +,

I figured out the reason for defocus/focus, if i set below configuration only then its happening and that too only on iOS
 await this._engine?.setVideoEncoderConfiguration({
      dimensions: { width: 1280, height: 720 },
      frameRate: 30,
       bitrate: 1710,
    });

**Comment by LichKing-2234** [comment]
sorry for the late reply, is this problem remain?

**Comment by LichKing-2234** [comment]
you can reopen this issue if it still exists.
