### ISSUE TITLE
Online Pk mode

### ISSUE THREAD

**Issue by varunsdcet** [AgoraIO-Community/react-native-agora#270]
I want to integrate Pkmode in react native.what should i do

**Comment by csmtcy** [comment]
I also want to implement this any clue on the pk mode integration?

**Comment by LichKing-2234** [comment]
you can refer to these docs.
https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/react_native/classes/rtcengine.html#startchannelmediarelay
https://docs.agora.io/en/Interactive%20Broadcast/media_relay_android?platform=Android

**Comment by varunsdcet** [comment]
@csmtcy  have you find any sample

**Comment by varunsdcet** [comment]
@LichKing-2234  We trying to implement 
 const channelMediaConfig = RtcEngine.ChannelMediaConfiguration();
        // Set the source channel information.
        channelMediaConfig.setSrcChannelInfo({
         channelName: GLOBAL.bookingid,
         uid: 0,

        })
        // Set the destination channel information. You can set a maximum of four destination channels.
        channelMediaConfig.addDestChannelInfo({
         channelName: "akash",
         uid: 1,

        })

but they give ChannelMediaConfiguration is undefined and let me know how its work ,And i want to know it show automatically COhost screen or we have to do extra stuff

**Comment by LichKing-2234** [comment]
@varunsdcet sorry for the late reply, have you contact sales to enable this function?

**Comment by varunsdcet** [comment]
@LichKing-2234  yes we enable it RtcEngine.ChannelMediaConfiguration() show undefined

**Comment by LichKing-2234** [comment]
@varunsdcet which version you used

**Comment by varunsdcet** [comment]
"react-native-agora": "^2.9.1-alpha.3",

**Comment by varunsdcet** [comment]
@LichKing-2234  ChannelMediaConfiguration give error How we intialize this Please help

**Comment by LichKing-2234** [comment]
have you got the error code? by the way please provide our SDK log.

**Comment by varunsdcet** [comment]
@LichKing-2234 ![IMG_20201019_094138](https://user-images.githubusercontent.com/33832368/96400896-98012580-11ef-11eb-80d6-67c4277f3b13.jpg)

**Comment by varunsdcet** [comment]
@LichKing-2234   I encounter this issue.Please help

**Comment by LichKing-2234** [comment]
in the 2.x version, `ChannelMediaConfiguration` is just an interface, so you should not call the constructor.
use it like
```
const config: ChannelMediaConfiguration = {
...
}
```

**Comment by varunsdcet** [comment]
@LichKing-2234 
const config : ChannelMediaConfiguration = {
}
when we use it give error unresolved or variable type  ChannelMediaConfiguration

**Comment by LichKing-2234** [comment]
@varunsdcet have you import `ChannelMediaConfiguration`?

**Comment by LichKing-2234** [comment]
by the way, which IDE you used, I think the IDE will suggest the solution for you.

**Comment by varunsdcet** [comment]
@LichKing-2234  const {
    FPS30,
    AudioProfileDefault,
    AudioScenarioDefault,
    Host,
    Adaptative,
    ChannelMediaConfiguration,
} = Agora
is this is ok?

**Comment by LichKing-2234** [comment]
you can find this in react-native-agora/types.d.ts
```
/**
 * ChannelMediaInfo
 * @property channelName: string
 * @property token: string
 * @property uid: number
 */
export interface ChannelMediaInfo {
    channelName: string;
    token?: string;
    uid?: number;
}
/**
 * ChannelMediaConfiguration
 * @property src: {
 *    @member channelName,
 *    @member token,
 *    @member uid,
 * }
 * @property channels: {@link Array<ChannelMediaInfo>}
 */
export interface ChannelMediaConfiguration {
    src?: {
        channelName: string;
        token?: string;
        uid?: number;
    };
    channels: Array<ChannelMediaInfo>;
}
```
they both are interface, no method call `setSrcChannelInfo`

**Comment by varunsdcet** [comment]
@LichKing-2234     

 const config: ChannelMediaConfiguration = {
                 src:{
                             channelName: GLOBAL.bookingid,
                             uid: 0,
                 }
}
How we set source and destination src info

**Comment by LichKing-2234** [comment]
you can refer to this [doc](https://docs.agora.io/en/Audio%20Broadcast/media_relay_android?platform=Android) to know how to start media relay.

**Comment by varunsdcet** [comment]
@LichKing-2234 
![IMG_8006](https://user-images.githubusercontent.com/33832368/96428034-ebd63380-121c-11eb-8322-d0ae48d97cdf.jpg)

@LichKing-2234  I am getting error while implementing start channel media relay is i am doing right or wrong please suggest

      var array = [ChannelMediaInfo]
      this.timeoutCheck = setTimeout(() => {


        const configs: ChannelMediaInfo = {

                        channelName: "42-2020-10-19-14-50-54",
                        uid: 42,

          }

array.push(configs)

        const config: ChannelMediaConfiguration = {
            src:{
                        channelName: "42-2020-10-19-14-50-54",
                        uid: 42,
            },
            channels :array
          }

          RtcEngine.startChannelMediaRelay(config).then(result =>{
             alert(JSON.stringify(result))
           })

**Comment by varunsdcet** [comment]
@LichKing-2234  i update my sdk     "react-native-agora": "^3.1.3",
  const ch = new ChannelMediaRelayConfiguration(
                {
                channelName: "12",
                    uid: 0,
            },
             {
                channelName: "42-2020-10-19-15-55-56",
                    uid: 42,
            }
            )


this._engine.startChannelMediaRelay(ch)

but nothing happen on console 
Possible Unhandled Promise Rejection (id: 0):
Error: invalid argument
promiseMethodWrapper@http://192.168.29.77:8081/index.bundle?platform=android&dev=true&minify=false:2242:45
_callMethod@http://192.168.29.77:8081/index.bundle?platform=android&dev=true&minify=false:120206:47
startChannelMediaRelay@http://192.168.29.77:8081/index.bundle?platform=android&dev=true&minify=false:119868:37
http://192.168.29.77:8081/index.bundle?platform=android&dev=true&minify=false:119109:48
_callTimer@http://192.168.29.77:8081/index.bundle?platform=android&dev=true&minify=false:30592:17
callTimers@http://192.168.29.77:8081/index.bundle?platform=android&dev=true&minify=false:30800:19
__callFunction@http://192.168.29.77:8081/index.bundle?platform=android&dev=true&minify=false:2765:36
http://192.168.29.77:8081/index.bundle?platform=android&dev=true&minify=false:2497:31
__guard@http://192.168.29.77:8081/index.bundle?platform=android&dev=true&minify=false:2719:15
callFunctionReturnFlushedQueue@http://192.168.29.77:8081/index.bundle?platform=android&dev=true&minify=false:2496:21
callFunctionReturnFlushedQueue@[native code]

**Comment by LichKing-2234** [comment]
https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/react_native/classes/channelmediarelayconfiguration.html#srcinfo
https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/react_native/classes/channelmediarelayconfiguration.html#destinfos

**Comment by LichKing-2234** [comment]
the uid in srcinfo must be 0.

**Comment by LichKing-2234** [comment]
> @LichKing-2234
> ![IMG_8006](https://user-images.githubusercontent.com/33832368/96428034-ebd63380-121c-11eb-8322-d0ae48d97cdf.jpg)
> 
> @LichKing-2234 I am getting error while implementing start channel media relay is i am doing right or wrong please suggest
> 
> ```
>   var array = [ChannelMediaInfo]
>   this.timeoutCheck = setTimeout(() => {
> 
> 
>     const configs: ChannelMediaInfo = {
> 
>                     channelName: "42-2020-10-19-14-50-54",
>                     uid: 42,
> 
>       }
> ```
> 
> array.push(configs)
> 
> ```
>     const config: ChannelMediaConfiguration = {
>         src:{
>                     channelName: "42-2020-10-19-14-50-54",
>                     uid: 42,
>         },
>         channels :array
>       }
> 
>       RtcEngine.startChannelMediaRelay(config).then(result =>{
>          alert(JSON.stringify(result))
>        })
> ```
`var array = [ChannelMediaInfo]` you can init array like this.
`var array:ChannelMediaInfo[] = []` is correct.

**Comment by varunsdcet** [comment]
@LichKing-2234 

After setting nothing happen null response coming
  const ch = new ChannelMediaRelayConfiguration(
                {
                channelName: "12",
                    uid: 0,
            },
             [{
                channelName: "42-2020-10-19-16-54-12",
                    uid: 42,
            }]
            )

            this._engine.startChannelMediaRelay(ch).then(result =>{
                    alert(JSON.stringify(result))
                })

**Comment by LichKing-2234** [comment]
this works for me.
`this._engine.startChannelMediaRelay(new ChannelMediaRelayConfiguration(new ChannelMediaInfo(0, {}), [new ChannelMediaInfo(0, {channelName: '123'})]))`

**Comment by varunsdcet** [comment]
@LichKing-2234  you are passing uid 0 in both

**Comment by LichKing-2234** [comment]
yes, `this._engine.startChannelMediaRelay(new ChannelMediaRelayConfiguration(new ChannelMediaInfo(0, {}), [new ChannelMediaInfo(123, {channelName: '123'})]))` also works.

**Comment by varunsdcet** [comment]
@LichKing-2234  i am also using  but nothing happen
import RtcEngine, {RtcLocalView, RtcRemoteView, VideoRenderMode,ChannelMediaRelayConfiguration,ChannelMediaInfo} from 'react-native-agora'

this._engine.startChannelMediaRelay(new ChannelMediaRelayConfiguration(new ChannelMediaInfo(0, {}), [new ChannelMediaInfo(42, {channelName: '42-2020-10-19-17-16-34'})]))

**Comment by LichKing-2234** [comment]
`this._engine.startChannelMediaRelay(new ChannelMediaRelayConfiguration(new ChannelMediaInfo(0, {}), [new ChannelMediaInfo(42, {channelName: '42-2020-10-19-17-16-34'})]))`

the uid 42 is the uid of media relay.

**Comment by varunsdcet** [comment]
@LichKing-2234  i am getting response 1 and after 3 and nothing happend . please help me out to resolve this issue of mine

**Comment by LichKing-2234** [comment]
have you made another device join the channel `42-2020-10-19-17-16-34`?

**Comment by varunsdcet** [comment]
@LichKing-2234  yes

**Comment by LichKing-2234** [comment]
have you set the client role to broadcaster?

**Comment by varunsdcet** [comment]
@LichKing-2234  yes

**Comment by LichKing-2234** [comment]
> @LichKing-2234 i am getting response 1 and after 3 and nothing happend . please help me out to resolve this issue of mine

state 3 means some error here. you can check the code.
https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/react_native/globals.html#mediarelaystatecallback

**Comment by varunsdcet** [comment]
@LichKing-2234  i am getting response 1 and 2

**Comment by LichKing-2234** [comment]
@varunsdcet the code from 1 to 2?

**Comment by varunsdcet** [comment]
@LichKing-2234  yes first time it give 1 after fraction of section they give response 2

**Comment by LichKing-2234** [comment]
@varunsdcet could you pls provide our SDK log? you can refer to [`setLogFile`](https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/react_native/classes/rtcengine.html#setlogfile)

**Comment by varunsdcet** [comment]
@LichKing-2234 
we get 1. Connecting = 1(The SDK tries to relay the media stream to the destination channel)
2. Running = 2(The SDK successfully relays the media stream to the destination channel)

@LichKing-2234  how we call and where we call 
<RtcRemoteView.SurfaceView
    uid={uid}
    renderMode={VideoRenderMode.Hidden} />

**Comment by LichKing-2234** [comment]
@varunsdcet so the problem about media relay has been resolved?

**Comment by LichKing-2234** [comment]
> @LichKing-2234
> we get 1. Connecting = 1(The SDK tries to relay the media stream to the destination channel)
> 2. Running = 2(The SDK successfully relays the media stream to the destination channel)
> 
> @LichKing-2234 how we call and where we call
> <RtcRemoteView.SurfaceView
> uid={uid}
> renderMode={VideoRenderMode.Hidden} />

you should call `setState` after the `UserJoined` event trigger, and add the component to your `render` function.

**Comment by varunsdcet** [comment]
@LichKing-2234  agora reply 
if we get this i
we get 1. Connecting = 1(The SDK tries to relay the media stream to the destination channel)
2. Running = 2(The SDK successfully relays the media stream to the destination channel)

its means channel is sucessfull for preparing  for channel media relay . its is ok ? or we perform another thing

**Comment by varunsdcet** [comment]
@LichKing-2234  according to document this
https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/react_native/enums/channelmediarelaystate.html#running
But our on userjoined method not called

**Comment by varunsdcet** [comment]
@LichKing-2234  if we pass same channel name on destination channel then user joined method call
this._engine.startChannelMediaRelay(new ChannelMediaRelayConfiguration(new ChannelMediaInfo(0, {channelName: '1'}), [new ChannelMediaInfo(42, {channelName: '1'})]))

I am doing code on one side is their any need code of another side

**Comment by LichKing-2234** [comment]
@varunsdcet the second ChannelMediaInfo `new ChannelMediaInfo(42, {channelName: '42-2020-10-21-13-44-49'})` means publishing to this channel, you should join the channel `42-2020-10-21-13-44-49` and listen `UserJoined`.

**Comment by varunsdcet** [comment]
@LichKing-2234  i faced a problem
1- First time user start channel media relay with another channel its work fine when another chanel leave pk its work fine but 
problem whose user which is already on Pk mode want to establish again channel media relay another with another this will not suceed

**Comment by LichKing-2234** [comment]
you can only keep one media relay at once time

**Comment by varunsdcet** [comment]
@LichKing-2234  thanks its working...
