### ISSUE TITLE
tsconfig issue in latest 3.1.2, Couldn't able to run the app after installing the package

### ISSUE THREAD

**Issue by EarshadAhamed** [AgoraIO-Community/react-native-agora#274]
![image](https://user-images.githubusercontent.com/71436815/94515507-4ba27580-0241-11eb-835e-fc9fce8ac7ea.png)
import React, {Component} from 'react';
import {
  View,
  StyleSheet,
  NativeModules,
  ScrollView,
  Text,
  Dimensions,
  TouchableOpacity,
  Alert,
  AsyncStorage
} from 'react-native';
import {RtcEngine, AgoraView } from 'react-native-agora';
import Icon from 'react-native-vector-icons/MaterialIcons';
import moment from 'react-moment';
import Moment from 'moment';
import 'moment-timezone';

const {Agora} = NativeModules; //Define Agora object as a native module

const {FPS30, AudioProfileDefault, AudioScenarioDefault, Adaptative} = Agora; //Set defaults for Stream

import { BASE_URL, APICalls, VIDEOCALLMETRICS, AGORA_BASE_URL,START_RECORDING, STOP_RECORDING, GET_RESOURCE_ID} from '../Helper'

class Video extends Component {
  constructor(props) {
    super(props);
    let interval;
    this.getKey()
    this.state = {

      patientKey:"",
      appointmentKey:"",
      resourceID:"",

      peerIds: [], 
      uid: Math.floor(Math.random() * 100), //Generate a UID for local user
      appid: 'cb3ef8dc3b2e48b994fb3e826fb5ffcc', //Enter the App ID generated from the Agora Website
      channelName: "webtesttzz", //Channel Name for the current session
      vidMute: false, //State variable for Video Mute
      audMute: false, //State variable for Audio Mute
      joinSucceed: false, //State variable for storing success
      callStartTime: Date(),
      callEndTime: Date(),
      UserJoinedTime: Date(),
      userMuteStartTime: Date(),
      userMuteEndTime: Date(),
      userMuteTIme: Date(),
      userJoinedFlag:false,
      second:0,

      UserJoinedID:'',

    };

    

    const config = {
      //Setting config of the app
      appid: this.state.appid, //App ID
      channelProfile: 0, 
      videoEncoderConfig: {
        
        width: 720,
        height: 1080,
        bitrate: 0.4,
        frameRate: FPS30,
        orientationMode: Adaptative,
        // degradationPrefer: Balanced,
      
      },
      audioProfile: AudioProfileDefault,
      audioScenario: AudioScenarioDefault,
    };
    RtcEngine.init(config); //Initialize the RTC engine
  }

  async getKey() {
    try {
      const patientKey = await AsyncStorage.getItem('patient_key');
      const appointmentkey = await AsyncStorage.getItem('appointment_key');
      console.log("Patent KEY" + patientKey + "   " + appointmentkey);
    
  
    this.setState({patientKey: patientKey, appointmentKey: appointmentkey});
  
        
    } catch (error) {
      console.log("Error retrieving data" + error);
    }
  }

  getAgoraResourceID()
  {
  console.log("\nAPI---------->",AGORA_BASE_URL + GET_RESOURCE_ID);

  // let PastartTime = moment(patient_start_time).format("hh:mm:ss")
  var pa = {
    cname: "webtesttzz",
    uid: this.state.uid,
    clientRequest: {
      resourceExpiredHour: 24
    }
  }
  var JsonData = JSON.stringify(pa)

  console.log("\nParameter---------->",JsonData);

      APICalls(AGORA_BASE_URL + GET_RESOURCE_ID, 'POST',JsonData)
      .then(response => {

          this.setState({ isLoading: false });
          this.setState({ loaderVisible: false });
          let JSONObject = JSON.stringify(response)
          console.log("\n\n ---->",JSONObject)

          console.log("\n\n AGORA GET RESOURCE ID ---->",response)

          if (response.status == 'success') {

              console.log("------>",response.data);
          }
          else
          {

          }

      })

  }

  sendMetrics(patient_start_time,patient_end_time,doctor_start_time,doctor_end_time,patient_mute_time,doctor_mute_time)
    {
    console.log("\nAPI---------->",BASE_URL + VIDEOCALLMETRICS);

    // let PastartTime = moment(patient_start_time).format("hh:mm:ss")
       
    var pa = {
        patient_n_key: this.state.patientKey,
        appointment_n_key: this.state.appointmentKey,
        room_id: this.state.appointmentKey,
        patient_start_time:Moment(patient_start_time).format("hh:mm:ss"),
        patient_end_time:Moment(patient_end_time).format("hh:mm:ss"),
        doctor_start_time:Moment(doctor_start_time).format("hh:mm:ss"),
        doctor_end_time:Moment(doctor_end_time).format("hh:mm:ss"),
        patient_mute_time:patient_mute_time,
        doctor_mute_time: doctor_mute_time
        
    }

    var JsonData = JSON.stringify(pa)

    console.log("\nParameter---------->",JsonData);

        APICalls(BASE_URL + VIDEOCALLMETRICS, 'POST',JsonData)
        .then(response => {

            this.setState({ isLoading: false });
            this.setState({ loaderVisible: false });
            let JSONObject = JSON.stringify(response)
            console.log("\n\n availablity Response ---->",JSONObject)

            if (response.status == 'success') {

                

                console.log("------>",response.data);

                

            }
          
            else
            {

            }

        })

    }

  
   componentDidMount() {
    console.log('\n\n\nStart Time:',this.state.callStartTime, '\n\n End Time:',this.state.callEndTime)
    this.getAgoraResourceID()
    
    RtcEngine.connectionStateChanged((ConnectionStateType,ConnectionChangedReason) =>{
      console.log("Connect change reason",ConnectionChangedReason, "Connection type", ConnectionStateType)

    })

    

    RtcEngine.on('userJoined', data => {
      const {peerIds} = this.state; //Get currrent peer IDs
      console.log('\n\nUser joined', data)
      
      this.setState({UserJoinedTime:Date(),userJoinedFlag:true,UserJoinedID:data.uid}, () => {
        this.getAgoraResourceID()
    })
      
      this.sendMetrics(null,null,Date(),null,null,null)
      if (peerIds.indexOf(data.uid) === -1) {
        //If new user has joined
        this.setState({
          peerIds: [...peerIds, data.uid], //add peer ID to state array
        });
      }
      console.log("Video:----> ",data)
    });
    RtcEngine.on('userOffline', data => {
      //If user leaves
      this.setState({
        peerIds: this.state.peerIds.filter(uid => uid !== data.uid), //remove peer ID from state array
      });
      this.sendMetrics(null,null,null,Date,null,null)
    });

    RtcEngine.on('joinChannelSuccess', data => {
      //If Local user joins RTC channel
      console.log('\njoinChannelSuccess:', data)
      RtcEngine.startPreview(); //Start RTC preview
      this.setState({
        joinSucceed: true, //Set state variable to true
      });
      this.sendMetrics(Date(),null,null,null,null,null)
    });
    RtcEngine.joinChannel(this.state.channelName, this.state.uid); //Join Channel
    RtcEngine.enableAudio(); //Enable the audio
  }
  
  toggleAudio() {
    let mute = this.state.audMute;
    console.log('Audio toggle', mute);
    RtcEngine.muteLocalAudioStream(!mute);
    this.setState({
      audMute: !mute,
    });
    if(!mute)
    {
      this.onStartTimer
    }
    else 
    {
      this.sendMetrics(null,null,null,null,this.state.second,null)
      this.onPauseTimer
    }
  }
  
  onStartTimer = () => {
    this._interval = setInterval(() => {
     this.setState({
       second: this.state.second + 1,
    })
 }, 1000);
}

onPauseTimer = () => {
  clearInterval(this._interval);
}

  
  toggleVideo() {
    let mute = this.state.vidMute;
    console.log('Video toggle', mute);
    this.setState({
      vidMute: !mute,
    });
    RtcEngine.muteLocalVideoStream(!this.state.vidMute);
    // RtcEngine.switchCamera();
  }
  
  endCall() {
      //  this.setState({callEndTime:Date()},()=>{
      //   var dif = moment.utc(moment(this.state.callStartTime,"E MMM d yyyy HH:mm:ss z").diff(moment(this.state.callEndTime,"E MMM d yyyy HH:mm:ss z"))).format("HH:mm:ss")
      //    console.log('\n\n\nStart Time:',this.state.callStartTime, '\n\n End Time:',this.state.callEndTime, '\n Difference:',dif)

         
      //   })
      console.log('Rtc Length---->',RtcEngine.length) 
    RtcEngine.destroy();
    this.sendMetrics(null,Date(),null,null,null,null)
    this.props.navigation.goBack();
  }

  
  peerClick(data) {
    let peerIdToSwap = this.state.peerIds.indexOf(data);
    this.setState(prevState => {
      let currentPeers = [...prevState.peerIds];
      let temp = currentPeers[peerIdToSwap];
      currentPeers[peerIdToSwap] = currentPeers[0];
      currentPeers[0] = temp;
      return {peerIds: currentPeers};
    });
  }
  /**
   * return video call view
   */
  videoView() {
    let flag = this.state.userJoinedFlag
    return (
      
      <View style={styles.full}>
        {this.state.userJoinedFlag == true ? 
        (
        <View style={{width:'100%',height:'100%'}}>
          {this.state.peerIds.length > 1 ? (
          <View style={styles.full}>
            <View style={{height: (dimensions.height * 3) / 4 - 50}}>
              <AgoraView
                style={styles.full}
                remoteUid={this.state.peerIds[0]}
                mode={1}
                key={this.state.peerIds[0]}
              />
            </View>
            <View style={{height: dimensions.height / 4}}>
              <ScrollView
                horizontal={true}
                decelerationRate={0}
                snapToInterval={dimensions.width / 2}
                snapToAlignment={'center'}
                style={{
                  width: dimensions.width,
                  height: dimensions.height / 4,
                }}>
                {this.state.peerIds.slice(1).map(data => (
                  <TouchableOpacity
                    style={{
                      width: dimensions.width / 2,
                      height: dimensions.height / 4,
                    }}
                    onPress={() => this.peerClick(data)}
                    key={data}>
                    <AgoraView
                      style={{
                        width: dimensions.width / 2,
                        height: dimensions.height / 4,
                      }}
                      remoteUid={data}
                      mode={1}
                      key={data}
                    />
                  </TouchableOpacity>
                ))}
              </ScrollView>
            </View>
          </View>
        ) : this.state.peerIds.length > 0 ? (
          <View style={{height: dimensions.height - 50}}>
            <AgoraView
              style={styles.full}
              remoteUid={this.state.peerIds[0]}
              mode={1}
            />
          </View>
        ) : (
          <View style={{width:'100%',height:'100%',alignItems:'center',justifyContent:'center'}}><Text>No users connected</Text></View>
          
        )}
        {!this.state.vidMute ? ( //view for local video
          <AgoraView
            style={styles.localVideoStyle}
            zOrderMediaOverlay={true}
            showLocalVideo={true}
            mode={1}
          />
        ) : (
          <View />
        )}
        <View style={styles.buttonBar}>
          <Icon.Button
            style={styles.iconStyle}
            backgroundColor="#0093E9"
            name={this.state.audMute ? 'mic-off' : 'mic'}
            onPress={() => this.toggleAudio()}
          />
          <Icon.Button
            style={styles.iconStyle}
            backgroundColor="#0093E9"
            name="call-end"
            onPress={() => this.endCall()}
          />
          <Icon.Button
            style={styles.iconStyle}
            backgroundColor="#0093E9"
            name={this.state.vidMute ? 'videocam-off' : 'videocam'}
            onPress={() => this.toggleVideo()}
          />
        </View>
        </View>
        ):
        (<View><View style={{backgroundColor:'#515151', width:'100%',height:'100%',alignItems:'center',justifyContent:'center'}}>
        <Text style={{color:'#fff',fontFamily:'Poppins-Light',fontSize:16}}>Please wait our care team member will connect</Text>
      </View></View>)
      }
        
    
  
      </View>
        
    );
  }

  videWaitingView() {
    return (
      <View style={{backgroundColor:'#515151', width:'100%',height:'100%',alignItems:'center',justifyContent:'center'}}>
        <Text style={{color:'#fff',fontFamily:'Poppins-Light',fontSize:16}}>Please wait our care team member will connect</Text>
      </View>
    );
  }
  render() {
   
      return this.videoView()
    
  }
}

let dimensions = {
  //get dimensions of the device to use in view styles
  width: Dimensions.get('window').width,
  height: Dimensions.get('window').height,
};

const styles = StyleSheet.create({
  buttonBar: {
    height: 50,
    backgroundColor: '#0093E9',
    display: 'flex',
    width: '100%',
    position: 'absolute',
    bottom: 0,
    left: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
  },
  localVideoStyle: {
    width: 140,
    height: 160,
    position: 'absolute',
    top: 5,
    right: 5,
    zIndex: 100,
  },
  iconStyle: {
    fontSize: 34,
    paddingTop: 15,
    paddingLeft: 40,
    paddingRight: 40,
    paddingBottom: 15,
    borderRadius: 0,
  },
  full: {
    flex: 1,
  },
});

export default Video;

**Comment by LichKing-2234** [comment]
your code is for v2.x, if you want to migrate to v3.x, pls refer to our quickstart
