### ISSUE TITLE
RN Debug crashes the app in latest version

### ISSUE THREAD

**Issue by mladenp** [AgoraIO-Community/react-native-agora#275]
After updating to agora 3.1.2 debug mode crashes the app with error in console:
`Cannot form weak reference to instance (0x6000003a9950) of class RCTAgoraRtcEngineModule.`

**Comment by LichKing-2234** [comment]
how to recurrence problem?

**Comment by LichKing-2234** [comment]
by the way, which version do you use? 3.1.2 or 3.1.2-rc.1?

**Comment by LichKing-2234** [comment]
fixed in 3.1.2-rc.2

**Comment by LichKing-2234** [comment]
Only crash on iOS debug mode and reload the application.
