### ISSUE TITLE
Unable to Mute Audio/Video of the local/peers

### ISSUE THREAD

**Issue by gautamshub** [AgoraIO-Community/react-native-agora#276]
Hi,

I'm unable to mute the audio or video of the local/peers. This was working in the previous version, but with the latest version, I'm currently facing this issue. Kindly find the snippet below,

For muting the local video
`muteVideo = async () => {
      let mute = this.state.vidMute;
      this.setState({
          vidMute: !mute,
      });
      await this._engine.muteLocalVideoStream(!this.state.vidMute);
  }`

For muting the local audio
`muteAudio = async () => {
      let mute = this.state.audMute;
      this.setState({
          audMute: !mute,
      });
      await this._engine.muteLocalAudioStream(!this.state.audMute);
  }`

Previous Working Version: **^2.9.1-alpha.7**
Current Failing Version: **^3.1.2**

Kindly let me know what needs to be done to get this fixed.

**Comment by LichKing-2234** [comment]
I have tested, it works. could you pls provide our SDK log?

**Comment by gautamshub** [comment]
@LichKing-2234 - On click of that action, we couldn't find anything in the logs.

**Comment by LichKing-2234** [comment]
you can refer to this doc.
https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/react_native/classes/rtcengine.html#setlogfile

**Comment by gautamshub** [comment]
@LichKing-2234 - As per the above doc, I have added the below piece of code after the enableVideo() method, even then I couldn't find any logs in the specified folder.

`await this._engine.setLogFile("\\Users\\XXXX\\Downloads\\testlog\\agorasdk.log")`.

I have given '777'  permission to file and folder as well.

**Comment by LichKing-2234** [comment]
why set the log path to your computer?

**Comment by LichKing-2234** [comment]
I will close the issue because it is not active, you can reopen it if the issue still exists.

**Comment by HaseebArshad46** [comment]
hello
const toggleAudioMute = () => {
    if (RtcEngine && RtcEngineEvents.muteLocalAudioStream) {
      RtcEngine.muteLocalAudioStream(!isAudioMuted);
      setIsAudioMuted(!isAudioMuted);
    } else {
      console.warn('muteLocalAudioStream function not available');
    }
  };

  const toggleVideoPause = () => {
    if (RtcEngine && RtcEngineEvents.enableLocalVideo) {
      if (isVideoPaused) {
        RtcEngine.enableLocalVideo(true);
      } else {
        RtcEngine.enableLocalVideo(false);
      }
      setIsVideoPaused(!isVideoPaused);
    } else {
      console.warn('enableLocalVideo function not available');
    }
  };
  
  TypeError: _reactNativeAgora.default.muteLocalAudioStream is not a function. (In '_reactNativeAgora.default.muteLocalAudioStream(!isAudioMuted)', '_reactNativeAgora.default.muteLocalAudioStream' is undefined)
 version agora: 3.7.1
