### ISSUE TITLE
3.1.2 audio comes out of earphone on Android 10

### ISSUE THREAD

**Issue by hhemmati81** [AgoraIO-Community/react-native-agora#278]
I just updated to version 3.1.2 and I am getting testers reporting calls between iOS and Android 10 outputs audio to the earphone rather than the speakerphone on the Android side. Android to Android is fine.

I have also tried setting the default output with no luck.
`setDefaultAudioRoutetoSpeakerphone(true)`

Can you confirm this on your end?

**Comment by LichKing-2234** [comment]
This is a known problem, will be fixed in 3.2.0

**Comment by hhemmati81** [comment]
Is there a workaround for this issue? It's difficult to do public testing without audio during call.

**Comment by LichKing-2234** [comment]
you can use `LiveBroadcasting` mode first.
```
setChannelProfile(ChannelProfile.LiveBroadcasting);
setClientRole(ClientRole.Broadcaster);
```
