### ISSUE TITLE
App crash when reload

### ISSUE THREAD

**Issue by tvc97** [AgoraIO-Community/react-native-agora#279]
react-native-agora 3.1.2
xcode 12.0.1
react native 0.63.3

![Screen Shot 2020-10-06 at 11 13 53](https://user-images.githubusercontent.com/6320796/95158154-1b208580-07c5-11eb-871e-23325ce91ecc.png)

**Comment by tvc97** [comment]
Also crash when turn on remote debug

**Comment by tmjordan** [comment]
I have exactly the same problem

**Comment by tmjordan** [comment]
@tvc97 did you find a solution?

**Comment by tvc97** [comment]
@tmjordan no I didn't, I'm still struggling with this.

**Comment by LichKing-2234** [comment]
you can try `3.1.2-rc.2`

**Comment by LichKing-2234** [comment]
https://github.com/AgoraIO-Community/react-native-agora/blob/rc/3.1.2/CHANGELOG.md#312-rc2

**Comment by tvc97** [comment]
@LichKing-2234 It's work! thank you

**Comment by tmjordan** [comment]
@tvc97 @LichKing-2234 i still have that issue even when using 3.1.2-rc.2
It happens only when i enable debug mode.
Did i miss something?

**Comment by LichKing-2234** [comment]
@tmjordan any crash dump?

**Comment by tmjordan** [comment]
@LichKing-2234 actually it works, but even after installed 3.1.2-rc.2, it was still the 3.1.2 which was installed. So i think it was related to some cache. So i made a fork of the repo, and i applied the changes. Now it works
