### ISSUE TITLE
App crashes on codePush restart after adding the package

### ISSUE THREAD

**Issue by ahmadhussain** [AgoraIO-Community/react-native-agora#281]
I am doing a programmatical restart in my application at a certain point. When I add the agora package then it gives an error on the restart which is this:

`[CodePush] Restarting app.
2020-10-08 14:21:54.297315+0300 app[289:5097] [native] Invalidating <RCTCxxBridge: 0x1123143f0> (parent: <RCTBridge: 0x282c33020>, executor: (null))
2020-10-08 14:21:54.299610+0300 app[289:5251] [native] [GESTURE HANDLER] Tearing down gesture handler registered for views {(
    <RCTRootContentView: 0x112214450; reactTag: 1; frame = (0 0; 414 736); gestureRecognizers = <NSArray: 0x2809408a0>; layer = <CALayer: 0x280702080>>
)}
objc[289]: Cannot form weak reference to instance (0x2809a0750) of class RCTAgoraRtcEngineModule. It is possible that this object was over-released, or is in the process of deallocation.`

When I run my project in xcode, it adds debugger on this point:

<img width="819" alt="Screenshot 2020-10-08 at 4 25 15 PM" src="https://user-images.githubusercontent.com/2836674/95584831-bf215f80-0a57-11eb-93e9-ba7c0d10dc69.png">

I am not even using agora on the home screen. I just added the package. It loads when the app starts.
Can we initiate agora when we go to that specific screen where I need it?

**Comment by LichKing-2234** [comment]
you can refer to this.
https://github.com/AgoraIO-Community/react-native-agora/issues/279
