### ISSUE TITLE
[Android] Audio Issues when App moves to Background (as Audience)

### ISSUE THREAD

**Issue by fritzfr** [AgoraIO-Community/react-native-agora#283]
Several of our users on Android are reporting, that they are having audio issues when they app goes into background mode. Those users are not Broadcasters, but muted participants in the audience.

Might be related (but very little info): https://github.com/AgoraIO-Community/react-native-agora/issues/176.

**Comment by LichKing-2234** [comment]
sorry for the late reply, could pls provide more information about the issue?

**Comment by LichKing-2234** [comment]
refer to https://github.com/AgoraIO-Community/react-native-agora/issues/176
