### ISSUE TITLE
crash in debug mode 

### ISSUE THREAD

**Issue by syrakozz** [AgoraIO-Community/react-native-agora#284]
when i run my app in debug mode , its crashing 
2020-10-14 22:13:19.430017+0300 app[50381:13109964] [native] Invalidating <RCTCxxBridge: 0x7ffc8d70abf0> (parent: <RCTBridge: 0x600000a76ed0>, executor: RCTWebSocketExecutor)
objc[50381]: Cannot form weak reference to instance (0x600002f05e00) of class RCTAgoraRtcEngineModule. It is possible that this object was over-released, or is in the process of deallocation.
CoreSimulator 732.17 - Device: iPhone 11 (40EFB26A-B85B-482E-8337-EBE973B72861) - Runtime: iOS 14.0 (18A372) - DeviceType: iPhone 11

im using the latest version of react native agora. 3.1.3

**Comment by LichKing-2234** [comment]
Can you describe the recurrence steps in detail? It works on my devices.

**Comment by LichKing-2234** [comment]
fixed
