### ISSUE TITLE
agora increases app size by 20 MB in android 

### ISSUE THREAD

**Issue by ebrahimhassan121** [AgoraIO-Community/react-native-agora#285]
![Screen Shot 2020-10-28 at 8 43 12 PM](https://user-images.githubusercontent.com/22202170/97482138-6ceca380-195e-11eb-8a0c-51ea8e644e48.png)

**Comment by LichKing-2234** [comment]
you can use `abiFilters` to choose the abis which you want to support.
https://developer.android.com/ndk/guides/abis#gc

**Comment by ebrahimhassan121** [comment]
yes , i use it but without any written code app increased by 6 MB just included agora sdk

**Comment by LichKing-2234** [comment]
I think Audio and video functions need this size.
