### ISSUE TITLE
Cannot read perfix of null 

### ISSUE THREAD

**Issue by ghanPrasad** [AgoraIO-Community/react-native-agora#286]
I update version to 3.1.3 then i am facing this issue , 
Quick start is working fine 
please give me fix for this

**Comment by LichKing-2234** [comment]
maybe you are using 2.x version? you should refer to the quickstart and modify your code.

**Comment by ghanPrasad** [comment]
ok but for doing that  after update to version 3.1.3 my build is not  going to successful

**Comment by LichKing-2234** [comment]
any log about the failed buid?

**Comment by ghanPrasad** [comment]
![Screenshot_1604384559](https://user-images.githubusercontent.com/73588320/97955049-359d4d00-1dcb-11eb-9104-5b79bca75d22.png)

**Comment by ghanPrasad** [comment]
"react": "16.13.1",
 "react-native": "0.62.2",
"react-native-agora": "^3.1.3",
i am using above versions

**Comment by LichKing-2234** [comment]
have you rerun the application? the native code should be refreshed.

**Comment by ghanPrasad** [comment]
yes i rerun the application and native code also refresh

**Comment by LichKing-2234** [comment]
I can see you enable Hermes. by the way, have you used Expo?

**Comment by ghanPrasad** [comment]
No i don't use expo

**Comment by LichKing-2234** [comment]
seem like your native layer not been built into your project, pls double-check.

**Comment by ghanPrasad** [comment]
ok i will check

**Comment by ghanPrasad** [comment]
it is built into my project

**Comment by LichKing-2234** [comment]
could pls debug your project, and make sure `RCTAgoraRtcPackage.kt` `createNativeModules` has been called.
