### ISSUE TITLE
Build Error: "Building for iOS simulator but linking in dylib built for iOS"

### ISSUE THREAD

**Issue by vorousjames** [AgoraIO-Community/react-native-agora#288]
I just upgraded to react-native v0.63.3

**My dev environment**
Xcode: v12.0.1
React-native: v0.63.3
react-native-agora: ^3.0.1-rc.4

after installing pods, and cleaning build folder, and building app, I get this error:

> Showing Recent Errors Only
> Building for iOS Simulator, but linking in dylib built for iOS, file 
> '/Users/Desktop/Development/AppName/ios/Pods/AgoraRtcEngine_iOS_Crypto/Agora_Native_SDK_for_iOS_FULL/libs/AgoraRtcCryptoLoader.framework/AgoraRtcCryptoLoader' for architecture arm64

I would imagine theres an issue on android as well but haven't gotten into it yet.

**Comment by LichKing-2234** [comment]
you are using Xcode 12, you should remove `valid archs` from your build setting

**Comment by vorousjames** [comment]
I have no VALID_ARCHS build setting. ion either my project OR target. the ONLY existence of VALID_ARCHS is in `AgoraRtcEngine_iOS_Crypto.xcconfig`
<img width="689" alt="Screen Shot 2020-11-05 at 10 32 23 PM" src="https://user-images.githubusercontent.com/26244526/98323122-1bc05d80-1fb7-11eb-9540-c60db0d6103f.png">

**Comment by LichKing-2234** [comment]
maybe you can try 3.1.3 version

**Comment by vorousjames** [comment]
same error with react-native-agora v3.1.3

**Comment by eleviven** [comment]
Samme error

**Comment by LichKing-2234** [comment]
which version of your cocoapods?

**Comment by eleviven** [comment]
@LichKing-2234 i'm using cocoapods v1.10.0 and getting same error

**Comment by LichKing-2234** [comment]
have you tried our quickstart?

**Comment by eleviven** [comment]
@LichKing-2234 i have followed this quick start guide https://docs.agora.io/en/Video/start_call_react_native?platform=React%20Native

**Comment by elgizhv** [comment]
when i use latest react-native version (0.63.3) it crashes on ios run, but when i use 0.61.5 version (which used on quickstart sample) it works well

**Comment by eleviven** [comment]
https://zoom.us/j/97334922301?pwd=YVNFVWIyTnR3RHplTUlNT2dzbUN1Zz09

Elgiz Hacıyev <notifications@github.com>, 8 Kas 2020 Paz, 16:29 tarihinde
şunu yazdı:

**Comment by LichKing-2234** [comment]
@eleviven I means run quickstart on your simulator

**Comment by LichKing-2234** [comment]
Xcode12 may cause `Building for iOS simulator but linking in dylib built for iOS`

you should use a physical device because the simulator can't capture video and render the remote video as a green picture (because of OpenGL).
