### ISSUE TITLE
Build Error on android

### ISSUE THREAD

**Issue by eleviven** [AgoraIO-Community/react-native-agora#289]
I got an error.

[![Foo](https://i.imgur.com/aLxXfJB_d.webp?maxwidth=728&fidelity=grand)](https://imgur.com/a/wkxcsSB)

"react-native": "0.63.3",
"react-native-agora": "^3.1.3",
Android Studio 4.1

**Comment by LichKing-2234** [comment]
you can refer to [google doc](https://developer.android.com/studio/build/multidex)

**Comment by eleviven** [comment]
@LichKing-2234 Just i changed minSdkVersion 16 to 21 and worked
