### ISSUE TITLE
Unable to play the video feed

### ISSUE THREAD

**Issue by pedromarta** [AgoraIO-Community/react-native-agora#290]
Hello,

Followed all the steps from the RN Getting Started guide for Live Interactive Video Streaming and didn't add any additional configuration, but I'm struggling to broadcast video.

After mounting the remote surface view in the audience side, I get a green opacity (green when using the broadcaster uid, nothing at all when using a random uid). Audio plays just fine and, additionally, I can see through Agora's dashboard that HD video is also being broadcasted.

Broadcaster side, I have permissions enabled for both camera and mic and the video preview works as expected.

I'm using the latest version @ 3.1.3. Tried past versions of the package and still get the same exact issue.
I get the exact same results from using Android/iOS on both roles.

This are the logs I get from the broadcaster side when testing it in Android:

> INFO    (18:37:37:304 |    0)  21371; Agora SDK ver 3.0.1.1 build 7039, built on Jun 12 2020 20:50:03
> INFO    (18:37:37:304 |    0)  21371; Agora SDK git ver:fa0abaa and branch:release/3.0.1.1
> INFO    (18:37:37:305 |    1)  21371; CacheManager: load cache from storage elapsed 0
> WARN    (18:37:37:305 |    0)  21371; CacheManager: check report cache file header failed
> INFO    (18:37:37:305 |    0)  21371; initialize plugin manager
> INFO    (18:37:37:305 |    0)  21371; loading encryption module: '/data/app/com.upcomer.circles-WsUgVAAjFXSZHlZ2CAgrmw==/lib/arm64/libagora-crypto.so'
> INFO    (18:37:37:307 |    2)  21371; loaded lib '/data/app/com.upcomer.circles-WsUgVAAjFXSZHlZ2CAgrmw==/lib/arm64/libagora-crypto.so'
> INFO    (18:37:37:307 |    0)  21371; built-in encryption is enabled
> INFO    (18:37:37:307 |    0)  21371; use AHPL engine
> INFO    (18:37:37:307 |    0)  19041; Agora Rtc Engine SDK ver 3.0.1.1 build 7039, built on Jun 12 2020 20:50:06
> WARN    (18:37:37:308 |    1)  21371; set_priorities not supported!!
> INFO    (18:37:37:319 |   11)  19041; [CommonUtility] [enableOrientationListener] done!
> INFO    (18:37:37:320 |    1)  19041; [CommonUtility] [regiseterBroadcaster] done!
> INFO    (18:37:37:320 |    0)  19041; [CommonUtility] [init] done!
> INFO    (18:37:37:320 |    0)  19041; [AudioRoute] initialize +
> DEBUG   (18:37:37:320 |    0)  19041; [AudioRoute] cancel bluetooth timer
> INFO    (18:37:37:320 |    0)  19041; [AudioRoute] Monitor stopped
> INFO    (18:37:37:320 |    0)  19041; [AudioRoute] Monitor stop state, reset
> DEBUG   (18:37:37:320 |    0)  19041; [AudioRoute] cancel bluetooth timer
> INFO    (18:37:37:321 |    1)  19041; [AudioRoute] Monitor stopped
> INFO    (18:37:37:321 |    0)  19041; [AudioRoute] Headset setup: Plugged = false
> INFO    (18:37:37:323 |    2)  19041; [AudioRoute] BT headset setup: BTHeadsetPlugged = false null
> INFO    (18:37:37:324 |    1)  19041; [AudioRoute] initial Bluetooth SCO device unconnected
> INFO    (18:37:37:324 |    0)  19041; [AudioRoute] initialize -
> INFO    (18:37:37:324 |    0)  19041; [CommonUtility] manufacturer = Xiaomi
> INFO    (18:37:37:324 |    0)  19041; [CommonUtility] hardware = qcom, suspectCount = 0
> DEBUG   (18:37:37:324 |    0)  18851; [AudioRoute] BT ACTION_SCO_AUDIO_STATE_UPDATED prev -1, 0
> INFO    (18:37:37:324 |    0)  18851; [AudioRoute] Bluetooth SCO device disconnected
> DEBUG   (18:37:37:324 |    0)  18851; [AudioRoute] sendEvent: [3], extra arg: 0... Handler (io.agora.rtc.internal.AudioRoutingController$EventHandler) {1af3b1f}
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: '..'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libsentry.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libsentry-android.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libfolly_futures.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libjscexecutor.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libnative-imagetranscoder.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libfb.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libflipper.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libreactnativeblob.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libglog.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libimagepipeline.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libcrashlytics.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libevent_extra-2.1.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: '.'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libNodeMediaClient.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libevent_core-2.1.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libreactnativejni.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libagora-rtc-sdk.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libglog_init.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libyoga.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libevent-2.1.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libjsc.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libfbjni.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libjsinspector.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libfolly_json.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libc++_shared.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libjsijniprofiler.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libnative-filters.so'
> DEBUG   (18:37:37:324 |    0)  19041; [pm] checking candidate: 'libagora-crypto.so'
> INFO    (18:37:37:325 |    1)  19041; doSetClientRole 1
> INFO    (18:37:37:325 |    0)  19041; API call to setAppType
> DEBUG   (18:37:37:326 |    1)  19041; [AudioRoute] StopState: onEvent: 3, info: 0
> INFO    (18:37:37:327 |    1)  21371; network: 'NETWORK_UNKOWN' -> 'WIFI' ipv4/v6 '192.******.9'/'' gw '192.******.1'/'' subtype 100 level 4 ssid '****' bssid '' rssi -45 asu 0
> INFO    (18:37:37:327 |    0)  19041; API call to enable video
> DEBUG   (18:37:37:327 |    0)  19041; [CommonUtility] updateLocalVideoEnableState: true
> DEBUG   (18:37:37:327 |    0)  19041; [AudioRoute] sendEvent: [14], extra arg: 0... Handler (io.agora.rtc.internal.AudioRoutingController$EventHandler) {1af3b1f}
> INFO    (18:37:37:329 |    2)  21371; updateScenarioConfig: scenario(0):
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: 0 0 1 0 0   0
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: scenario(1):
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: 1 1 1 0 0   1
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: scenario(2):
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: 0 1 1 1 0   0
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: scenario(3):
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: 0 0 0 0 0   0
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: scenario(4):
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: 0 0 1 0 0   0
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: scenario(5):
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: 1 1 1 0 0   1
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: scenario(6):
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: 0 0 1 0 0   0
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: scenario(7):
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: 1 1 1 1 1   1
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: scenario(8):
> INFO    (18:37:37:329 |    0)  21371; updateScenarioConfig: 0 0 0 0 0   0
> ERROR   (18:37:37:329 |    0)  21371; audioProfile lambda: value nullptr on connect and apply default scenario
> DEBUG   (18:37:37:329 |    0)  19041; [AudioRoute] StopState: onEvent: 14, info: 0
> INFO    (18:37:37:330 |    1)  21371; [rs] updateServers 199.190.44.36:8000, priority 1
> INFO    (18:37:37:330 |    0)  21371; [rs] updateServers 199.190.44.37:8000, priority 1
> INFO    (18:37:37:330 |    0)  21371; [rlbs] selected: 118.190.148.38:9700
> INFO    (18:37:37:330 |    0)  21371; [rlbs] request rs list from 118.190.148.38:9700 with fake ch report_lbs_1604947057330.......
> INFO    (18:37:37:331 |    1)  21371; [MIO] mediaIO controller created
> INFO    (18:37:37:331 |    0)  21371; found 'xiaomi/' for device 'xiaomi/pocophone f1/beryllium/beryllium/29/4.9.186-perf-g4290b13'
> INFO    (18:37:37:331 |    0)  21371; [rp-store] {"che.audio.highQuality.enableOpenSL":false,"che.audio.opensl":true}
> DEBUG   (18:37:37:331 |    0)  21371; api call executed: che.audio.highQuality.enableOpenSL err 0, err msg is "no error"
> DEBUG   (18:37:37:331 |    0)  21371; api call executed: che.audio.opensl err 0, err msg is "no error"
> DEBUG   (18:37:37:332 |    1)  21371; [rs] start to tx cached report, items count: 0
> INFO    (18:37:37:332 |    0)  21371; [rp-cds] {}
> DEBUG   (18:37:37:332 |    0)  21371; [asr] api call report, too frequently, cache item
> INFO    (18:37:37:332 |    0)  21371; [cs] applied from cache: {"configs":{},"version":"27"}, elapsed: 786
> INFO    (18:37:37:332 |    0)  21371; [ap] selected: 118.190.148.38:8000
> INFO    (18:37:37:333 |    1)  21371; tcp_client connecting 118.190.148.38:8000
> INFO    (18:37:37:333 |    0)  21371; [ap] creating channel with 118.190.148.38:8000, ts 0, flag: 64
> INFO    (18:37:37:333 |    0)  21371; [ap] selected: 3.0.163.78:1080
> INFO    (18:37:37:333 |    0)  21371; [ap] creating channel with 3.0.163.78:1080, ts 0, flag: 64
> INFO    (18:37:37:333 |    0)  21371; [ap] selected: 47.107.39.93:25000
> INFO    (18:37:37:333 |    0)  21371; [ap] creating channel with 47.107.39.93:25000, ts 0, flag: 64
> DEBUG   (18:37:37:333 |    0)  21371; api call executed: rtc.api.start_engine err 0, err msg is "no error"
> DEBUG   (18:37:37:333 |    0)  21371; [asr] api call report, too frequently, cache item
> INFO    (18:37:37:333 |    0)  21371; [rp] {"che.android_simulator":false}
> DEBUG   (18:37:37:333 |    0)  21371; api call executed: che.android_simulator err 0, err msg is "no error"
> DEBUG   (18:37:37:333 |    0)  21371; [asr] api call report, too frequently, cache item
> INFO    (18:37:37:333 |    0)  21371; [rp] {"che.android_version":29}
> DEBUG   (18:37:37:333 |    0)  21371; api call executed: che.android_version err 0, err msg is "no error"
> DEBUG   (18:37:37:333 |    0)  21371; [asr] api call report, too frequently, cache item
> INFO    (18:37:37:333 |    0)  21371; [rp] {"rtc.client_role":1}
> INFO    (18:37:37:333 |    0)  21371; set client role to broadcaster
> DEBUG   (18:37:37:333 |    0)  21371; api call executed: rtc.client_role err 0, err msg is "no error"
> DEBUG   (18:37:37:333 |    0)  21371; [asr] api call report, too frequently, cache item
> INFO    (18:37:37:333 |    0)  21371; [rp] {"rtc.log_file":"./agora.log"}

Has anyone experienced the same issue in the past?

Thanks in advance for any help I can get with this issue.

**Comment by LichKing-2234** [comment]
got a green screen on iOS simulator?

**Comment by pedromarta** [comment]
Yap, iOS simulator. Also, just to be clear, the entire screen isn't green, just the remote view.
The very same disappears if I just decide to broadcast audio.

**Comment by LichKing-2234** [comment]
if you use an iOS simulator, you should make sure your iOS version below 12.

suggest you use a physical device because the simulator doesn't support video capture.

**Comment by pedromarta** [comment]
Thanks for the help, that was it! The video feed gets through just fine when using physical devices on both ends.
