### ISSUE TITLE
Joining more channels at once

### ISSUE THREAD

**Issue by vSleichert** [AgoraIO-Community/react-native-agora#291]
The official documentation says [here](https://docs.agora.io/en/Voice/multiple_channel_apple?platform=iOS) that joining multiple channels should be possible, but description of `joinChannel` says that _You must call [leaveChannel]{@link leaveChannel} to exit the current call before joining another channel._.

Anyway I have tried to implement it to join more channels at once but once I join another channel, the first one's video freezes.

Is there a way to join multiple channels at once with this package ?

Thanks for answers

**Comment by LichKing-2234** [comment]
you should use RtcChannel to join multiple channels

**Comment by LichKing-2234** [comment]
you can refer to this [file](https://github.com/AgoraIO-Community/react-native-agora/blob/dev%2Fbob/example/src/examples/advanced/MultiChannel.tsx) before it be merged into the master branch.

**Comment by vSleichert** [comment]
Thank you so much for your answer! I will implement it the way you provided.
