### ISSUE TITLE
UVC camera support

### ISSUE THREAD

**Issue by syron0** [AgoraIO-Community/react-native-agora#293]
Is there any plan to support UVC camera input, rather than only front/rear?

An alternative could be the possibility to use a video stream as source, but I see it's only supported in the native SDK.

Thanks

**Comment by LichKing-2234** [comment]
Do you mean custom video capture?

**Comment by syron0** [comment]
No, I mean the possibility to use an external (UVC) camera for video calls or streaming.
As of now we can only switch between front and rear camera

**Comment by LichKing-2234** [comment]
you said it only supported in the native SDK.

could you pls tell me how it support?

**Comment by syron0** [comment]
I meant that Agora supports the possibility to use a video stream as a source, but only in the native SDK, as you also stated here: #182 
Will this be supported on react native side?

Apart from this, the main question was: will the use of an external UVC camera be supported?

**Comment by LichKing-2234** [comment]
react-native SDK just a bridge of native SDK, you can add it in the native layer by yourself.
