### ISSUE TITLE
Get RemoteAudioState without listener

### ISSUE THREAD

**Issue by vSleichert** [AgoraIO-Community/react-native-agora#296]
Hi, 

I am sorry to start this as an issue, since its more like a question.

So in my RN app, I have an option to disable video and go only with audio ( in which case I have other stuff connected to this state ).

BUT, if someone joins the channel AFTER someone in the channel disables his video, I am unable to get that information about users already in channel.
Listener `RemoteAudioStateChanged` does not trigger on init and I can see no function that would give me this info.

Would you know please? 

Thanks in advance

**Comment by vSleichert** [comment]
Any updates ?

**Comment by LichKing-2234** [comment]
does UserJoined trigger?

**Comment by LichKing-2234** [comment]
```
_initEngine = async () => {
    this._engine = await RtcEngine.create(config.appId);
    this._addListeners();

    await this._engine.enableAudio();
    await this._engine.disableVideo();
    await this._engine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await this._engine.setClientRole(ClientRole.Broadcaster);
  };

  _addListeners = () => {
    this._engine?.addListener('JoinChannelSuccess', (channel, uid, elapsed) => {
      console.info('JoinChannelSuccess', channel, uid, elapsed);
      this.setState({ isJoined: true });
    });
    this._engine?.addListener('LeaveChannel', (stats) => {
      console.info('LeaveChannel', stats);
      this.setState({ isJoined: false });
    });
    this._engine?.addListener(
      'RemoteAudioStateChanged',
      (uid, state, reason, elapsed) => {
        console.info('RemoteAudioStateChanged', uid, state, reason, elapsed);
      }
    );
  };

  _joinChannel = async () => {
    if (Platform.OS === 'android') {
      await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.RECORD_AUDIO
      );
    }
    await this._engine?.joinChannel(
      config.token,
      this.state.channelId,
      null,
      config.uid
    );
  };
```

**Comment by LichKing-2234** [comment]
this works fine for me.
![image](https://user-images.githubusercontent.com/9312526/100961461-67860880-355d-11eb-83ec-d0e3d18e255c.png)

**Comment by vSleichert** [comment]
Oh sorry I ment `RemoteVideoStateChanged` of course, my bad. 
`UserJoined` triggers fine.

**Comment by LichKing-2234** [comment]
yes, `disableVideo` means diable video engine, you can try `enableLocalVideo`

**Comment by vSleichert** [comment]
For 'disabling video' we are using `muteLocalVideoStream` . My goal here is to find out the video state ( of everyone else ) once I join a channel . Just like what `RemoteVideoStateChanged` returns, but as I mentioned, that does not trigger on init. Is there any way how to get the video state anyhow else, but the `RemoteVideoStateChanged` listener?

**Comment by LichKing-2234** [comment]
`that does not trigger on init`

I can not understand this, `RemoteVideoStateChanged` will be triggered after you joined the channel.

**Comment by vSleichert** [comment]
Well, it does not trigger after I join. We are using `RtcChannel`, maybe the issue is there ?

**Comment by LichKing-2234** [comment]
I test it with `RtcEngine`, I will test it with `RtcChannel` tomorrow.

**Comment by LichKing-2234** [comment]
have you called `publish`?

**Comment by LichKing-2234** [comment]
if the remote user mute his video, you can't receive `RemoteVideoStateChanged`.

**Comment by LichKing-2234** [comment]
you can set no video state by default, and change state when you received `RemoteVideoStateChanged `.

**Comment by vSleichert** [comment]
Yeah you are right. I could have thought as well 😄 . Thanks for pointing out 👍🏼
