### ISSUE TITLE
react-native-video with react-native-agora freezes the video

### ISSUE THREAD

**Issue by voslartomas** [AgoraIO-Community/react-native-agora#297]
Hello,

we have an application which is playing video from cdn in react-native-video and also in small thumbnail there are agora streams, problem is that on iOS it is freezing after every 2-3 seconds (for just a sec and it plays again). This happens right after you create channel with `RtcChannel.create(channelName)` you don't even need to join the channel.

Also watching FPS for UI and JS and UI is dropping to 40 every those 2-3 seconds. JS fps are solid 60.

If we have only react-native-video or just react-native-agora (even multiple channels) it's solid and plays without any problems.

In XCode debug terminal I can see messages like this `Deactivating an audio session that has running I/O` it seems it freezes video every time this message appears.

Any idea, what could cause this?

**Comment by LichKing-2234** [comment]
you can try `engine.setParameters("{\"che.audio.keep.audiosession\":true}")` before join channel

**Comment by voslartomas** [comment]
Unfortunately this doesn't help, it's still freezes even with this parameters.

**Comment by LichKing-2234** [comment]
could you pls share your code about our SDK?

**Comment by voslartomas** [comment]
This is how we create an engine.

```typescript
StreamingEngine.instance = new StreamingEngine()
StreamingEngine.instance.engine = await RtcEngine.create('....')
StreamingEngine.instance.engine.setAudioProfile(AudioProfile.Default, AudioScenario.Default)
StreamingEngine.instance.engine.setVideoEncoderConfiguration(videoEncoderConfig)
StreamingEngine.instance.engine.setChannelProfile(ChannelProfile.LiveBroadcasting)
StreamingEngine.instance.engine.enableVideo()
StreamingEngine.instance.engine.enableAudioVolumeIndication(200, 3, true)
```

Then we create channel and join it (with some listeners)

```typescript
const channel = await RtcChannel.create(channelName)
channel.addListener('UserJoined', userJoinedCb)
channel.addListener('UserOffline', userOfflineCb)
channel.addListener('RemoteVideoStateChanged', remoteVideoStateChangedCb)
channel.addListener('JoinChannelSuccess', joinChannelSuccessCb)

channel.setClientRole(isBroadcaster ? ClientRole.Broadcaster : ClientRole.Audience)
channel.joinChannel(null, null, uid ?? 0 as number, new ChannelMediaOptions(true, true))

if (isBroadcaster) {
    channel.publish().catch(err => console.error(err))
}
```

**Comment by voslartomas** [comment]
If I disableAudio() in engine, react-native-video is not freezing and I cannot see those xcode messages about setActive.

**Comment by LichKing-2234** [comment]
where you add the `engine.setParameters("{\"che.audio.keep.audiosession\":true}")` code?

**Comment by voslartomas** [comment]
Oh sry, I was trying to add it right after `StreamingEngine.instance.engine.enableAudioVolumeIndication(200, 3, true)
`

**Comment by LichKing-2234** [comment]
maybe you can try `engine.joinChannel()` after call `setParameters`, do you need multi-channel?

**Comment by voslartomas** [comment]
Yes we are using multiple channels, so we need to create channel and join it, not calling engine.joinChannel, right?

**Comment by LichKing-2234** [comment]
@voslartomas yes

**Comment by voslartomas** [comment]
Are you sure that `engine.setParameters("{\"che.audio.keep.audiosession\":true}")` this is being called correctly (I mean in react native layer), because it seems this should really solve the issue.

**Comment by LichKing-2234** [comment]
if the return promise of `setParameters` does not throw an error, means success.

**Comment by voslartomas** [comment]
Yes, it's all called well, no errors thrown.

**Comment by voslartomas** [comment]
Ok actually it stopped with `Deactivating an audio session that has running I/O`, but video is still freezing, so it was not related and it must be something else, any idea what could it be? (fps drops)

If I disable audio in RtcEngine, it's fine. So I guess it's still related to something with audio.

**Comment by LichKing-2234** [comment]
you can refer to
https://github.com/react-native-video/react-native-video#audio-mixing
https://docs.agora.io/cn/Voice/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/setAudioSessionOperationRestriction:

**Comment by voslartomas** [comment]
Well yes, that is what I tried as well. Problem is I can hear audio of both videos, so that is not the problem. But it's freezing, it is like RtcEngine is trying to do every 3s and it drops FPS on UI thread.

**Comment by voslartomas** [comment]
Found out that it's causing react-native-video lib by calling `[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error:nil];` onPause, which is then repeatedly called every few seconds. Solution is to call this every time video is paused, but call it only once on app start.
