### ISSUE TITLE
Nesting in RtcLocalView.SurfaceView on Android

### ISSUE THREAD

**Issue by vSleichert** [AgoraIO-Community/react-native-agora#298]
Hi,

Once I want to put children inside `RtcLocalView.SurfaceView` , it throws this error.

![Screenshot_2020-11-25-15-54-18-150_com beappmobile](https://user-images.githubusercontent.com/45597983/100362324-8fc0b500-2ffb-11eb-97e6-8d55dd729683.jpg)

But it works fine on iOS.

"react-native-agora": "^3.1.3"
![image](https://user-images.githubusercontent.com/45597983/100361701-c6e29680-2ffa-11eb-9045-234802066de7.png)

**Comment by LichKing-2234** [comment]
you should not add any child component to our view, it just a view not viewgroup
