### ISSUE TITLE
Failure simulcasting to Facebook

### ISSUE THREAD

**Issue by ericluwj** [AgoraIO-Community/react-native-agora#300]
I have followed the live streaming tutorial for React Native at https://docs.agora.io/en/Interactive%20Broadcast/start_live_react_native?platform=React%20Native.

In order to experiment simulcasting to Facebook, I have made 3 main changes:
```js
// Set log filter.
await this._engine.setLogFilter(LogFilter.Debug)
```

```js
this._engine.addListener('JoinChannelSuccess', async (channel, uid, elapsed) => {
  console.log('JoinChannelSuccess', channel, uid, elapsed)
   // Set state variable to true
  this.setState({
    joinSucceed: true
  })

  await this._engine?.addPublishStreamUrl('rtmps://live-api-s.facebook.com:443/rtmp/<STREAM_KEY>', false)
})
```

```js
this._engine.addListener('RtmpStreamingStateChanged', (url, state, errCode) => {
  console.log('RtmpStreamingStateChanged', url, state, errCode)
})
```

I received these logs (I have replaced the stream key with the right value):
```
Warning 8
Warning 16
JoinChannelSuccess channel-x 2101467835 279
RtmpStreamingStateChanged rtmps://live-api-s.facebook.com:443/rtmp/<STREAM_KEY> 1 0
RtmpStreamingStateChanged rtmps://live-api-s.facebook.com:443/rtmp/<STREAM_KEY> 3 0
RtmpStreamingStateChanged rtmps://live-api-s.facebook.com:443/rtmp/<STREAM_KEY> 4 3
```

What I can see from the logs is that somehow the RTMP connection to Facebook could not be established and ultimately resulted in a connection timeout. I have used the exact same Facebook stream url with a broadcasting software and it works, so I'm sure the stream url is correct.

What is wrong here?

It appears that I succeeded using a different rtmp stream url from Youtube.
Is this a problem with the "rtmps" protocol or a problem with the stream key because it contains symbols such as questions marks and equal signs?

**Comment by LichKing-2234** [comment]
you should enable transcoding. you can refer to the android code.
![image](https://user-images.githubusercontent.com/9312526/100706365-dd666480-33e3-11eb-8809-de6bafbb3604.png)

**Comment by ericluwj** [comment]
I have read the web documentation that transcoding should preferably not be enabled for single host broadcasting.

And in fact, I have successfully published to Youtube's live stream with the same code.

Is this specific to just Facebook's live stream?

**Comment by LichKing-2234** [comment]
if you want to support rtmps, you must enable transcoding.
