### ISSUE TITLE
Is it possible to get state of Remote videos after join?

### ISSUE THREAD

**Issue by voslartomas** [AgoraIO-Community/react-native-agora#304]
Hi, trying to find out if users are streaming in the channel after joining it. I know there is `RemoteVideoStateChanged` listener, but it's called only once you join, but I need initial state of all the remote videos (to show some picture instead of black screen).

**Comment by LichKing-2234** [comment]
you want to get remote video state before you join channel?

**Comment by voslartomas** [comment]
I want to get video state (if they heva enabled cameras) of others after I join the channel.

**Comment by voslartomas** [comment]
Problem is if I join as last, I cannot get video state of people who joined before me.

**Comment by LichKing-2234** [comment]
it works for me.
![image](https://user-images.githubusercontent.com/9312526/100981659-0a507e00-3582-11eb-82ea-2f3fd4ac8e62.png)

**Comment by LichKing-2234** [comment]
the uid 1763140254 join the channel before me.

**Comment by voslartomas** [comment]
Ok, so remote video state changed should report all the connected streamers after another joins? So perhaps it will be something wrong in our app. Thank you, will check and let you know

**Comment by voslartomas** [comment]
Because for us, RemoteVideoStateChanged is triggered only if another users changes state after we connect. If we connect and use change this state before our connection, RemoteVideoStateChanged is not triggered.

**Comment by LichKing-2234** [comment]
`RemoteVideoStateChanged` will be triggered when you join channel success or remote video state changed.

**Comment by voslartomas** [comment]
I am not sure if we understand each other.

Imagine this situation, 1 streamer is already connected and is streaming without video (only audio, he pause video), now I am joining the channel and I need to get information about 1 streamer, that he paused the video, but `RemoteVideoStateChanged` is not triggered when I join the channel.

It is only triggered if 1 streamer pause/unpause after I join.

**Comment by LichKing-2234** [comment]
which one of `RtcEngine` and `RtcChannel` do you use? I have tested it with `RtcEngine` and it works fine.

**Comment by voslartomas** [comment]
We are using `RtcChannel`

**Comment by LichKing-2234** [comment]
have you called `publish`?

**Comment by voslartomas** [comment]
Yes

**Comment by LichKing-2234** [comment]
I think it is by design, you can let it no video by default, and change state when you received `RemoteVideoStateChanged `.

**Comment by voslartomas** [comment]
Ok! good point, thanks
