### ISSUE TITLE
Background removal of local video before render on view.

### ISSUE THREAD

**Issue by balasubrahmanyam2314** [AgoraIO-Community/react-native-agora#308]
My use case is to add a background image/bokeh effect to the video before it is rendering on the view. So the user has control over this. like he can turn on /off his background blurring or place an image.

**Comment by LichKing-2234** [comment]
you can refer to https://github.com/AgoraIO-Community/react-native-agora/wiki/Raw-data-Plugin-is-beta

**Comment by balasubrahmanyam2314** [comment]
unable to run the example of react-native-agora-rawdata in android. Installed the node modules and all.
when I comment on these lines it is working.
await AgoraRawdata.registerAudioFrameObserver(
        await agora.getNativeHandle()
      );
      await AgoraRawdata.registerVideoFrameObserver(
        await agora.getNativeHandle()
      );

I just want to know what those are exactly doing.

And some c++ code written. is it really necessary to have c++ code for the removal of the background of the local video?

when I looked into the android source code I found this AgoraRawdataModule.kt. do we need to add this package to our react native project manually?

Sorry for asking these many questions Please guide am going on the right path. Meanwhile, I'll study the documentation.
[https://docs.agora.io/en/Video/raw_data_video_android?platform=Android](url)
Thank you very much.

**Comment by LichKing-2234** [comment]
you just npm install the plugin and use it with `react-native-agora`

this demo just register raw data handler in c++ layer, and modify the raw data in android and iOS code.

you can found it here.

https://github.com/LichKing-2234/react-native-agora-rawdata/blob/main/android/src/main/java/io/agora/rtc/rawdata/react/AgoraRawdataModule.kt#L60

https://github.com/LichKing-2234/react-native-agora-rawdata/blob/main/ios/React/AgoraRawdata.swift#L81

**Comment by LichKing-2234** [comment]
if you want to implement your requirement, you should modify the code about change raw data.
