### ISSUE TITLE
createRtcChannel is not defined

### ISSUE THREAD

**Issue by crazypioneer** [AgoraIO-Community/react-native-agora#310]
createRtcChannel is not defined in react native.

https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#classio_1_1agora_1_1rtc_1_1_rtc_engine.html#a9eb0770851a8ba489564f72f9b280bca

![image](https://user-images.githubusercontent.com/35123708/101768823-72c2d080-3b29-11eb-9a9e-cf7307c93d20.png)

**Comment by crazypioneer** [comment]
[RtcEngine.native.ts.zip](https://github.com/AgoraIO-Community/react-native-agora/files/5672498/RtcEngine.native.ts.zip)

I also checked RtcEngine source class but I can't find createRtcChannel function.
But It is on API document.

Please help me...

**Comment by LichKing-2234** [comment]
pls refer to React Native doc.
https://docs.agora.io/en/live-streaming/API%20Reference/react_native/classes/rtcchannel.html
