### ISSUE TITLE
react-native-web support

### ISSUE THREAD

**Issue by victorcastro89** [AgoraIO-Community/react-native-agora#318]
HI, I'm building a multi platform App. For web I'm trying to use react-native-web, however the bundle does not compile. This library is compatible? If it's not, any suggestions? 

Thank you!

**Comment by plutoless** [comment]
@victorcastro89 the way how websdk and native sdk works are quite different, including api style and capabilities. so it's recommended to use our websdk directly to work with React in your app. if you want to reuse UI code you can create a wrapper on top of react-native sdk and websdk.
