### ISSUE TITLE
setLogFile() not changing the directory that log files are written to

### ISSUE THREAD

**Issue by marcusmolchany** [AgoraIO-Community/react-native-agora#320]
this is my code snippet for setting the log file. after this runs the logs continue to be written at the top level `<App Sandbox>/Library/Caches` directory.

```ts
import RtcEngine, { LogFilter } from 'react-native-agora';
import * as FileSystem from 'expo-file-system';

const setupLogFile = async (rtcEngine: RtcEngine) => {
  const agoraLogsDir = `${FileSystem.cacheDirectory}agoralogs`;

  // create log directory
  await FileSystem.makeDirectoryAsync(agoraLogsDir);

  const agoraLogFile = `${agoraLogsDir}/agorasdk.log`;
  await rtcEngine.setLogFile(agoraLogFile);
  await rtcEngine.setLogFilter(LogFilter.Info);
};

const rtcEngine = await RtcEngine.create(agoraConfig.appid);
setupLogFile(rtcEngine);
```

`agoralogs/` is empty in the picture below
![Screen Shot 2020-12-30 at 2 43 29 PM](https://user-images.githubusercontent.com/2160046/103384994-6a691000-4aad-11eb-8d76-3c8429ce3d66.png)

-----UPDATE-----

I'm seeing this in the `agorasdk.log` file that _is_ being written.

```
INFO    (14:52:56:201 |    0)    771; [API][rtc_engine_impl.cpp:1848][setLogFile]
INFO    (14:52:56:201 |    0)    771; [API][rtc_engine_impl.cpp:2545][queryInterface]
INFO    (14:52:56:201 |    0)    771; [API][rtc_engine_impl.cpp:974][setParameters]
INFO    (14:52:56:201 |    0) 636695; [rp] {"rtc.log_file":"file:///Users/MY-COMPUTER-REDACTED/Library/Developer/CoreSimulator/Devices/DEVICE-ID-REDACTED/data/Containers/Data/Application/APP-ID-REDACTED/Library/Caches/ag�
WARN    (14:52:56:202 |    1) 636695; create log file directory failed
```

it looks like the SDK is not seeing the full filepath `/agoralogs/agorasdk.log`, instead it's seeing `/ag`

**Comment by LichKing-2234** [comment]
your character encoding is `UTF-8`? what is `ag�`?

**Comment by marcusmolchany** [comment]
hey @LichKing-2234, yep my character encoding is utf-8. i saw in my log files that when the logs got to a certain line length it would stop logging the line and put the `�` character.

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
