### ISSUE TITLE
defining engine in function component

### ISSUE THREAD

**Issue by mtalhagaoglu** [AgoraIO-Community/react-native-agora#323]
hi. as i saw we can defined engine in component class like

`
this._engine = await  RtcEngine.create(agora_id);
`

but we don't have "this" in function component. how can i do that?  all the examples with class component

**Comment by LichKing-2234** [comment]
you can call `RtcEngine.instance()`.

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if it still exists.

**Comment by thanhit93** [comment]
Example code:


export const VideoScreen: FC<StackScreenProps<NavigatorParamList, "videoScreen">> = observer(
    ({ navigation }) => {
        const goBack = () => navigation.goBack()
        // engine state
        const [engine, setEngine] = useState(undefined);
        const [peerIds, setPeerIds] = useState([])
        const [joinSucceed, setJoinSucceed] = useState(false)

        const { characterStore } = useStores()
        //const { characters, loading } = characterStore
        const appId = "6a6e334589344ae69ae7f476a8ee8d59"
        const channelName = "channel-x"
        const token = "0066a6e334589344ae69ae7f476a8ee8d59IADAITfp1BexpV0h1uM8lHxz8umcfJGoKf4M+7amRcuM8QJkFYoAAAAAEAA+DPg7cO6wYQEAAQBw7rBh"

        useEffect(() => {
            const initPermission = async () => {
                if (Platform.OS === 'android') {
                    // Request required permissions from Android
                    requestCameraAndAudioPermission().then(() => {
                        console.log('requested!');
                    });
                }
            }
            initPermission();
        }, []);

        useEffect(() => {
            // variable used by cleanup function
            let isSubscribed = true;

            // create the function
            const createEngine = async () => {
                console.log("inside engine");
                try {
                    console.log("inside try");
                    const rtcEngine = await RtcEngine.create(appId);
                    await rtcEngine.enableVideo();

                    // need to prevent calls to setEngine after the component has unmounted
                    if (isSubscribed) {
                        setEngine(rtcEngine);
                    }
                } catch (e) {
                    console.log(e);
                }
            }

            // call the function
            createEngine();

            engine?.addListener('Warning', (warn) => {
                console.log('Warning', warn)
            })

            engine?.addListener('Error', (err) => {
                console.log('Error', err)
            })

            engine?.addListener('UserJoined', (uid, elapsed) => {
                console.log('UserJoined', uid, elapsed)
                // If new user
                if (peerIds.indexOf(uid) === -1) {
                    // Add peer ID to state array
                    setPeerIds([...peerIds, uid])
                }
            })

            engine?.addListener('UserOffline', (uid, reason) => {
                console.log('UserOffline', uid, reason)
                // Remove peer ID from state array
                setPeerIds(peerIds.filter(id => id !== uid))
            })

            // If Local user joins RTC channel
            engine?.addListener('JoinChannelSuccess', (channel, uid, elapsed) => {
                console.log('JoinChannelSuccess', channel, uid, elapsed)
                if (isSubscribed) {
                    // Set state variable to true
                    setJoinSucceed(true)
                }
            })

            startCall();

            // return a cleanup
            return () => {
                console.log('unmount')
                isSubscribed = false;
                console.log(engine)
                engine?.removeAllListeners();
                engine?.destroy();
            }

        },
            // will run once on component mount or if appId or engine changes
            [engine, appId]
        );

        const renderRemoteVideos = () => {
            return (
                <ScrollView
                    style={REMOTE_CONTAINER}
                    contentContainerStyle={{ paddingHorizontal: 2.5 }}
                    horizontal={true}>
                    {peerIds.map((value, index, array) => {
                        return (
                            <RtcRemoteView.SurfaceView
                                style={REMOTE}
                                uid={value}
                                channelId={channelName}
                                renderMode={VideoRenderMode.Hidden}
                                zOrderMediaOverlay={true} />
                        )
                    })}
                </ScrollView>
            )
        }

        /**
     * @name startCall
     * @description Function to start the call
     */
        const startCall = async () => {
            // Join Channel using null token and channel name
            await engine?.joinChannel(token, channelName, null, 0)
            console.log('startCall')
        }

        /**
         * @name endCall
         * @description Function to end the call
         */
        const endCall = async () => {
            setPeerIds([])
            setJoinSucceed(false)
            await engine?.leaveChannel()
        }

        return (
            <View testID="VideoScreen" style={FULL}>
                <GradientBackground colors={["#422443", "#281b34"]} />
                <Screen style={CONTAINER} preset="fixed" backgroundColor={color.transparent}>
                    <Header
                        headerTx="videoScreen.title"
                        leftIcon="back"
                        onLeftPress={goBack}
                        style={HEADER}
                        titleStyle={HEADER_TITLE}
                    />
                    <View style={{ flex: 1 }}>
                        {engine // check if we have an engine and not undefined
                            ?
                            <View style={{ flex: 1 }}>
                                {joinSucceed ? <RtcLocalView.SurfaceView
                                    style={{ flex: 1 }}
                                    channelId={channelName}
                                    renderMode={VideoRenderMode.Hidden} /> : null}
                                {renderRemoteVideos()}
                            </View> // if we know that we have an engine, we can do something with it
                            :
                            <ActivityIndicator /> // show a loading component while waiting for createEngine to finish 
                        }
                    </View>
                </Screen>
            </View>
        )

    },
)
