### ISSUE TITLE
Apple Silicon iOS simulator support

### ISSUE THREAD

**Issue by radko93** [AgoraIO-Community/react-native-agora#325]
The new [3.3](https://docs.agora.io/en/Voice/release_ios_audio?platform=iOS) SDK supports `XCframework` which enables use of the SDK on iOS simulator on new M1 Macs. Is there a plan to bring support soon? If not I could potentially contribute sometime soon.

**Comment by LichKing-2234** [comment]
the 3.3.0 version has been republished.
https://www.npmjs.com/package/react-native-agora/v/3.3.0-rc.1

**Comment by radko93** [comment]
I missed that, I will close this issue then thank you.
