### ISSUE TITLE
Live Audio streaming

### ISSUE THREAD

**Issue by sgkalyans** [AgoraIO-Community/react-native-agora#326]
What should I do if I just want stream audio to the mobile app like live internet radio ?

**Comment by yoreland** [comment]
there is an API "disablevideo" to completely disable video capturing and subscribing.

**Comment by sgkalyans** [comment]
> there is an API "disablevideo" to completely disable video capturing and subscribing. 

Thank you for your reply. 

could you advice whether can use "disableVideo" option in this sample project?

**Comment by yoreland** [comment]
you could call this API just bofore join channel

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
