### ISSUE TITLE
LiveBroadcasting detect listeners

### ISSUE THREAD

**Issue by mtalhagaoglu** [AgoraIO-Community/react-native-agora#327]
Hi. is there a way for detecting new or current listeners in LiveBroadcasting mode? i know we can do this in Communication mode but i need for LiveBroadcasting :/ i looked the documentation but i couldn't find anything useful.

**Comment by LichKing-2234** [comment]
listener for user join?

**Comment by mtalhagaoglu** [comment]
No. I am a host and i need to see audience for how many there are and what are their agora uid's

**Comment by plutoless** [comment]
@mtalhagaoglu we don't provide events for audience. if you need these, you will need to set up your own server and maintain the user list via websockets.

**Comment by mtalhagaoglu** [comment]
i solved this with using pusherjs if anyone interested in

**Comment by Nziranziza** [comment]
Kinda like a feature we should have
