### ISSUE TITLE
API difference between `react-native-agora` and web SDK

### ISSUE THREAD

**Issue by Invertisment** [AgoraIO-Community/react-native-agora#329]
Hi. 
I opened this issue: https://github.com/AgoraIO-Community/AgoraWebSDK-NG/issues/126
I think that both projects are not consistent with each other and both should have some kind of changes.

I think it needs to be sorted out which API is the correct one.

**Comment by LichKing-2234** [comment]
WebSDK and ReactNative SDK are two different products, and Web-NG SDK is not only for React, but if you have more suggestions, we can discuss on https://github.com/AgoraIO-Community/AgoraWebSDK-NG/issues/126.
