### ISSUE TITLE
Outdated comments or no support for remote video on iOS

### ISSUE THREAD

**Issue by Invertisment** [AgoraIO-Community/react-native-agora#330]
I've stumbled upon some comments that iOS is not supported. But this is what is given as example code in the examples.
Is this functionality not usable on iOS?

Comment1:
` * SurfaceView is supported on Android only. Use UIView on iOS.`
https://github.com/AgoraIO-Community/react-native-agora/blob/master/src/RtcRemoteView.tsx#L17

Comment2;
` * TextureView is supported on Android only. iOS does not support TextureView.`
https://github.com/AgoraIO-Community/react-native-agora/blob/master/src/RtcRemoteView.tsx#L35

This is what your example uses (which means I should use that too):
https://github.com/AgoraIO-Community/react-native-agora/blob/master/example/src/examples/basic/JoinChannelVideo.tsx#L153

https://github.com/AgoraIO-Community/react-native-agora/blob/master/example/src/examples/basic/JoinChannelVideo.tsx#L162

What would be the correct way to use this component so that iOS would be supported as well?

**Comment by LichKing-2234** [comment]
I think this is an error from the document, you should use `SurfaceView` on iOS

**Comment by LichKing-2234** [comment]
https://github.com/AgoraIO-Community/react-native-agora/commit/9cde71698a37cf8772c934510fb64b2489421163
