### ISSUE TITLE
String userAccount vs number uid for RtcRemoteView

### ISSUE THREAD

**Issue by yspektor** [AgoraIO-Community/react-native-agora#338]
Currently, the RemoteView components only support a number uid. Our api uses string uuids for users.

Are there plans to support string accounts?
And is the workaround to use getUserInfoByUserAccount() to get a remote user's uid?

**Comment by plutoless** [comment]
@yspektor right. getUserInfoByUserAccount can get you a mapping of string account to int uid. you will need to call joinChannelWithStringAccount or registerAccount before join

**Comment by yspektor** [comment]
@plutoless Thanks for the quick response!
