### ISSUE TITLE
Agora warning code emulators redefinition

### ISSUE THREAD

**Issue by nitinvi-dev** [AgoraIO-Community/react-native-agora#342]
Hello, 

I can not build `ios` while upgrading to version "3.0.1" and "agora-react-native-rtm": "^1.2.2-alpha.3" due to below error.

node_modules/react-native-agora/ios/RCTAgora/Libs/AgoraRtcKit.framework/Headers/AgoraEnumerates.h:14:28: Redefinition of 'AgoraWarningCode'

node_modules/react-native-agora/ios/RCTAgora/Libs/AgoraRtcKit.framework/Headers/AgoraEnumerates.h:16:5: Redefinition of enumerator 'AgoraWarningCodeInvalidView'

can anyone please help ?

thanks in advanced.

Rgds, Nitin

**Comment by LichKing-2234** [comment]
@nitinvi-dev seems like you are using 1.x version of `react-native-agora`?

**Comment by nitinvi-dev** [comment]
@LichKing-2234 

no, I am using `"react-native-agora": "^2.9.1-alpha.7",` and trying to upgrade to version 3.0.1

**Comment by LichKing-2234** [comment]
@nitinvi-dev you should unlink the native library, and npm install the new version. pls follow the readme.
