### ISSUE TITLE
The remote video quality very poor, only freezing

### ISSUE THREAD

**Issue by PakenduX** [AgoraIO-Community/react-native-agora#349]
Hello y'all,

I am working on a react native video call app, I use react-native-agora, everything works fine except the 
remote video quality is extremely bad, I can see nothing, it is only freezing.
I use react native agora version : 3.2.2

My rtcEngine init function : 

  `const init = async () => {
        const {token, appId} = await getToken();
        setAppId(appId);
        setToken(token);
        engine = await RtcEngine.create(appId);
        await engine.enableVideo();
        await engine.enableAudio();
        await engine?.joinChannel(token, 'channelName', null, 0);

        engine.addListener('Warning', (warn) => {
            console.log('Warning', warn);
        });

        engine.addListener('Error', async (err) => {
            if(err === 17){
                if(!engine){
                    engine = await RtcEngine.create(appId);
                }
                await engine?.leaveChannel();
                setPeerIds(peerIds => []);
                await engine?.joinChannel(token, `${session.id}`, null, 0);
            }
            console.log('Error', err);
        });

        engine.addListener('UserJoined', async (uid, elapsed) => {
            console.log('UserJoined', uid, elapsed);
            // Get current peer IDs
            // If new user
            if (peerIds.indexOf(uid) === -1) {
                setPeerIds(peerIds => [...peerIds, uid]);
            }
        });

        engine.addListener('UserOffline', (uid, reason) => {
            console.log('UserOffline', uid, reason);
            setPeerIds(peerIds => [...peerIds.filter((id) => id !== uid)]);
        });

        // If Local user joins RTC channel
        engine.addListener('JoinChannelSuccess', (channel, uid, elapsed) => {
            console.log('JoinChannelSuccess', channel, uid, elapsed);
            // Set state variable to true
            setJoinSucceed(true);
        });
    }`

I am sorry I cannot get my code well formatted here, I don't now why.

Thanks in advance for your help.

**Comment by plutoless** [comment]
could you pls provide your channel name?

**Comment by PakenduX** [comment]
> could you pls provide your channel name?

**Comment by PakenduX** [comment]
> could you pls provide your channel name?

Hello, my channel name depends on an id of a database table : `${session.id}`

**Comment by PakenduX** [comment]
> > could you pls provide your channel name?
> 
> Hello, my channel name depends on an id of a database table : `${session.id}`

Hello plutoless I finally solved my problem thank you.

**Comment by LichKing-2234** [comment]
could you pls share your solution? I think it will help other developers who face the same issue.

**Comment by PakenduX** [comment]
Of course for those who have the same issue, I just change my videoEncoderConfiguration like this:

`await engine.setVideoEncoderConfiguration(new VideoEncoderConfiguration({
        dimensions: new VideoDimensions(320, 240),
        bitrate: 140,
        frameRate: VideoFrameRate.Fps30,
        degradationPrefer: 0
    }))`
