### ISSUE TITLE
Audio is playing in the background as soon as a remote user joins channel

### ISSUE THREAD

**Issue by sheyDev** [AgoraIO-Community/react-native-agora#350]
The audio is playing the background even though RtcRemoteView.SurfaceView is not on the screen. We confirmed it wasnt on the screen by completely removing it from the code, still we can hear the remote users audio.

This is what we use to login and join the channel. Is there something im missing here?

`
const login = useCallback(async (eventsCallback) => {
  await client.createInstance(appId);

  client.removeAllListeners();
  Object.keys(RtmEngineEvents).forEach((key) => {
        client.addListener(RtmEngineEvents[key], (evt) => {
        eventsCallback({
        event: RtmEngineEvents[key],
        data: evt
        });
    });
  });

await client.loginV2(user_id, token);
}, [token, user_id]);

const joinChannel = useCallback(async () => {
  try {
    await client.joinChannel(channel_id);
  } catch (error) {
    console.log(error);
    throw error;
    }
 }, [channel_id]);
`

`
client.addListener(RtcEngineEvents.UserJoined, (uid, elapsed) => {
  callback({
  event: RtcEngineEvents.UserJoined,
    data: {
    uid,
    elapsed
    }
});
});`

**Comment by LichKing-2234** [comment]
the view just for video, you should use muteRemoteAudio to control audio

**Comment by sheyDev** [comment]
cool, got it. assumed it played only if the component was added, thanks! @LichKing-2234
