### ISSUE TITLE
iOS Problem

### ISSUE THREAD

**Issue by mtalhagaoglu** [AgoraIO-Community/react-native-agora#352]
Hi,

I am not able to make it run this lib on ios devices :/ on android there is no problem its flawless but ios it gives strange errors. probably its because of me but still strange. I didn't edit any of native lib files, this is my error:

```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file react_native_agora/RtcEngine.swift, line 529
2021-03-31 19:21:23.591430+0300 poducer[3843:1112634] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file react_native_agora/RtcEngine.swift, line 529
(lldb) 
```

**Comment by RoJoHub** [comment]
> Hi,
> 
> I am not able to make it run this lib on ios devices :/ on android there is no problem its flawless but ios it gives strange errors. probably its because of me but still strange. I didn't edit any of native lib files, this is my error:
> 
> ```
> Fatal error: Unexpectedly found nil while unwrapping an Optional value: file react_native_agora/RtcEngine.swift, line 529
> 2021-03-31 19:21:23.591430+0300 poducer[3843:1112634] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file react_native_agora/RtcEngine.swift, line 529
> (lldb) 
> ```

Could you please provide more detain about version of sdk or Specific `swift code`.

**Comment by mtalhagaoglu** [comment]
![swift](https://user-images.githubusercontent.com/47723198/113290180-eca9e000-92f9-11eb-8e4a-981f6b7aec66.jpg)
this is the swift code that xcode shows to me. my xcode version is 12.4 btw

**Comment by RoJoHub** [comment]
Please confirm in the js file whether the three parameters of `interval` `smooth` `report_vad` are passed correctly.


```ts
enableAudioVolumeIndication(
    interval: number,
    smooth: number,
    report_vad: boolean
  ): Promise<void>
```

**Comment by mtalhagaoglu** [comment]
in my js code, i didn't give any parameters to that function. should i do that? because in android it is working like that even there is no warning.

**Comment by RoJoHub** [comment]
> in my js code, i didn't give any parameters to that function. should i do that? because in android it is working like that even there is no warning.

This is doc:
https://docs.agora.io/en/Video/API%20Reference/flutter/rtc_engine/RtcEngine/enableAudioVolumeIndication.html
