### ISSUE TITLE
When displaying a video on top of a video using the RtcRemoteView.SurfaceView component, borderRadius not working with zOrderOnTop 

### ISSUE THREAD

**Issue by dylancolin** [AgoraIO-Community/react-native-agora#353]
Trying to display a video on top of another video. 
The bottom video is a fullscreen video. 
// FullVideo.js
`<View fullScreen style={{ position: 'absolute', top: 0, left: 0, zIndex: 0}}>
    <RtcRemoteView.SurfaceView style={{ flex: 1 }} uid={uid} channelId={channelId} renderMode= 
    {VideoRenderMode.Hidden} zOrderMediaOverlay />}
</View>
`

Another video is displayed as absolute positioned, on top of it. 
// SmallVideo.js
`
<View  style={{ width, height, borderRadius: 10, overflow: 'hidden', zIndex: 2 }}>
    <RtcRemoteView.SurfaceView style={{ flex: 1 }} uid={uid} channelId={channelId} renderMode={VideoRenderMode.Hidden} zOrderOnTop />
</View>
`

When in SmallVideo.js the  zOrderMediaOverlay prop is set,  the View becomes TRANSPARENT
When in SmallVideo.js the  zOrderOnTop prop is set, borderRadius does not work even with overflow hidden

Even zIndex in the SurfaceView style doesn't have any effect. Is there something missing here? 
I am using the react native v0.63.3

**Comment by RoJoHub** [comment]
Maybe you should use `removeClippedSubviews` and `overflow: 'hidden'`
![14201617691545_ pic](https://user-images.githubusercontent.com/15648309/113669776-cb286a00-96e6-11eb-8539-a09271d6b8bf.jpg)

```jsx
import React, { Component, Fragment } from 'react';
import {
  Button,
  PermissionsAndroid,
  Platform,
  ScrollView,
  StyleSheet,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';

import RtcEngine, {
  ChannelProfile,
  ClientRole,
  RtcEngineConfig,
  RtcLocalView,
  RtcRemoteView,
} from 'react-native-agora';

const config = require('../../../agora.config.json');

interface State {
  channelId: string;
  isJoined: boolean;
  remoteUid: number[];
  switchCamera: boolean;
  switchRender: boolean;
  uid?: number;
}

export default class JoinChannelAudio extends Component<{}, State, any> {
  _engine: RtcEngine | undefined;

  constructor(props: {}) {
    super(props);
    this.state = {
      channelId: config.channelId,
      isJoined: false,
      remoteUid: [],
      switchCamera: true,
      switchRender: true,
    };
  }

  UNSAFE_componentWillMount() {
    this._initEngine();
  }

  componentWillUnmount() {
    this._engine?.destroy();
  }

  _initEngine = async () => {
    this._engine = await RtcEngine.createWithConfig(
      new RtcEngineConfig(config.appId)
    );
    this._addListeners();

    await this._engine.enableVideo();
    await this._engine.startPreview();
    await this._engine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await this._engine.setClientRole(ClientRole.Broadcaster);
  };

  _addListeners = () => {
    this._engine?.addListener('JoinChannelSuccess', (channel, uid, elapsed) => {
      console.info('JoinChannelSuccess', channel, uid, elapsed);
      this.setState({ isJoined: true });
    });
    this._engine?.addListener('UserJoined', (uid, elapsed) => {
      console.info('UserJoined', uid, elapsed);
      this.setState({ uid });
      this.setState({ remoteUid: [...this.state.remoteUid, uid] });
    });
    this._engine?.addListener('UserOffline', (uid, reason) => {
      console.info('UserOffline', uid, reason);
      this.setState({ uid: null });
      this.setState({
        remoteUid: this.state.remoteUid.filter((value) => value !== uid),
      });
    });
    this._engine?.addListener('LeaveChannel', (stats) => {
      console.info('LeaveChannel', stats);
      this.setState({ isJoined: false, remoteUid: [] });
    });
  };

  _joinChannel = async () => {
    if (Platform.OS === 'android') {
      await PermissionsAndroid.requestMultiple([
        PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
        PermissionsAndroid.PERMISSIONS.CAMERA,
      ]);
    }
    await this._engine?.joinChannel(
      config.token,
      this.state.channelId,
      null,
      config.uid
    );
  };

  _leaveChannel = async () => {
    await this._engine?.leaveChannel();
  };

  _switchCamera = () => {
    const { switchCamera } = this.state;
    this._engine
      ?.switchCamera()
      .then(() => {
        this.setState({ switchCamera: !switchCamera });
      })
      .catch((err) => {
        console.warn('switchCamera', err);
      });
  };

  _switchRender = () => {
    const { switchRender, remoteUid } = this.state;
    this.setState({
      switchRender: !switchRender,
      remoteUid: remoteUid.reverse(),
    });
  };

  render() {
    const { channelId, isJoined, switchCamera } = this.state;
    return (
      <View style={styles.container}>
        <View style={styles.top}>
          <TextInput
            style={styles.input}
            onChangeText={(text) => this.setState({ channelId: text })}
            placeholder={'Channel ID'}
            value={channelId}
          />
          <Button
            onPress={isJoined ? this._leaveChannel : this._joinChannel}
            title={`${isJoined ? 'Leave' : 'Join'} channel`}
          />
        </View>
        {this._renderVideo()}
      </View>
    );
  }

  _renderVideo = () => {
    const { remoteUid } = this.state;
    const u1 = remoteUid[0];
    const u2 = remoteUid[1];
    console.log('u1', u1, 'u2', u2, remoteUid);

    if (!u1) {
      return null;
    }
    return (
      <RtcRemoteView.SurfaceView
        style={styles.container}
        uid={u1}
        zOrderMediaOverlay={true}
      >
        <View style={styles.float} collapsable={false}>
          {!!u2 && (
            <RtcRemoteView.SurfaceView
              style={styles.small}
              uid={u2}
              zOrderMediaOverlay={true}
              zOrderOnTop
              removeClippedSubviews
            />
          )}
        </View>
      </RtcRemoteView.SurfaceView>
    );
  };
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  small: {
    width: 200,
    height: 200,
    position: 'absolute',
    borderWidth: 2,
    borderRadius: 40,
    borderColor: 'yellow',
    overflow: 'hidden',
  },
  float: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 200,
    height: 200,
  },
  top: {
    width: '100%',
  },
  input: {
    borderColor: 'gray',
    borderWidth: 1,
  },
  local: {
    flex: 1,
  },
  remoteContainer: {
    position: 'absolute',
    left: 0,
    top: 0,
  },
  remote: {
    width: 120,
    height: 120,
  },
});

```

**Comment by dylancolin** [comment]
Hey @RoJoHub  Thanks for the reply! I tried with removeClippedSubviews and overflow: 'hidden' on android, seems like no effect for me. It displays transparent view like this
![WhatsApp Image 2021-04-06 at 21 53 57](https://user-images.githubusercontent.com/19780195/113745935-64757180-9723-11eb-876f-c1cf48cf58ec.jpeg)

**Comment by RoJoHub** [comment]
> Hey @RoJoHub Thanks for the reply! I tried with removeClippedSubviews and overflow: 'hidden' on android, seems like no effect for me. It displays transparent view like this
> ![WhatsApp Image 2021-04-06 at 21 53 57](https://user-images.githubusercontent.com/19780195/113745935-64757180-9723-11eb-876f-c1cf48cf58ec.jpeg)

Could you please provide a demo

**Comment by louxinbo** [comment]
@dylancolin Did you try to use `RtcRemoteView.TextureView`? 
The `borderRadius` did not work for me, when I used `SurfaceView`, after I changed to `TextureView` then it worked.

**Comment by LichKing-2234** [comment]
if you use SurfaceView on Android, you should change the `zOrderMediaOverlay` property to control the layer order.

**Comment by dylancolin** [comment]
> @dylancolin Did you try to use `RtcRemoteView.TextureView`?
> The `borderRadius` did not work for me, when I used `SurfaceView`, after I changed to `TextureView` then it worked.

@louxinbo did not knew i could use the TextureView, i tried the RtcRemoteView.TextureView and borderRadius did work for me.  Thank you so much!   However, Is there any performance differences between the SurfaceView and TextureView that need to be considered?

**Comment by louxinbo** [comment]
> > @dylancolin Did you try to use `RtcRemoteView.TextureView`?
> > The `borderRadius` did not work for me, when I used `SurfaceView`, after I changed to `TextureView` then it worked.
> 
> @louxinbo did not knew i could use the TextureView, i tried the RtcRemoteView.TextureView and borderRadius did work for me. Thank you so much! However, Is there any performance differences between the SurfaceView and TextureView that need to be considered?

@dylancolin From my research, SurfaceView has better performance, while TextureView has advantages of alpha, rotate, transform, animate. 
Source: https://source.android.com/devices/graphics/arch-tv

**Comment by LichKing-2234** [comment]
seem like the issue has been solved.
