### ISSUE TITLE
Android 10. await RtcEngine.create(AGORA_ID) is never resolves

### ISSUE THREAD

**Issue by kolyuchii** [AgoraIO-Community/react-native-agora#354]
```
"react": "16.11.0",
"react-native": "0.62.2",
"react-native-agora": "^3.3.2",
```

Starting the engine code
```
    async _createEngine() {
            this._engine = await RtcEngine.create(AGORA_ID);
            this._setListeners();
    }
```

but the this._setListeners(); method is never executed

**Comment by RoJoHub** [comment]
It seems that you don't configure `AGORA_ID `

**Comment by kolyuchii** [comment]
> It seems that you don't configure `AGORA_ID `

Hi @RoJoHub!

As I found, the problem was a cache. 
I've uninstalled and re install the app on your device after clearing the cache and deleting the build folder.
