### ISSUE TITLE
'react_native_agora.modulemap' not found

### ISSUE THREAD

**Issue by rewdt** [AgoraIO-Community/react-native-agora#355]
I have an ejected expo application and have been trying to setup agora on ios. However, I keep getting this error

`module map file '/Users/rewdt/Library/Developer/Xcode/DerivedData/positiveoapp-atfvcuuobfizhpacqepswehcplgi/Build/Products/Debug-iphonesimulator/react-native-agora/react_native_agora.modulemap' not found`

I am currently testing on an apple silicon(m1 pro), with xcode 12.4 however a teammate was able to set it up on his intel based device seamlessly.  Any idea as to what the cause is and how this can be resolved? 

Thank you

**Comment by RoJoHub** [comment]
Please refer to this

https://github.com/facebook/react-native/issues/29605#issuecomment-813129520

**Comment by zhigang1992** [comment]
We had both pod file and Xcode set to the same target, and this still happened.

I think this is an issue related to m1.

@rewdt have you fixed it on your m1 yet?

I was able to get it working with Mac as direct target (instead of Simulator).
