### ISSUE TITLE
How do I get past the AppleStore review process?

### ISSUE THREAD

**Issue by Tatara-Takumi** [AgoraIO-Community/react-native-agora#357]
Hi, I submitted an app to AppStore using react-native-agora for voice communication, but it was rejected because the voice was not audible.
Voice is fine at test flights and during development.

The AppStore review team is testing via VPN, so that's probably the problem, but I don't know much about networks, so I don't know what the solution is.
What should I do?

I am using the react-native v0.63.4, react-native-agora v3.2.2

**Comment by RoJoHub** [comment]
Under normal circumstances, you need to tell the reviewers that there is a problem with the vpn they are using
In addition, you may need to provide a video to the reviewers to prove that it is their problem

**Comment by Tatara-Takumi** [comment]
Thanks for replying!!
I sent a demo video in the past, but it still hasn't been approved...
I send email again with a demo video to see if it can be approved!

**Comment by rafaelcavalcante** [comment]
Hi @Tatara-Takumi. Did it work?

**Comment by Tatara-Takumi** [comment]
@rafaelcavalcante 
I went through Review !!
It seems that we need to not only put out a video, but also make sure to point out that there is a problem on Apple's side.

Thank you, @RoJoHub
