### ISSUE TITLE
muteLocalVideoStream and UserMuteVideo / Audio event interaction between rn sdk and web sdk

### ISSUE THREAD

**Issue by sheyDev** [AgoraIO-Community/react-native-agora#358]
Hey guys!
When i call muteLocalVideoStream (meant to stop sending the video stream) it works as expected on the remote (web sdk) client. Same with muteLocalAudioStream. But if they're both done (audio & video muted), 5 seconds after the last call, the remote client fires a 'stream-removed' event. This is different from how the web sdk operates when av mute functions are called. it just fires the mute-audio/video but doesn't call stream-removed until the stream.stop() method is called.

Question: is this how these methods are supposed to work or is it a bug?

Thank you!

**Comment by RoJoHub** [comment]
Hello there 
The current mobile sdk and web sdk interaction events are a bit problematic.
We are following up on this issue

**Comment by RoJoHub** [comment]
please refer to this

**Comment by DevMinhThu** [comment]
@RoJoHub hello, I am facing this issue. Has this issue been solved yet?
