### ISSUE TITLE
AgoraRtcKit/AgoraRtcEngineKit.h file not found

### ISSUE THREAD

**Issue by salmanxoxo** [AgoraIO-Community/react-native-agora#362]
![Screenshot 2021-04-19 at 12 15 38 AM](https://user-images.githubusercontent.com/5101083/115157131-2d00b080-a0a5-11eb-997c-6f93a4da78c3.png)

Getting this error while running on IOS. Android is working fine.

**Comment by plutoless** [comment]
usually this is because your cocoapods link failed. pls read readme faqs

**Comment by salmanxoxo** [comment]
package.json:

```
"react-native": "~0.63.4",
"react-native-agora": "^3.3.2",
```
Podfile.lock:

```
- react-native-agora (3.3.2):
- AgoraRtcEngine_iOS (= 3.3.1)
```

**Comment by salmanxoxo** [comment]
> usually this is because your cocoapods link failed. pls read readme faqs

But linking is automatic for RN > .60 right?

**Comment by plutoless** [comment]
https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
autolinking still requires this extra step for ios

**Comment by salmanxoxo** [comment]
how can i fix the linking for IOS for this? please guide me through the steps

**Comment by salmanxoxo** [comment]
> https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
> autolinking still requires this extra step for ios

how can i fix the linking for IOS for this? please guide me through the steps

**Comment by plutoless** [comment]
just step into ios folder and run pod install separately after you add dependency

**Comment by salmanxoxo** [comment]
> just step into ios folder and run pod install separately after you add dependency

already did pod install.

**Comment by plutoless** [comment]
https://github.com/AgoraIO-Community/Agora-RN-Quickstart
maybe try this quickstart

**Comment by salmanxoxo** [comment]
> https://github.com/AgoraIO-Community/Agora-RN-Quickstart
> maybe try this quickstart

i already followed those steps. android is working fine. the link says only `cd ios && pod install` which i have already done.

**Comment by salmanxoxo** [comment]
should i do `react-native link react-native-agora` ?

**Comment by LichKing-2234** [comment]
> should i do `react-native link react-native-agora` ?

No, pls make sure your project support swift. 
You should create a swift file by Xcode to make your project support swift.

**Comment by salmanxoxo** [comment]
> > should i do `react-native link react-native-agora` ?
> 
> No, pls make sure your project support swift.
> You should create a swift file by Xcode to make your project support swift.

![Screenshot 2021-04-19 at 9 22 40 AM](https://user-images.githubusercontent.com/5101083/115179500-0d8f7500-a0f1-11eb-8c3e-3bc3686d5cd8.png)
I have done that too.

**Comment by LichKing-2234** [comment]
why you link our library? you should keep auto-linking.

**Comment by salmanxoxo** [comment]
I kept auto linking first. i got this error. then i followed [this link](https://github.com/AgoraIO-Community/react-native-agora/issues/39) added library to the project.

**Comment by LichKing-2234** [comment]
maybe you can try our example or quickstart first.

**Comment by amingsc** [comment]
same issue +1

debug build is ok, error only when release build.

**Comment by amingsc** [comment]
> same issue +1
> 
> debug build is ok, error only when release build.

release build on device is ok, simulator will result error.(but it's alright before i upgrade rn0.61 to 0.64,why? is it a bug with new version agora?)

**Comment by LichKing-2234** [comment]
maybe 0.64 support new version of swift, you can try to delete the empty swift file in your project and renew it to migrate the new version of swift.

**Comment by salmanxoxo** [comment]
> maybe you can try our example or quickstart first.

tried this on a demo project. that is working fine. when i try to add this to my existing project im getting this error. but tried on xcode 11. thats working fine. having this issue with xcode 12. dont know exactly what the issue is.

**Comment by EnginYilmaz** [comment]
I have been pulling my hairs for about 4 days with half sleeping. I tried every single recipe I found on github starting over and over again even starting with example project but no luck. 

Now I tried older versions of react-native-agora@3.0.1 and it can compile a release version without error.
