### ISSUE TITLE
There's a 10 seconds delay for mute event in RemoteAudioStateChanged

### ISSUE THREAD

**Issue by louxinbo** [AgoraIO-Community/react-native-agora#372]
![image](https://user-images.githubusercontent.com/22609051/118573185-65d79680-b7c5-11eb-95db-7b4b492591b1.png)
In my screenshot red area, is the state/reason changes. When a remote user mute himself (`enableLocalAudio(false)`)), I will first get state 3 `Frozen`, reason is `NetworkCongestion`, then I will get state 2, which means `decoding`, Then finally I can get state 0, reason is `RemoteMuted`, there's a 10 seconds delay.
Do you have any solution for getting this state faster?

**Comment by plutoless** [comment]
is this 100% reproducible?

**Comment by louxinbo** [comment]
@plutoless 
Hi, yes, it happens consistently.
![image](https://user-images.githubusercontent.com/22609051/118602082-8f101b00-b7f5-11eb-8643-7e10264e7b17.png)
I found there's a time elapse value, and the delay is around 13 seconds.

**Comment by louxinbo** [comment]
@plutoless 
Hi, I need to mention that I was using `enableLocalAudio` API
If I change to use `MuteLocalAudioStream`, the delay is very small. 
![image](https://user-images.githubusercontent.com/22609051/118602622-460c9680-b7f6-11eb-8bdc-b73057099bc7.png)

**Comment by LichKing-2234** [comment]
> @plutoless
> Hi, I need to mention that I was using `enableLocalAudio` API
> If I change to use `MuteLocalAudioStream`, the delay is very small.
> ![image](https://user-images.githubusercontent.com/22609051/118602622-460c9680-b7f6-11eb-8bdc-b73057099bc7.png)

yes, `enableLocalAudio` will cause a delay.

**Comment by phuocantd** [comment]
same to when I switch camera

**Comment by LichKing-2234** [comment]
I will close this issue, if it still exists, you can reopen it.
