### ISSUE TITLE
method setEnableSpeakerphone can not triggered event AudioRouteChanged when the headset is pluged in

### ISSUE THREAD

**Issue by vietdung123** [AgoraIO-Community/react-native-agora#373]
Iam looking for a way to switch to Speakerphone or Earpiece when Headset still pluged in. I try method setEnableSpeakerphone() but seem it not work (event AudioRouteChanged not triggered ). Can someone give me some solution? Many thanks

**Comment by LichKing-2234** [comment]
have you followed the doc? https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/react_native/classes/rtcengine.html#setenablespeakerphone

**Comment by vietdung123** [comment]
> have you followed the doc? https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/react_native/classes/rtcengine.html#setenablespeakerphone 
Thank LickKing, yes i see it, so there's no way to switch audio output to other one right? ( in case: Headset Plugged in).
Like some other apps, it can switch to speakerphone while still plugging in headset.

**Comment by louxinbo** [comment]
I have the same issue, it should let the user choose the route.
