### ISSUE TITLE
Text Chat SDK

### ISSUE THREAD

**Issue by seamive** [AgoraIO-Community/react-native-agora#378]
Does this package allow the usage of normal group text chat for react-native?
Probably this: https://www.agora.io/en/products/real-time-messaging/

We're planning to run a group channel for people to comment or discuss topics. Channels could be created dynamically.

Thanks!

**Comment by LichKing-2234** [comment]
pls use https://github.com/agoraio/agora-react-native-rtm

**Comment by seamive** [comment]
@LichKing-2234 : That hasn't been updated for 5 months. Also, I cannot see the channel/RTMP option in our Agora dashboard.
