### ISSUE TITLE
Momentary pause in audio when switching between client role Audience <=> Broadcaster

### ISSUE THREAD

**Issue by jaydgoss** [AgoraIO-Community/react-native-agora#379]
When using the method `setClientRole` to toggle between `ClientRole.Broadcaster` and `ClientRole.Audience` there is a brief pause in audio from the stream while the OS appears to switch between recording and publishing, to not recording and just consuming.

Is there an alternate method to switch between broadcasting <=> consuming, or an additional parameter I can configure to prevent this momentary lapse in audio from the stream?

Using react-native-agora v3.3.3.

**Comment by LichKing-2234** [comment]
you can use muteLocalAudioStream or muteRemoteAuduoStream API to control it.

**Comment by jaydgoss** [comment]
I did try this but found that when using `.muteLocalAudioStream(false)`, `LocalAudioStateChanged` would never update to recording or encoding.  I'll try again to get more details.

**Comment by jaydgoss** [comment]
This was due to the audio profile scenario being set to `AudioScenario.GameStreaming`.
