### ISSUE TITLE
Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by marcojr** [AgoraIO-Community/react-native-agora#382]
Hey ! I just followed the steps of https://docs.agora.io/en/Video/start_call_react_native?platform=React%20Native

And when I start a call I got this error

 ERROR  Error: Text strings must be rendered within a <Text> component.

This error is located at:
    in RCTView (at View.js:34)
    in View (at App.tsx:136)
    in RCTView (at View.js:34)
    in View (at App.tsx:115)
    in RCTView (at View.js:34)
    in View (at App.tsx:114)
    in App
    in RCTView (at View.js:34)
    in View (at AppContainer.js:107)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:134)
    in AppContainer (at renderApplication.js:40)
 ERROR  Error: Text strings must be rendered within a <Text> component.

Since it's inside the RCTView, I believe that's something involving this library.

Can someone help me with this ? Thanks in advance !

**Comment by LichKing-2234** [comment]
could you share your code?

**Comment by LichKing-2234** [comment]
you should not add comments into the View tag

**Comment by marcojr** [comment]
Thanks @LichKing-2234 ! Well..I just copy/pasted the official documentation. Sadly they dont'test what they post. But ty ! Now it works !

**Comment by LichKing-2234** [comment]
@marcojr I have feedback to the documentation team, it will be fixed.
