### ISSUE TITLE
unable to see the user when one user connects via mobile and the other via web app

### ISSUE THREAD

**Issue by gosrinin** [AgoraIO-Community/react-native-agora#390]
Our application support 1:1 video calling
User A has an option to join from Web and Mobile app(Android/IOS) and Where as User B can join only through web application
Currently what we are experiencing is when both user is joining via web application both of them are able to see and hear each other where as
when as user "A" joins via mobile user "A" is able to see and hear user "B" where as user "B" who has joined via web application cannot see or hear the User "A"
in web app we are not receiving any joining events of user "a" where as when user "a" leaves the channel from mobile app we are able to receive response
Event name:"peer leaved"
![WhatsApp Image 2021-07-03 at 11 57 57 PM (1)](https://user-images.githubusercontent.com/46101043/124363876-b0b94a80-dc5b-11eb-973f-bf6ac5e54e2b.jpeg)
![WhatsApp Image 2021-07-03 at 11 57 57 PM](https://user-images.githubusercontent.com/46101043/124363877-b1ea7780-dc5b-11eb-99fe-21ce5b57da48.jpeg)
![WhatsApp Image 2021-07-03 at 11 57 57 PM (1)](https://user-images.githubusercontent.com/46101043/124363885-b747c200-dc5b-11eb-8ace-d829a959c972.jpeg)
![WhatsApp Image 2021-07-03 at 11 57 57 PM](https://user-images.githubusercontent.com/46101043/124363896-bd3da300-dc5b-11eb-9173-f0f0f63392d8.jpeg)

reason: server time out
I have attached the screenshot for reference do kindly help us to fix the issue.
Agora React Native SDK:3.4.2
Agora web SDK:3.6.0

**Comment by LichKing-2234** [comment]
mayby you are using the string uid on web.

**Comment by gosrinin** [comment]
thats right when we changed the uid its working fine thanks
