### ISSUE TITLE
TypeError: null is not an object (evaluating 'AgoraRtcChannelModule.prefix')

### ISSUE THREAD

**Issue by Waker777** [AgoraIO-Community/react-native-agora#393]
When i run my app on the ios, i get the error 'TypeError: null is not an object (evaluating 'AgoraRtcChannelModule.prefix')'
Can you give me a some suggestion why this is happen?

    "react": "17.0.1",
    "react-native": "0.64.2",
    "react-native-agora": "^3.4.2"
     iOS:14
    MacOS Big Sure 11.3.1

**Comment by LichKing-2234** [comment]
pls try our example first.
there are some causes of your issue:
1. You are opening the .project and run it by XCode, pls open the .workspace.
2. You may not rerun the application after you run `npm install react-native-agora`.
3. You are using expo, pls refer to #188.

**Comment by Waker777** [comment]
Ohh, problem was very simple, after pulling my branch i forget run 'pod install'...sorry and thx ))

**Comment by brytoz** [comment]
Having the same problem.
`TypeError: null is not an object (evaluating 'AgoraRtcChannelModule.prefix')`

I've tried expo eject, include the expo-dev-client, and installed agora-react-native-rtm  but still same issue. How can i fix this @LichKing-2234 ?

**Comment by EkaanshArora** [comment]
@brytoz are you trying to use this on iOS? Did you run pod install after building your expo dev client?  
Are you using `expo run:ios` or `expo run:android` to run the project?

**Comment by lionelbui** [comment]
Hi support?
is working with Expo?

**Comment by Coding-Algorithm** [comment]
Hy... I am experiencing this bug on my project...

I run my expo project with 'expo run:android' which made available, the android folder, I have react-native-agora, agora-rn-uikit, agora-react-native-rtm yet I am still getting this error:

`TypeError: null is not an object (evaluating 'AgoraRtcChannelModule.prefix')`
