### ISSUE TITLE
RtcEngine startAudioiMixing not working in production release

### ISSUE THREAD

**Issue by hongzhou85** [AgoraIO-Community/react-native-agora#398]
Hi I'm using the RTCEngine to mix in audio to be use during conversation. 
The code is working during development (debug) of both android and iOS. However, when release, it is not playing on android but some sound are working on iOS. I wonder what could be the issue?

Below is a sample code of how I mix the audio files:

`
const enterRoomAlert = async () => {

        const enterAlertAudio = Asset.fromModule(require('../assets/audio/mixkit-guitar-stroke-up.wav')).uri;
        
        await currentContext.rtcEngine
        .startAudioMixing(enterAlertAudio, false, false, 1, 0)
        
    }
`

**Comment by LichKing-2234** [comment]
you should not use assets on RN, the real file path is different between debug and release mode.
you should add the files to the native project, and use the path to call this method.

**Comment by hongzhou85** [comment]
Thank you! @LichKing-2234 , aha! that help explains. Do you know any examples of how to add the wav file in native environment and get the path to be used in RN?

**Comment by LichKing-2234** [comment]
https://github.com/AgoraIO-Community/react-native-agora/blob/master/example/src/examples/basic/JoinChannelAudio.tsx#L141

**Comment by hongzhou85** [comment]
Thanks @LichKing-2234 , I went ahead to use RNFS instead and it works. :))
