### ISSUE TITLE
Frozen when switch camera

### ISSUE THREAD

**Issue by phuocantd** [AgoraIO-Community/react-native-agora#399]
When I switch camera it returns frozen
Also while streaming it sometimes returns frozen
Any ideas help me? Thanks

**Comment by LichKing-2234** [comment]
which return frozen? the LocalVideoStateChanged event?

**Comment by phuocantd** [comment]
I listener 'RemoteVideoStateChanged' to join view stream and return state VideoRemoteState.Frozen(=3)

**Comment by LichKing-2234** [comment]
does it recover normally finally?

**Comment by phuocantd** [comment]
then it's normal to watch but sometimes it's frozen even though I don't take any action

I don't want to return frozen because it will show black screen

**Comment by LichKing-2234** [comment]
Cloud you pls provide the SDK log? You can get more info from the comment on the `setLogFile` method.

**Comment by phuocantd** [comment]
using https://github.com/BeTomorrow/react-native-file-logger ???

**Comment by LichKing-2234** [comment]
No, our SDK log file.

**Comment by phuocantd** [comment]
seems when i setTimeout when frozen it doesn't show black screen

**Comment by lamlengend98** [comment]
@phuocantd i wonder how to switch camera

**Comment by phuocantd** [comment]
> @phuocantd i wonder how to switch camera

engine.switchCamera() nha
