### ISSUE TITLE
IOS react-native 0.66.0 build error

### ISSUE THREAD

**Issue by dagouzhi** [AgoraIO-Community/react-native-agora#417]
Build target react-native-agora of project Pods with configuration Release

CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'react-native-agora' from project 'Pods')

**Comment by LichKing-2234** [comment]
you should new a empty swift file to your root project to upgrade your swift.

**Comment by dagouzhi** [comment]
0.65.1是正常的，更新0.66.0后出现问题

**Comment by LichKing-2234** [comment]
方法应该就是上面发的，一些三方库和swift的版本兼容的问题

**Comment by edbaymax** [comment]
DId you solve your issue ?

**Comment by LichKing-2234** [comment]
> you should new a empty swift file to your root project to upgrade your swift.

Pls try this.
