### ISSUE TITLE
Join a channel but render my camera

### ISSUE THREAD

**Issue by lamlengend98** [AgoraIO-Community/react-native-agora#418]
I have a stream web, when i created channel on web, it returned agora channelName and token
I joined by using my mobile app successful but my app render phone's camera but web camera
i wonder what i was wrong or mobile cannot render web's cam

`"react-native-agora": "^3.5.0"
"react-native": "0.65.1"`

`{joined ? (
              <RtcLocalView.SurfaceView
                style={styles.container}
                renderMode={VideoRenderMode.Hidden}
              />
            ) : (
              <Container containerStyle={styles.container} />
            )}`

**Comment by LichKing-2234** [comment]
have you tried our example?

**Comment by lamlengend98** [comment]
> have you tried our example?

yes, i tried before, for your example i used 2 phones and it's worked
But this case is 1 phone and 1 web, i don't know what i was wrong

**Comment by lamlengend98** [comment]
> have you tried our example?

can you support me via skype?

**Comment by lamlengend98** [comment]
Solved. Use RtcLocalView instead of RtcRemoteView
