### ISSUE TITLE
Apple Silicon support (M1)

### ISSUE THREAD

**Issue by radko93** [AgoraIO-Community/react-native-agora#433]
Seems like Agora will not support M1 MacBooks when using Cocoapods so I started to create a workaround for this.

1. Download Agora SDK with the same version as in the podspec (you can use `install.sh` that is in this repo already)
2. You need to extract the `*.framework` from `ios-x86_64_arm64-simulator` folder inside `*.xcframework` and put those in a folder `agora-m1/` in your root.
3. Run `tar -cvzf agora-m1.tgz agora-m1`
4. Create `patch-agora-m1.sh` in the root directory with the following: 
```
#!/bin/bash
libs="ios/Pods/AgoraRtcEngine_iOS"
unzipped_libs="agora-m1/"

if [ "$(uname -s)" == 'Darwin' ] && [ "$(uname -m)" == 'arm64' ]; then
    echo "Patching agora frameworks for M1..."
        tar -xzf agora-m1.tgz
        rm -rf ${libs:?}/*
        for framework in $(find $unzipped_libs -iname '*.framework'); do
            mv -f "$framework" $libs
        done
    echo "Patching done."
fi
```
5. In your Podfile add one line to invoke the script
```
post_install do |installer|
  ...
  # We patch agora frameworks on M1 machines only
  system("sh ../patch-agora-m1.sh")
end
```

You might need to modify the script to your needs, it can also be improved a lot (looking for help on that). Please mind that you will have to reinstall the original files if you want to run on a real device/build for release mode.

**Comment by LichKing-2234** [comment]
is our SDK works on native project?

**Comment by radko93** [comment]
The SDK downloaded from Swift Package Manager & the website from a link (from `install.sh`) has XCFramework has support for Apple M1.

**Comment by nyoung697** [comment]
Hi @radko93, is this meant to patch agora so it will run on a simulator on the new Mac M1s?  I am still having issues building the project after following the above workaround.  It is isolated specifically to adding 'react-native-agora'.

I set up a blank RN project using `react-native init` just to try and isolate the issue.  I am able to build and run it on the simulator before adding agora.

The error I am getting now is: 

> ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/nick/Documents/Projects/test/ios/Pods/AgoraRtcEngine_iOS/AgoraAIDenoiseExtension.framework/AgoraAIDenoiseExtension' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Do you have any ideas?  I double checked that I was running your patch script properly.  I see both "Patching agora frameworks for M1..." and "Patching done." printed out after running npx pod-install.

I also tried some of the other suggestions I found and combinations of all of them, without any luck.

Like excluding arm64 as per this post: (which caused other issues with yogakit)
https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io

Also added this to my podfile:

```
...
installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
        end
      end
      aggregate_target.user_project.save
    end

    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end

    # We patch agora frameworks on M1 machines only
    system("sh ../patch-agora-m1.sh")
...
```

Thank you!

**Comment by nyoung697** [comment]
For anyone else looking at this, the version I had to download was v3.5.0.4.  I couldn't figure out how to do it with the install.sh script, so I got it from Agora's website.  It is a bit confusing, as react-native-agora's package shows v3.5.1 as the most recent release, so I figured it would match up with the native package version 3.5.1.

https://docs-preprod.agora.io/en/Voice/release_ios_audio?platform=iOS#v3504
https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v3_5_0_4_VOICE.zip

However, it was complaining about the `getAudioMixingDuration` method, which was deprecated in version 3.5.1 on the native side and hasn't been updated yet in the RN library.

Once I downloaded the proper SDK version, this solution worked for me.  

I also had to add the following to my Podfile:

```
installer.pods_project.build_configurations.each do |config|
  config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
end
```

So the post_install code block looks like this:

```
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end

  # We patch agora frameworks on M1 machines only
  system("sh ./patch-agora-m1.sh")

  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
```

**Comment by LichKing-2234** [comment]
> For anyone else looking at this, the version I had to download was v3.5.0.4. I couldn't figure out how to do it with the install.sh script, so I got it from Agora's website. It is a bit confusing, as react-native-agora's package shows v3.5.1 as the most recent release, so I figured it would match up with the native package version 3.5.1.
> 
> https://docs-preprod.agora.io/en/Voice/release_ios_audio?platform=iOS#v3504 https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v3_5_0_4_VOICE.zip
> 
> However, it was complaining about the `getAudioMixingDuration` method, which was deprecated in version 3.5.1 on the native side and hasn't been updated yet in the RN library.
> 
> Once I downloaded the proper SDK version, this solution worked for me.
> 
> I also had to add the following to my Podfile:
> 
> ```
> installer.pods_project.build_configurations.each do |config|
>   config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
> end
> ```
> 
> So the post_install code block looks like this:
> 
> ```
> post_install do |installer|
>   installer.pods_project.build_configurations.each do |config|
>     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
>   end
> 
>   # We patch agora frameworks on M1 machines only
>   system("sh ./patch-agora-m1.sh")
> 
>   react_native_post_install(installer)
>   __apply_Xcode_12_5_M1_post_install_workaround(installer)
> end
> ```

Why do you use `install.sh`? it for RN 0.59.x
https://github.com/AgoraIO-Community/react-native-agora#installing-react-native--059x

**Comment by radko93** [comment]
@LichKing-2234 we didn't know that's the case. Anyway, it was an easy way to get the Agora frameworks downloaded.

**Comment by radko93** [comment]
This is no longer needed from 3.6.2.
