### ISSUE TITLE
Unable to view stream from web

### ISSUE THREAD

**Issue by lucienbl** [AgoraIO-Community/react-native-agora#439]
Hello,

It's been a few days I'm trying to achieve this and it just doesn't work and I have no idea why so I'm asking here if maybe someone knows what the issue is. I have a react native app using this package which is streaming video as a "host". I followed the live streaming examples for implementation. I can successfully join a channel, however it absolutely doesn't work when I'm trying to watch the stream from a web implementation. It doesn't even trigger `user-joined` on web when I join the channel from the react native app. 
Note that web to web works well using the example projects...

Why do I have the strange behaviour ? Does anybody has or had the same problem or a solution for this ?

Thank you very much in advance, I'm completely lost !

**Comment by LichKing-2234** [comment]
video call from web to react native?

**Comment by lucienbl** [comment]
@LichKing-2234 it’s a live streaming from react-native to web

**Comment by LichKing-2234** [comment]
Maybe you are using the same uid?

**Comment by lucienbl** [comment]
@LichKing-2234 It seems like it was indeed an uid issue, but not because I'm using the same but because we were using a string uid on the web part. Thanks for your support, I'm closing the issue.
