### ISSUE TITLE
Unable to route to Home Screen from the Call Screen

### ISSUE THREAD

**Issue by Asher978** [AgoraIO-Community/react-native-agora#444]
After trying to route the user to the home screen on call end, the `Call` screen re-renders.

using React Navigation

``` js

const endCall = async () => {
    console.log("END CALL IN CALL SCREEN", navigation);
    navigation.navigate("Home");
  };

```

**Comment by LichKing-2234** [comment]
Have you tried it on our example?

**Comment by Asher978** [comment]
Please close this issue. After troubleshooting the error was on my end. 
Apologies of submitting this
