### ISSUE TITLE
Virtual background color inconsistent across iOS and Android

### ISSUE THREAD

**Issue by EkaanshArora** [AgoraIO-Community/react-native-agora#451]
Hi Team, what's the range of the expected red, green and blue values when defining a color for virtual background? I read the docs  and the type definitions but couldn't find the range/bounds. I tried a few different ranges and had inconsistent results between colors on iOS, I tried float value (0-1), percentages (0-100) and 8-bit color (0-255). What's the right way to generate a color using RGB values?

However I wasn't able to get the color to work on Android at all. I used the following snippet and got Red background on iOS but Android only shows white background no matter what I try. Can you tell me what is that I'm doing wrong? (screenshots attached)

```jsx
    await this._engine.enableVideo();
    let color = new Color(1, 0, 0);
    let colorSource = new VirtualBackgroundSource({
      backgroundSourceType: VirtualBackgroundSourceType.Color,
      color: color,
    })
    await this._engine.enableVirtualBackground(true, colorSource);
```
iOS 
![IMG_3502](https://user-images.githubusercontent.com/10047883/145846786-c348b625-602b-449b-8806-51879a83b57f.png)
Android 
![Screenshot_20211213-211424](https://user-images.githubusercontent.com/10047883/145846801-ef0a0e41-3d4c-4353-9cae-fb0832856799.png)

**Comment by digitallysavvy** [comment]
@LichKing-2234 can you please take a look at this issue and provide some guidance?

**Comment by EkaanshArora** [comment]
@sanjithmsk the error suggests you're passing an incorrect path to your resource, I'd suggest double checking if you're getting the correct absolute path and that the image file is cached to that location. I've added image as virtual background to the quickstart project, you can find the [source code here](https://github.com/EkaanshArora/Agora-RN-VirtualBackground). Hope that helps!

**Comment by LichKing-2234** [comment]
have you tried the latest version?

**Comment by EkaanshArora** [comment]
@LichKing-2234 I posted the above issue/screenshots while using `v3.5.1`.

Using `v3.5.2-rc.0` I still get `ColorFormatNotSupported` while setting color on Android like so: `let color = new Color(1, 0, 0);`.

Can you tell me the expected format for the color constructor?

**Comment by LichKing-2234** [comment]
@EkaanshArora The color is 0-255

**Comment by EkaanshArora** [comment]
If the range is 0-255, the code snippet I posted `let color = new Color(1, 0, 0)` should not give red, but rather close to black. It's not working as expected on iOS and it doesn't work at all on Android (as mentioned in #453).

**Comment by LichKing-2234** [comment]
fixed by https://github.com/AgoraIO-Community/react-native-agora/pull/471

**Comment by EkaanshArora** [comment]
@LichKing-2234 thanks for the update, `v3.5.3` fixes the Android issue. iOS still has problem: 
`Color(100, 0, 0)` gives a dark red as expected on Android but defaults to white on iOS.

**Comment by LichKing-2234** [comment]
@EkaanshArora 
Pls try to modify this line to `backgroundSource.color = (UInt(red * 255.0) << 16) + (UInt(green * 255.0) << 8) + UInt(blue * 255.0)` then test it.
https://github.com/AgoraIO-Community/react-native-agora/blob/master/ios/RCTAgora/Base/BeanCovertor.swift#L430
