### ISSUE TITLE
Virtualbackground - ColorFormatNotSupported

### ISSUE THREAD

**Issue by codemeall** [AgoraIO-Community/react-native-agora#453]
Trying to pass the color format, it works in iOS but always throws `ColorFormatNotSupported` for android,

here is the code below which I am using

        let color = new Color(0, 0, 0); // For Black color
        let color = new Color(1, 1, 1);   // For White color
        
        let source = new VirtualBackgroundSource({
            backgroundSourceType: VirtualBackgroundSourceType.Color,
            color: color
        });
        this._engine.enableVirtualBackground(true, source);
`

**Comment by LichKing-2234** [comment]
the color is 0-255

**Comment by EkaanshArora** [comment]
I'm facing the same issue on Android using the latest version of the SDK.

**Comment by LichKing-2234** [comment]
fixed by https://github.com/AgoraIO-Community/react-native-agora/pull/471
