### ISSUE TITLE
Building for iOS Simulator, but linking in dylib built for iOS for architecture arm64

### ISSUE THREAD

**Issue by workhexaloop** [AgoraIO-Community/react-native-agora#460]
Please help facing this issue

Building for iOS Simulator, but linking in dylib built for iOS
/ios/Pods/AgoraRtcEngine_iOS/AgoraAIDenoiseExtension.framework/AgoraAIDenoiseExtension' for architecture arm64

```
react: "17.0.2",
react-native: "0.66.4",
react-native-agora: "^3.5.1"
MackBook Air M1, 
Xcode: Version 13.1 (13A1030d)
```

**Comment by LichKing-2234** [comment]
https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io

**Comment by radko93** [comment]
check #433, Agora does not support Simulators on Apple M1 out of the box.

**Comment by workhexaloop** [comment]
thanks radko93 it's working on device
