### ISSUE TITLE
"export 'requireNativeComponent' was not found in 'react-native-web/dist/index'

### ISSUE THREAD

**Issue by martianmartian** [AgoraIO-Community/react-native-agora#462]
./node_modules/react-native-agora/lib/module/common/RtcRenderView.native.js:102:26
"export 'requireNativeComponent' was not found in 'react-native-web/dist/index'
  100 |  * @ignore
  101 |  */
> 102 | const RCTRtcTextureView = requireNativeComponent<RtcRenderViewProps>(
      |                          ^
  103 |   'RCTAgoraRtcTextureView'
  104 | );
  105 | 

Got this error message. I'm using following setup.

```

 "dependencies": {
    "@react-native-masked-view/masked-view": "0.2.6",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "agora-rn-uikit": "^3.3.0",
    "axios": "^0.24.0",
    "expo": "~44.0.0",
    "expo-dev-client": "^0.8.0",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-agora": "^3.5.1",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.64.12",
    "typescript": "~4.3.5"
  },
```

the project was setup using expo, the newest configuration. probably some compatibility issues. I tried to down grade agora to lower version, same issue. maybe beause the react is too new? 17.0.1 

using m1 macbook air

**Comment by martianmartian** [comment]
oh shoot, eject first

**Comment by LichKing-2234** [comment]
Our package does not support `react-native-web`
