### ISSUE TITLE
TypeError: null is not an object (evaluating 'Agora.FPS30') 

### ISSUE THREAD

**Issue by syedfahadhussain-rn** [AgoraIO-Community/react-native-agora#467]
Hi, 
I am new to react native,
We have used react-native-agora@2.9.1-alpha.6 before it got deprecated,
And I can't able to connect video calls and gets lot of warning in my code,

So I decided to update new agora package and I have updated to react-native-agora 3.5.2,
But I am getting TypeError: null is not an object (evaluating 'Agora.FPS30') in index.bundle,
Any suggestion or idea to solve this issue

![Screenshot (35)](https://user-images.githubusercontent.com/91606927/149734177-802899be-280f-4c68-989b-9be558ee514d.png)

ERROR    TypeError: null is not an object (evaluating 'Agora.FPS30')
ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by syedfahadhussain-rn** [comment]
@LichKing-2234 can you help on this..?

**Comment by LichKing-2234** [comment]
Seem like you are using the legacy version, pls follow our example to upgrade.

**Comment by syedfahadhussain-rn** [comment]
@LichKing-2234 I have followed the example,
Please help to fix this.

**Comment by Auspicious77** [comment]
I have same error,
Please, help me solution to fix it
