### ISSUE TITLE
 native-full-sdk-3.5.2.aar not accessible

### ISSUE THREAD

**Issue by rauljr11** [AgoraIO-Community/react-native-agora#469]
Please help!
My internet connection is fine but native-full-sdk-3.5.2.aar could not be downloaded.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform native-full-sdk-3.5.2.aar (com.github.agorabuilder:native-full-sdk:3.5.2) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not download native-full-sdk-3.5.2.aar (com.github.agorabuilder:native-full-sdk:3.5.2)
         > Could not get resource 'https://www.jitpack.io/com/github/agorabuilder/native-full-sdk/3.5.2/native-full-sdk-3.5.2.aar'.
            > Read timed out

I also tried downloading it manually through https://www.jitpack.io/com/github/agorabuilder/native-full-sdk/3.5.2/native-full-sdk-3.5.2.aar but still not working.

**Comment by LichKing-2234** [comment]
Sorry for the late reply, I think this issue has been fixed now.

**Comment by dhimanrascon** [comment]
Same issue for me

**Comment by dhimanrascon** [comment]
Running Gradle task 'assembleDevRelease'...                     

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:compileReleaseKotlin'.
> Could not resolve all files for configuration ':agora_rtc_engine:***CompileClasspath'.
   > Failed to transform native-full-sdk-3.5.2.jar (com.github.agorabuilder:native-full-sdk:3.5.2) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=***, org.gradle.usage=java-api}.
      > Could not find native-full-sdk-3.5.2.jar (com.github.agorabuilder:native-full-sdk:3.5.2).
        Searched in the following locations:
            https://www.jitpack.io/com/github/agorabuilder/native-full-sdk/3.5.2/native-full-sdk-3.5.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

**Comment by YuTaeKim** [comment]
same issue for me

**Comment by LichKing-2234** [comment]
It is a bug from the jetpack. The latest version has fixed this issue because we have migrated to maven.

https://www.npmjs.com/package/react-native-agora/v/3.6.2

**Comment by navaneeth001** [comment]
> Sorry for the late reply, I think this issue has been fixed now.

how was it fixed?

**Comment by LichKing-2234** [comment]
> > Sorry for the late reply, I think this issue has been fixed now.
> 
> how was it fixed?

the 3.6.2 version has migrated to maven
