### ISSUE TITLE
Can't able to call after update

### ISSUE THREAD

**Issue by syedfahadhussain-rn** [AgoraIO-Community/react-native-agora#473]
@LichKing-2234 

we have used same code for two different apps to communicate and its works on react-native-agora @alpha before it got depreciated,
know we have updated to the latest but video enables in one app only, in another app nothing is happen only shows a warning 
Error: request to join channel is rejected 
when tried twice,
need your help to fix this

**Comment by LichKing-2234** [comment]
pls provide the SDK log.

**Comment by syedfahadhussain-rn** [comment]
"react-native-agora": "^3.5.2",
  "react": "17.0.2",
  "react-native": "0.66.4",

@LichKing-2234

**Comment by LichKing-2234** [comment]
I mean our SDK log file, you can refer to the comments of `setLogFile` method to get more information.

**Comment by syedfahadhussain-rn** [comment]
Sorry I won't get properly what you asking exactly @LichKing-2234

**Comment by syedfahadhussain-rn** [comment]
Just know get that agora won't supporting in android version more than 10
