### ISSUE TITLE
Warning 106 and error 18

### ISSUE THREAD

**Issue by syedfahadhussain-rn** [AgoraIO-Community/react-native-agora#474]
Getting Warning 106 while trying to joinChannelVideo and joinChannelAudio.

@LichKing-2234 do you suggest any Idea to fix this.

**Comment by CMLCNL** [comment]
_A timeout occurs when joining the channel. Once the specified channel is found, the SDK starts joining the channel. This warning usually occurs when the network connection is too poor for the SDK to connect to the server._

i am using agora and i never seen this error. maybe you must check your logic or your code.
