### ISSUE TITLE
Audio volume decreases  when using multiple audio apps at the same time

### ISSUE THREAD

**Issue by buog** [AgoraIO-Community/react-native-agora#484]
I realized when I run engine.enableAudio(), the volume decreases for other apps but my app volume is fine. I want the app to have full volume of audio for all the external app when there are multiple audio through different apps. (Like the listener mode in Clubhouse) I tried  engine.enableLocalAudio(false) but it didn't help. Is this possible to do in agora?

**Comment by LichKing-2234** [comment]
I think you should control Audio Session by yourself.

**Comment by manjubhatt** [comment]
any update on this?
