### ISSUE TITLE
Could not find native-full-sdk-3.5.2.jar (com.github.agorabuilder:native-full-sdk:3.5.2)

### ISSUE THREAD

**Issue by arsyrangga** [AgoraIO-Community/react-native-agora#486]
please help, error while build release..

stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Could not determine the dependencies of task ':app:lintVitalRelease'.
[stderr] > Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
[stderr]    > Could not find native-full-sdk-3.5.2.jar (com.github.agorabuilder:native-full-sdk:3.5.2).
[stderr]      Searched in the following locations:
[stderr]          https://www.jitpack.io/com/github/agorabuilder/native-full-sdk/3.5.2/native-full-sdk-3.5.2.jar
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 1m 44s

**Comment by tvc97** [comment]
same issue here, older versions are also not working

**Comment by tvc97** [comment]
@LichKing-2234 Can you take a look at this issue. We can't build our production app until this issue is resolved

**Comment by badgeek** [comment]
same here, cant build production app

**Comment by stevanusw28** [comment]
@LichKing-2234 same here, can you view this issue?

**Comment by badgeek** [comment]
are there any jitpack mirror ?

**Comment by LichKing-2234** [comment]
It is a bug from the jetpack. The latest version has fixed this issue because we have migrated to maven.

https://www.npmjs.com/package/react-native-agora/v/3.6.2

**Comment by badgeek** [comment]
should we react native link again when upgrading? @LichKing-2234  

thanks

**Comment by sanjay628** [comment]
After updating with new version i.e 3.6.2 i am facing some issues in IOS and android issue is still not resolved
Android issue - :

stderr] FAILURE: Build failed with an exception. [stderr] * What went wrong: [stderr] Could not determine the dependencies of task ':app:lintVitalRelease'. [stderr] > Could not resolve all artifacts for configuration ':app:debugCompileClasspath'. [stderr] > Could not find native-full-sdk-3.5.2.jar (com.github.agorabuilder:native-full-sdk:3.5.2). [stderr] Searched in the following locations: [stderr] https://www.jitpack.io/com/github/agorabuilder/native-full-sdk/3.5.2/native-full-sdk-3.5.2.jar [stderr] * Try: [stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. [stderr] * Get more help at https://help.gradle.org/ [stderr] BUILD FAILED in 1m 44s


IOS issue -:


<img width="1111" alt="Screenshot 2022-04-13 at 3 35 02 PM" src="https://user-images.githubusercontent.com/54932767/163154982-dead5e2c-4c7d-4031-a845-67715e0d6426.png">
<img width="1406" alt="Screenshot 2022-04-13 at 3 35 32 PM" src="https://user-images.githubusercontent.com/54932767/163155139-7961dd7d-f1e7-4463-8fa5-9682259d9752.png">

**Comment by chiefninew** [comment]
It works after upgrading to the latest version. just run pod deintegrate then pod install if you're facing a problem with pods

**Comment by arsyrangga** [comment]
I just solved this issue, 

First, 
`yarn remove react-native-agora`

And then install again with version 3.5.0
`yarn add react-native-agora@3.5.0`

I hope this help you thanks

**Comment by badgeek** [comment]
@LichKing-2234 should we down grade or upgrade, @arsyrangga solved it by downgrading it

**Comment by arsyrangga** [comment]
Yeah, I was downgrade from v.3.5.3 to v.3.5.0 and issue has been fixed
