### ISSUE TITLE
switchCamera doesn't work on the latest version

### ISSUE THREAD

**Issue by tvc97** [AgoraIO-Community/react-native-agora#491]
switchCamera doesn't work on the latest version

Platform: Android
react-native-agora verison: 3.6.2
react-native version: 0.66.3

**Comment by LichKing-2234** [comment]
is our example working?

**Comment by phuocantd** [comment]
same in version 3.7.0

**Comment by tvc97** [comment]
Caused by conflict with another library. In my case, the other library is using the front camera, so it won't be able to switch to the back camera. Closing this issue for now.
