### ISSUE TITLE
Stretched or distorted image on some Android devices. 

### ISSUE THREAD

**Issue by nornewman** [AgoraIO-Community/react-native-agora#497]
Using agora RN 3.7.0
Some users see distorted android image on this device: Android - Samsung J7 prime
Don't know whether we need to add any config. Distorted image is seen on iOS, when talking with Android. 

<img width="314" alt="image" src="https://user-images.githubusercontent.com/34377396/168425264-f7754885-9696-4de0-8d8b-7db451c33080.png">

**Comment by LichKing-2234** [comment]
you can try the render mode (the property of the RtcSurfaceView or RtcTextureView component)

Distorted image (you can try [setVideoEncorderConfigurarion](https://docs.agora.io/cn/Interactive%20Broadcast/API%20Reference/react_native/classes/rtcengine.html?platform=React%20Native#setvideoencoderconfiguration))

**Comment by nornewman** [comment]
I don't have any updates from client on this issue, looks like the latest library version fixed it? Closing it now.
