### ISSUE TITLE
App size reduction.

### ISSUE THREAD

**Issue by nornewman** [AgoraIO-Community/react-native-agora#498]
I've tried to follow app size reduction best practices from your guide for React Native.
https://docs.agora.io/en/Video/reduce_rtc_app_size?platform=iOS
But it just doesn't seem to work. All of the libraries are getting installed on both platforms.
I've tried to update my projects pod file, and gradle file, but it looks like this is ignored, all all libraries are being installed as per your node_modules/react-native-agora settings. Could you please hint on how can I possibly change it for Android and iOS there?

I think I've had some success by changing it for Android in:
./node_modules/react-native-agora/android/build.gradle
From
api 'io.agora.rtc:full-rtc:3.7.0'
To
api 'io.agora.rtc:full-rtc-basic:3.7.0'

But I'm not sure if that's the best way, and also how to do it for iOS in that folder, as it doesn't have pod file.

I appreciate your support!

**Comment by LichKing-2234** [comment]
this for iOS
https://github.com/AgoraIO-Community/react-native-agora/blob/master/react-native-agora.podspec

**Comment by nornewman** [comment]
Thank you! Yes, found it as well. 
I see it refers to
`s.dependency "AgoraRtcEngine_iOS", "3.7.0"`
As full data library.

So I tried to specify a short subspecs like this, but looks like the syntax is not right for podspec file.
`s.dependency "AgoraRtcEngine_iOS", "3.7.0", :subspecs => ['RtcBasic']`
 
 I'd appreciate any help on this!
Looks like Android works well.

**Comment by LichKing-2234** [comment]
> podspec

Try add this to your Podfile?

**Comment by LichKing-2234** [comment]
I think if it not be compiled to your app is fine.

**Comment by yogeshydvme** [comment]
I am facing same issue, what is right way to go about remove these dependencies, given latest react native version is autolinking package from node modules and ignoring any changes to pod file or gradle

**Comment by yogeshydvme** [comment]
Where should we make change to only keep RTC basic dependency

**Comment by Ping5841** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/16773559/169749635-f583d85a-44af-45c7-a348-a336cf87180e.png">
works well in my project.

**Comment by yogeshydvme** [comment]
But this works only for ios right, How about android?

**Comment by Ping5841** [comment]
> But this works only for ios right, How about android?

just like nornewman said changing it for Android in:
./node_modules/react-native-agora/android/build.gradle
From
api 'io.agora.rtc:full-rtc:3.7.0'
To
api 'io.agora.rtc:full-rtc-basic:3.7.0'
