### ISSUE TITLE
Could not find native-full-sdk-3.4.6.jar (com.github.agorabuilder:native-full-sdk:3.4.6).

### ISSUE THREAD

**Issue by dylancolin** [AgoraIO-Community/react-native-agora#502]
Hi, just installed 3.4.6 in my project.  IOS builds fine. Android giving error 

* What went wrong:
Execution failed for task ':react-native-agora:compileDebugKotlin'.
> Could not resolve all artifacts for configuration ':react-native-agora:debugCompileClasspath'.
   > Could not find native-full-sdk-3.4.6.jar (com.github.agorabuilder:native-full-sdk:3.4.6).
     Searched in the following locations:
         https://www.jitpack.io/com/github/agorabuilder/native-full-sdk/3.4.6/native-full-sdk-3.4.6.jar

Do not have an option to upgrade/downgrade agora version. Please help!

System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1
    Memory: 30.23 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 12.22.12 - ~/.nvm/versions/node/v12.22.12/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v12.22.12/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v12.22.12/bin/npm
    Watchman: 2022.05.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by caferyukseloglu** [comment]
As output says it can't fin native module implimentation because the url is changed please check new url here : https://jarcasting.in/artifacts/io.agora.rtc/full-sdk/

I guess it was in build.gradle file so find the imlimentation than change url to new one which is io.agora.rtc:full-sdk:<your_version>.  Sync  files then re build it

**Comment by LichKing-2234** [comment]
pls try the latest version, it has migrated to maven.
